BEGIN;

CREATE TABLE IF NOT EXISTS axionpro."AttendancePolicyVersionConfiguration"
(
    "Id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "TenantId" bigint NOT NULL,
    "PolicyVersionId" bigint NOT NULL,
    "AttendanceLocationScope" smallint NOT NULL,
    "AllowBiometric" boolean NOT NULL,
    "AllowMobile" boolean NOT NULL,
    "AllowWeb" boolean NOT NULL,
    "AllowManualAttendance" boolean NOT NULL,
    "AllowWorkFromHome" boolean NOT NULL,
    "RequireGeoFenceForOffice" boolean NOT NULL,
    "RequireGpsForRemote" boolean NOT NULL,
    "AllowOutsideLocationWithApproval" boolean NOT NULL,
    "AddedById" bigint NOT NULL,
    "AddedDateTime" timestamp with time zone NOT NULL,
    "UpdatedById" bigint NULL,
    "UpdatedDateTime" timestamp with time zone NULL,
    CONSTRAINT "FK_AttendancePolicyVersionConfiguration_Tenant"
        FOREIGN KEY ("TenantId") REFERENCES axionpro."Tenant" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_AttendancePolicyVersionConfiguration_PolicyVersion"
        FOREIGN KEY ("PolicyVersionId") REFERENCES axionpro."PolicyVersion" ("Id") ON DELETE CASCADE,
    CONSTRAINT "CK_AttendancePolicyVersionConfiguration_LocationScope"
        CHECK ("AttendanceLocationScope" BETWEEN 1 AND 4),
    CONSTRAINT "CK_AttendancePolicyVersionConfiguration_Channel"
        CHECK ("AllowBiometric" OR "AllowMobile" OR "AllowWeb" OR "AllowManualAttendance")
);

CREATE UNIQUE INDEX IF NOT EXISTS "UX_AttendancePolicyVersionConfiguration_PolicyVersion"
    ON axionpro."AttendancePolicyVersionConfiguration" ("PolicyVersionId");

CREATE UNIQUE INDEX IF NOT EXISTS "UX_AttendancePolicyVersionConfiguration_TenantVersion"
    ON axionpro."AttendancePolicyVersionConfiguration" ("TenantId", "PolicyVersionId");

-- Existing Attendance versions receive compatibility settings so deployment does not invalidate them.
INSERT INTO axionpro."AttendancePolicyVersionConfiguration"
(
    "TenantId", "PolicyVersionId", "AttendanceLocationScope",
    "AllowBiometric", "AllowMobile", "AllowWeb", "AllowManualAttendance", "AllowWorkFromHome",
    "RequireGeoFenceForOffice", "RequireGpsForRemote", "AllowOutsideLocationWithApproval",
    "AddedById", "AddedDateTime"
)
SELECT version."TenantId", version."Id", 2,
       true, true, true, true, true,
       false, false, true,
       version."AddedById", CURRENT_TIMESTAMP
FROM axionpro."PolicyVersion" version
JOIN axionpro."Policy" policy ON policy."Id" = version."PolicyId" AND policy."TenantId" = version."TenantId"
JOIN axionpro."PolicyType" policy_type ON policy_type."Id" = policy."PolicyTypeId" AND policy_type."TenantId" = version."TenantId"
JOIN axionpro."PolicyCategory" category ON category."Id" = policy_type."PolicyCategoryId"
WHERE upper(category."CategoryCode") = 'ATTENDANCE'
  AND NOT EXISTS
  (
      SELECT 1
      FROM axionpro."AttendancePolicyVersionConfiguration" existing
      WHERE existing."PolicyVersionId" = version."Id"
  );

COMMIT;
