BEGIN;

CREATE TABLE IF NOT EXISTS axionpro."EmployeeMonitoringPolicy" (
    "Id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "TenantId" bigint NOT NULL,
    "MinimumCaptureIntervalSeconds" integer NOT NULL,
    "MaximumCaptureIntervalSeconds" integer NOT NULL,
    "HeartbeatIntervalSeconds" integer NOT NULL,
    "DelayedAfterSeconds" integer NOT NULL,
    "UnreachableAfterSeconds" integer NOT NULL,
    "OfflineRetentionDays" integer NOT NULL,
    "MaximumOfflineBytes" bigint NOT NULL,
    "ImageQuality" integer NOT NULL,
    "CaptureAllMonitors" boolean NOT NULL,
    "IsActive" boolean NOT NULL,
    "IsSoftDeleted" boolean NOT NULL,
    "AddedById" bigint NOT NULL,
    "AddedDateTime" timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "UpdatedById" bigint NULL,
    "UpdatedDateTime" timestamp without time zone NULL,
    CONSTRAINT "FK_EmployeeMonitoringPolicy_Tenant" FOREIGN KEY ("TenantId")
        REFERENCES axionpro."Tenant" ("Id") ON DELETE RESTRICT
);

CREATE UNIQUE INDEX IF NOT EXISTS "UX_EmployeeMonitoringPolicy_Tenant"
    ON axionpro."EmployeeMonitoringPolicy" ("TenantId")
    WHERE "IsActive" = true AND "IsSoftDeleted" = false;

CREATE TABLE IF NOT EXISTS axionpro."EmployeeMonitoringAgent" (
    "Id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "AgentInstanceId" uuid NOT NULL,
    "TenantId" bigint NOT NULL,
    "EmployeeId" bigint NOT NULL,
    "PolicyId" bigint NOT NULL,
    "DeviceName" character varying(200) NOT NULL,
    "CredentialHash" character varying(64) NOT NULL,
    "AgentVersion" character varying(50) NULL,
    "LastHeartbeatDateTime" timestamp without time zone NULL,
    "LastCaptureDateTime" timestamp without time zone NULL,
    "LastSuccessfulUploadDateTime" timestamp without time zone NULL,
    "PendingCaptureCount" integer NOT NULL,
    "LastErrorCode" character varying(100) NULL,
    "IsActive" boolean NOT NULL,
    "IsSoftDeleted" boolean NOT NULL,
    "AddedById" bigint NOT NULL,
    "AddedDateTime" timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "UpdatedById" bigint NULL,
    "UpdatedDateTime" timestamp without time zone NULL,
    CONSTRAINT "FK_EmployeeMonitoringAgent_Tenant" FOREIGN KEY ("TenantId") REFERENCES axionpro."Tenant" ("Id") ON DELETE RESTRICT,
    CONSTRAINT "FK_EmployeeMonitoringAgent_Employee" FOREIGN KEY ("EmployeeId") REFERENCES axionpro."Employee" ("Id") ON DELETE RESTRICT,
    CONSTRAINT "FK_EmployeeMonitoringAgent_Policy" FOREIGN KEY ("PolicyId") REFERENCES axionpro."EmployeeMonitoringPolicy" ("Id") ON DELETE RESTRICT
);

CREATE UNIQUE INDEX IF NOT EXISTS "UX_EmployeeMonitoringAgent_Instance" ON axionpro."EmployeeMonitoringAgent" ("AgentInstanceId");
CREATE UNIQUE INDEX IF NOT EXISTS "UX_EmployeeMonitoringAgent_CredentialHash" ON axionpro."EmployeeMonitoringAgent" ("CredentialHash");
CREATE INDEX IF NOT EXISTS "IX_EmployeeMonitoringAgent_Tenant_Employee" ON axionpro."EmployeeMonitoringAgent" ("TenantId", "EmployeeId");
CREATE INDEX IF NOT EXISTS "IX_EmployeeMonitoringAgent_LastHeartbeat" ON axionpro."EmployeeMonitoringAgent" ("LastHeartbeatDateTime");

CREATE TABLE IF NOT EXISTS axionpro."EmployeeScreenCapture" (
    "Id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "CaptureId" uuid NOT NULL,
    "TenantId" bigint NOT NULL,
    "EmployeeId" bigint NOT NULL,
    "MonitoringAgentId" bigint NOT NULL,
    "CapturedAtUtc" timestamp without time zone NOT NULL,
    "ReceivedAtUtc" timestamp without time zone NOT NULL,
    "MonitorNumber" integer NOT NULL,
    "ContentType" character varying(50) NOT NULL,
    "ContentLength" bigint NOT NULL,
    "ChecksumSha256" character varying(64) NOT NULL,
    "StorageObjectKey" character varying(1000) NOT NULL,
    CONSTRAINT "FK_EmployeeScreenCapture_Tenant" FOREIGN KEY ("TenantId") REFERENCES axionpro."Tenant" ("Id") ON DELETE RESTRICT,
    CONSTRAINT "FK_EmployeeScreenCapture_Employee" FOREIGN KEY ("EmployeeId") REFERENCES axionpro."Employee" ("Id") ON DELETE RESTRICT,
    CONSTRAINT "FK_EmployeeScreenCapture_Agent" FOREIGN KEY ("MonitoringAgentId") REFERENCES axionpro."EmployeeMonitoringAgent" ("Id") ON DELETE RESTRICT
);

CREATE UNIQUE INDEX IF NOT EXISTS "UX_EmployeeScreenCapture_Agent_Capture" ON axionpro."EmployeeScreenCapture" ("MonitoringAgentId", "CaptureId");
CREATE INDEX IF NOT EXISTS "IX_EmployeeScreenCapture_Tenant_Employee_Captured" ON axionpro."EmployeeScreenCapture" ("TenantId", "EmployeeId", "CapturedAtUtc");

COMMIT;
