BEGIN;

CREATE TABLE IF NOT EXISTS axionpro."EmployeeAttendancePunch"
(
    "Id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "TenantId" bigint NOT NULL,
    "EmployeeId" bigint NOT NULL,
    "EmployeeWorkArrangementId" bigint NOT NULL,
    "PolicyVersionId" bigint NOT NULL,
    "TenantLocationId" bigint NULL,
    "WorkDate" date NOT NULL,
    "OccurredAtUtc" timestamp with time zone NOT NULL,
    "ClientOccurredAt" timestamp with time zone NULL,
    "Channel" smallint NOT NULL,
    "PunchAction" smallint NOT NULL,
    "Latitude" numeric(10,7) NULL,
    "Longitude" numeric(10,7) NULL,
    "AccuracyMeters" numeric(10,2) NULL,
    "DistanceFromLocationMeters" numeric(12,2) NULL,
    "IdempotencyKey" uuid NOT NULL,
    "AddedById" bigint NOT NULL,
    "AddedDateTime" timestamp with time zone NOT NULL,
    CONSTRAINT "CK_EmployeeAttendancePunch_Channel" CHECK ("Channel" BETWEEN 1 AND 4),
    CONSTRAINT "CK_EmployeeAttendancePunch_Action" CHECK ("PunchAction" BETWEEN 1 AND 2),
    CONSTRAINT "CK_EmployeeAttendancePunch_Latitude" CHECK ("Latitude" IS NULL OR "Latitude" BETWEEN -90 AND 90),
    CONSTRAINT "CK_EmployeeAttendancePunch_Longitude" CHECK ("Longitude" IS NULL OR "Longitude" BETWEEN -180 AND 180),
    CONSTRAINT "FK_EmployeeAttendancePunch_Tenant" FOREIGN KEY ("TenantId") REFERENCES axionpro."Tenant" ("Id"),
    CONSTRAINT "FK_EmployeeAttendancePunch_Employee" FOREIGN KEY ("EmployeeId") REFERENCES axionpro."Employee" ("Id"),
    CONSTRAINT "FK_EmployeeAttendancePunch_Arrangement" FOREIGN KEY ("EmployeeWorkArrangementId") REFERENCES axionpro."EmployeeWorkArrangement" ("Id"),
    CONSTRAINT "FK_EmployeeAttendancePunch_PolicyVersion" FOREIGN KEY ("PolicyVersionId") REFERENCES axionpro."PolicyVersion" ("Id"),
    CONSTRAINT "FK_EmployeeAttendancePunch_Location" FOREIGN KEY ("TenantLocationId") REFERENCES axionpro."TenantLocation" ("Id")
);

CREATE UNIQUE INDEX IF NOT EXISTS "UX_EmployeeAttendancePunch_Idempotency"
    ON axionpro."EmployeeAttendancePunch" ("TenantId", "EmployeeId", "IdempotencyKey");
CREATE INDEX IF NOT EXISTS "IX_EmployeeAttendancePunch_DayTimeline"
    ON axionpro."EmployeeAttendancePunch" ("TenantId", "EmployeeId", "WorkDate", "OccurredAtUtc", "Id");

COMMIT;
