BEGIN;

ALTER TABLE axionpro."AttendanceDeviceType"
    ADD COLUMN IF NOT EXISTS "DeviceTypeCode" character varying(30);

INSERT INTO axionpro."AttendanceDeviceType"
    ("DeviceTypeCode", "DeviceType", "Remark", "IsActive", "IsDeviceRegister", "AddedById", "AddedDateTime")
SELECT seed."Code", seed."Name", seed."Remark", TRUE, seed."RequiresRegistration", 1, CURRENT_TIMESTAMP
FROM (VALUES
    ('MOBILE', 'Mobile', 'Attendance marked from an authenticated mobile client.', FALSE),
    ('WEB', 'Web', 'Attendance marked from an authenticated web client.', FALSE),
    ('BIOMETRIC', 'Biometric Device', 'Attendance received from a registered physical attendance device.', TRUE),
    ('MANUAL', 'Manual Entry', 'Attendance entered by an authorized administrator.', FALSE)
) AS seed("Code", "Name", "Remark", "RequiresRegistration")
WHERE NOT EXISTS (
    SELECT 1 FROM axionpro."AttendanceDeviceType" existing
    WHERE upper(btrim(existing."DeviceTypeCode")) = seed."Code");

ALTER TABLE axionpro."AttendanceDeviceType"
    ALTER COLUMN "DeviceTypeCode" SET NOT NULL;
CREATE UNIQUE INDEX IF NOT EXISTS "UX_AttendanceDeviceType_DeviceTypeCode"
    ON axionpro."AttendanceDeviceType" (upper(btrim("DeviceTypeCode")));

CREATE TABLE IF NOT EXISTS axionpro."EmployeeAttendancePunch"
(
    "Id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "TenantId" bigint NOT NULL,
    "EmployeeId" bigint NOT NULL,
    "EmployeeWorkArrangementId" bigint NOT NULL,
    "PolicyVersionId" bigint NOT NULL,
    "TenantLocationId" bigint NULL,
    "WorkDate" date NOT NULL,
    "OccurredAtUtc" timestamp with time zone NOT NULL,
    "ClientOccurredAt" timestamp with time zone NULL,
    "AttendanceDeviceTypeId" integer NOT NULL,
    "PunchAction" smallint NOT NULL,
    "Latitude" numeric(10,7) NULL,
    "Longitude" numeric(10,7) NULL,
    "AccuracyMeters" numeric(10,2) NULL,
    "DistanceFromLocationMeters" numeric(12,2) NULL,
    "IdempotencyKey" uuid NOT NULL,
    "AddedById" bigint NOT NULL,
    "AddedDateTime" timestamp with time zone NOT NULL,
    CONSTRAINT "CK_EmployeeAttendancePunch_Action" CHECK ("PunchAction" BETWEEN 1 AND 2),
    CONSTRAINT "CK_EmployeeAttendancePunch_Latitude" CHECK ("Latitude" IS NULL OR "Latitude" BETWEEN -90 AND 90),
    CONSTRAINT "CK_EmployeeAttendancePunch_Longitude" CHECK ("Longitude" IS NULL OR "Longitude" BETWEEN -180 AND 180),
    CONSTRAINT "FK_EmployeeAttendancePunch_Tenant" FOREIGN KEY ("TenantId") REFERENCES axionpro."Tenant" ("Id"),
    CONSTRAINT "FK_EmployeeAttendancePunch_Employee" FOREIGN KEY ("EmployeeId") REFERENCES axionpro."Employee" ("Id"),
    CONSTRAINT "FK_EmployeeAttendancePunch_Arrangement" FOREIGN KEY ("EmployeeWorkArrangementId") REFERENCES axionpro."EmployeeWorkArrangement" ("Id"),
    CONSTRAINT "FK_EmployeeAttendancePunch_PolicyVersion" FOREIGN KEY ("PolicyVersionId") REFERENCES axionpro."PolicyVersion" ("Id"),
    CONSTRAINT "FK_EmployeeAttendancePunch_Location" FOREIGN KEY ("TenantLocationId") REFERENCES axionpro."TenantLocation" ("Id"),
    CONSTRAINT "FK_EmployeeAttendancePunch_AttendanceDeviceType" FOREIGN KEY ("AttendanceDeviceTypeId") REFERENCES axionpro."AttendanceDeviceType" ("Id")
);

CREATE UNIQUE INDEX IF NOT EXISTS "UX_EmployeeAttendancePunch_Idempotency"
    ON axionpro."EmployeeAttendancePunch" ("TenantId", "EmployeeId", "IdempotencyKey");
CREATE INDEX IF NOT EXISTS "IX_EmployeeAttendancePunch_DayTimeline"
    ON axionpro."EmployeeAttendancePunch" ("TenantId", "EmployeeId", "WorkDate", "OccurredAtUtc", "Id");

COMMIT;
