-- Generic Policy rule catalogue and UI schema.
-- Idempotent: all seed joins resolve stable codes; no environment-specific IDs are embedded.
BEGIN;

CREATE TABLE IF NOT EXISTS axionpro."PolicyCategoryRuleType"
(
    "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "PolicyCategoryId" integer NOT NULL REFERENCES axionpro."PolicyCategory"("Id") ON DELETE RESTRICT,
    "PolicyRuleTypeId" integer NOT NULL REFERENCES axionpro."PolicyRuleType"("Id") ON DELETE RESTRICT,
    "IsRequired" boolean NOT NULL DEFAULT false,
    "AllowMultiple" boolean NOT NULL DEFAULT false,
    "DisplayOrder" integer NOT NULL,
    "IsActive" boolean NOT NULL DEFAULT true,
    CONSTRAINT "UQ_PolicyCategoryRuleType_Category_Rule" UNIQUE ("PolicyCategoryId", "PolicyRuleTypeId")
);

CREATE TABLE IF NOT EXISTS axionpro."PolicyRuleSettingDefinition"
(
    "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "PolicyRuleTypeId" integer NOT NULL REFERENCES axionpro."PolicyRuleType"("Id") ON DELETE RESTRICT,
    "SettingCode" varchar(80) NOT NULL,
    "DisplayName" varchar(120) NOT NULL,
    "DataTypeCode" varchar(30) NOT NULL,
    "IsRequired" boolean NOT NULL DEFAULT false,
    "DefaultValueJson" jsonb,
    "MinimumValue" numeric,
    "MaximumValue" numeric,
    "RegexPattern" varchar(500),
    "Placeholder" varchar(200),
    "HelpText" varchar(500),
    "DisplayOrder" integer NOT NULL,
    "IsActive" boolean NOT NULL DEFAULT true,
    CONSTRAINT "UQ_PolicyRuleSettingDefinition_Rule_Code" UNIQUE ("PolicyRuleTypeId", "SettingCode"),
    CONSTRAINT "CK_PolicyRuleSettingDefinition_Type" CHECK ("DataTypeCode" IN ('BOOLEAN','INTEGER','DECIMAL','STRING','CODE'))
);

CREATE TABLE IF NOT EXISTS axionpro."PolicyRuleSettingOption"
(
    "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "PolicyRuleSettingDefinitionId" integer NOT NULL REFERENCES axionpro."PolicyRuleSettingDefinition"("Id") ON DELETE CASCADE,
    "OptionCode" varchar(80) NOT NULL,
    "OptionLabel" varchar(120) NOT NULL,
    "ValueJson" jsonb NOT NULL,
    "DisplayOrder" integer NOT NULL,
    "IsActive" boolean NOT NULL DEFAULT true,
    CONSTRAINT "UQ_PolicyRuleSettingOption_Setting_Code" UNIQUE ("PolicyRuleSettingDefinitionId", "OptionCode")
);

CREATE TABLE IF NOT EXISTS axionpro."PolicyRuleSettingDependency"
(
    "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "PolicyRuleSettingDefinitionId" integer NOT NULL REFERENCES axionpro."PolicyRuleSettingDefinition"("Id") ON DELETE CASCADE,
    "DependsOnSettingDefinitionId" integer NOT NULL REFERENCES axionpro."PolicyRuleSettingDefinition"("Id") ON DELETE CASCADE,
    "OperatorCode" varchar(30) NOT NULL,
    "ExpectedValueJson" jsonb NOT NULL,
    "ActionCode" varchar(30) NOT NULL,
    CONSTRAINT "UQ_PolicyRuleSettingDependency" UNIQUE ("PolicyRuleSettingDefinitionId", "DependsOnSettingDefinitionId", "ActionCode"),
    CONSTRAINT "CK_PolicyRuleSettingDependency_Operator" CHECK ("OperatorCode" IN ('EQUALS','NOT_EQUALS')),
    CONSTRAINT "CK_PolicyRuleSettingDependency_Action" CHECK ("ActionCode" IN ('SHOW','REQUIRE','ENABLE'))
);

WITH mapping("CategoryCode", "RuleTypeCode", "DisplayOrder") AS (VALUES
 ('LEAVE','ELIGIBILITY',10),('LEAVE','ENTITLEMENT',20),('LEAVE','ACCRUAL',30),('LEAVE','CARRY_FORWARD',40),('LEAVE','SANDWICH',50),('LEAVE','LIMIT',60),('LEAVE','APPROVAL',70),
 ('ATTENDANCE','LATE_PENALTY',10),('ATTENDANCE','OVERTIME',20),('ATTENDANCE','APPROVAL',30),
 ('WORK_ARRANGEMENT','ELIGIBILITY',10),('WORK_ARRANGEMENT','LIMIT',20),('WORK_ARRANGEMENT','APPROVAL',30),
 ('TRAVEL','ELIGIBILITY',10),('TRAVEL','LIMIT',20),('TRAVEL','REIMBURSEMENT',30),('TRAVEL','APPROVAL',40),
 ('ACCOMMODATION','ELIGIBILITY',10),('ACCOMMODATION','LIMIT',20),('ACCOMMODATION','REIMBURSEMENT',30),('ACCOMMODATION','APPROVAL',40),
 ('INSURANCE','ELIGIBILITY',10),('INSURANCE','ENTITLEMENT',20),('INSURANCE','LIMIT',30),
 ('EXPENSE','LIMIT',10),('EXPENSE','REIMBURSEMENT',20),('EXPENSE','APPROVAL',30),
 ('HOLIDAY','CALENDAR',10),('HOLIDAY','LIMIT',20),
 ('SHIFT','CALENDAR',10),('SHIFT','OVERTIME',20),('SHIFT','APPROVAL',30),
 ('EMPLOYMENT','ELIGIBILITY',10),('EMPLOYMENT','LIMIT',20),('EMPLOYMENT','APPROVAL',30),
 ('BENEFIT','ELIGIBILITY',10),('BENEFIT','ENTITLEMENT',20),('BENEFIT','LIMIT',30),
 ('CUSTOM','CUSTOM',10)
)
INSERT INTO axionpro."PolicyCategoryRuleType" ("PolicyCategoryId","PolicyRuleTypeId","IsRequired","AllowMultiple","DisplayOrder","IsActive")
SELECT category."Id", rule_type."Id", false, false, mapping."DisplayOrder", true
FROM mapping
JOIN axionpro."PolicyCategory" category ON category."CategoryCode" = mapping."CategoryCode"
JOIN axionpro."PolicyRuleType" rule_type ON rule_type."RuleTypeCode" = mapping."RuleTypeCode"
ON CONFLICT ("PolicyCategoryId","PolicyRuleTypeId") DO UPDATE
SET "DisplayOrder"=EXCLUDED."DisplayOrder", "IsActive"=true;

WITH setting("RuleTypeCode","SettingCode","DisplayName","DataTypeCode","IsRequired","DefaultValueJson","MinimumValue","MaximumValue","DisplayOrder","HelpText") AS (VALUES
 ('ELIGIBILITY','minimumServiceDays','Minimum service days','INTEGER',false,'0'::jsonb,0,NULL,10,'Minimum completed service before eligibility.'),
 ('ENTITLEMENT','quantity','Entitlement quantity','DECIMAL',true,NULL,0,NULL,10,'Quantity granted in the selected unit.'),
 ('ENTITLEMENT','unit','Unit','CODE',true,'"DAY"'::jsonb,NULL,NULL,20,'Stable unit code.'),
 ('ACCRUAL','frequency','Accrual frequency','CODE',true,'"MONTHLY"'::jsonb,NULL,NULL,10,'How often entitlement is credited.'),
 ('ACCRUAL','amountPerCycle','Amount per cycle','DECIMAL',true,NULL,0,NULL,20,'Amount credited each cycle.'),
 ('ACCRUAL','prorateNewJoiner','Prorate new joiner','BOOLEAN',true,'true'::jsonb,NULL,NULL,30,'Prorate the first cycle for joiners.'),
 ('CARRY_FORWARD','enabled','Enable carry forward','BOOLEAN',true,'false'::jsonb,NULL,NULL,10,'Whether unused balance carries forward.'),
 ('CARRY_FORWARD','maximumQuantity','Maximum carry-forward quantity','DECIMAL',false,NULL,0,NULL,20,'Maximum quantity that may carry forward.'),
 ('CARRY_FORWARD','expiryMonths','Expiry months','INTEGER',false,NULL,1,120,30,'Months after which carried balance expires.'),
 ('SANDWICH','enabled','Enable sandwich rule','BOOLEAN',true,'false'::jsonb,NULL,NULL,10,'Include intervening non-working days when conditions match.'),
 ('SANDWICH','includeWeeklyOff','Include weekly off','BOOLEAN',true,'true'::jsonb,NULL,NULL,20,'Count intervening weekly off.'),
 ('SANDWICH','includePublicHoliday','Include public holiday','BOOLEAN',true,'true'::jsonb,NULL,NULL,30,'Count intervening public holidays.'),
 ('LIMIT','minimum','Minimum allowed','DECIMAL',false,NULL,0,NULL,10,'Minimum value per request.'),
 ('LIMIT','maximum','Maximum allowed','DECIMAL',false,NULL,0,NULL,20,'Maximum value per request.'),
 ('LIMIT','negativeAllowed','Allow negative balance','BOOLEAN',true,'false'::jsonb,NULL,NULL,30,'Whether the result may become negative.'),
 ('LATE_PENALTY','graceMinutes','Grace minutes','INTEGER',true,'0'::jsonb,0,1440,10,'Allowed delay before penalty.'),
 ('LATE_PENALTY','occurrences','Occurrences before penalty','INTEGER',true,'1'::jsonb,1,NULL,20,'Number of late events before penalty.'),
 ('OVERTIME','minimumMinutes','Minimum overtime minutes','INTEGER',true,'0'::jsonb,0,NULL,10,'Minimum duration qualifying as overtime.'),
 ('OVERTIME','multiplier','Overtime multiplier','DECIMAL',true,'1'::jsonb,0,NULL,20,'Multiplier applied by the consuming module.'),
 ('APPROVAL','levels','Approval levels','INTEGER',true,'1'::jsonb,1,20,10,'Number of approval levels.'),
 ('APPROVAL','managerRequired','Manager approval required','BOOLEAN',true,'true'::jsonb,NULL,NULL,20,'Whether manager approval is required.'),
 ('REIMBURSEMENT','currencyCode','Currency code','CODE',true,NULL,NULL,NULL,10,'ISO 4217 currency code.'),
 ('REIMBURSEMENT','maximumAmount','Maximum amount','DECIMAL',true,NULL,0,NULL,20,'Maximum reimbursable amount.'),
 ('REIMBURSEMENT','evidenceRequired','Evidence required','BOOLEAN',true,'true'::jsonb,NULL,NULL,30,'Whether supporting evidence is mandatory.'),
 ('CALENDAR','calendarCode','Calendar code','CODE',true,NULL,NULL,NULL,10,'Stable calendar code used by the module adapter.'),
 ('CUSTOM','configurationCode','Configuration code','CODE',true,NULL,NULL,NULL,10,'Stable tenant-defined configuration code.'),
 ('CUSTOM','value','Value','STRING',true,NULL,NULL,NULL,20,'Tenant-defined value consumed by a registered adapter.')
)
INSERT INTO axionpro."PolicyRuleSettingDefinition"
 ("PolicyRuleTypeId","SettingCode","DisplayName","DataTypeCode","IsRequired","DefaultValueJson","MinimumValue","MaximumValue","DisplayOrder","HelpText","IsActive")
SELECT rule_type."Id", setting."SettingCode", setting."DisplayName", setting."DataTypeCode", setting."IsRequired", setting."DefaultValueJson", setting."MinimumValue", setting."MaximumValue", setting."DisplayOrder", setting."HelpText", true
FROM setting JOIN axionpro."PolicyRuleType" rule_type ON rule_type."RuleTypeCode"=setting."RuleTypeCode"
ON CONFLICT ("PolicyRuleTypeId","SettingCode") DO UPDATE SET
 "DisplayName"=EXCLUDED."DisplayName", "DataTypeCode"=EXCLUDED."DataTypeCode", "IsRequired"=EXCLUDED."IsRequired",
 "DefaultValueJson"=EXCLUDED."DefaultValueJson", "MinimumValue"=EXCLUDED."MinimumValue", "MaximumValue"=EXCLUDED."MaximumValue",
 "DisplayOrder"=EXCLUDED."DisplayOrder", "HelpText"=EXCLUDED."HelpText", "IsActive"=true;

WITH option_seed("RuleTypeCode","SettingCode","OptionCode","OptionLabel","ValueJson","DisplayOrder") AS (VALUES
 ('ENTITLEMENT','unit','DAY','Day','"DAY"'::jsonb,10),('ENTITLEMENT','unit','HOUR','Hour','"HOUR"'::jsonb,20),('ENTITLEMENT','unit','AMOUNT','Amount','"AMOUNT"'::jsonb,30),
 ('ACCRUAL','frequency','MONTHLY','Monthly','"MONTHLY"'::jsonb,10),('ACCRUAL','frequency','QUARTERLY','Quarterly','"QUARTERLY"'::jsonb,20),('ACCRUAL','frequency','YEARLY','Yearly','"YEARLY"'::jsonb,30)
)
INSERT INTO axionpro."PolicyRuleSettingOption" ("PolicyRuleSettingDefinitionId","OptionCode","OptionLabel","ValueJson","DisplayOrder","IsActive")
SELECT definition."Id", option_seed."OptionCode", option_seed."OptionLabel", option_seed."ValueJson", option_seed."DisplayOrder", true
FROM option_seed
JOIN axionpro."PolicyRuleType" rule_type ON rule_type."RuleTypeCode"=option_seed."RuleTypeCode"
JOIN axionpro."PolicyRuleSettingDefinition" definition ON definition."PolicyRuleTypeId"=rule_type."Id" AND definition."SettingCode"=option_seed."SettingCode"
ON CONFLICT ("PolicyRuleSettingDefinitionId","OptionCode") DO UPDATE SET "OptionLabel"=EXCLUDED."OptionLabel", "ValueJson"=EXCLUDED."ValueJson", "DisplayOrder"=EXCLUDED."DisplayOrder", "IsActive"=true;

WITH dependency_seed("RuleTypeCode","SettingCode","DependsOnCode","ActionCode") AS (VALUES
 ('CARRY_FORWARD','maximumQuantity','enabled','SHOW'),('CARRY_FORWARD','maximumQuantity','enabled','REQUIRE'),
 ('CARRY_FORWARD','expiryMonths','enabled','SHOW'),('SANDWICH','includeWeeklyOff','enabled','SHOW'),('SANDWICH','includePublicHoliday','enabled','SHOW')
)
INSERT INTO axionpro."PolicyRuleSettingDependency" ("PolicyRuleSettingDefinitionId","DependsOnSettingDefinitionId","OperatorCode","ExpectedValueJson","ActionCode")
SELECT target."Id", parent."Id", 'EQUALS', 'true'::jsonb, dependency_seed."ActionCode"
FROM dependency_seed
JOIN axionpro."PolicyRuleType" rule_type ON rule_type."RuleTypeCode"=dependency_seed."RuleTypeCode"
JOIN axionpro."PolicyRuleSettingDefinition" target ON target."PolicyRuleTypeId"=rule_type."Id" AND target."SettingCode"=dependency_seed."SettingCode"
JOIN axionpro."PolicyRuleSettingDefinition" parent ON parent."PolicyRuleTypeId"=rule_type."Id" AND parent."SettingCode"=dependency_seed."DependsOnCode"
ON CONFLICT ("PolicyRuleSettingDefinitionId","DependsOnSettingDefinitionId","ActionCode") DO UPDATE SET "ExpectedValueJson"=EXCLUDED."ExpectedValueJson";

COMMIT;
