BEGIN;

CREATE TABLE IF NOT EXISTS axionpro."PolicyVersionLeaveType" (
    "Id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "TenantId" bigint NOT NULL,
    "PolicyVersionId" bigint NOT NULL REFERENCES axionpro."PolicyVersion"("Id") ON DELETE CASCADE,
    "LeaveTypeId" integer NOT NULL REFERENCES axionpro."LeaveType"("Id") ON DELETE RESTRICT,
    "IsActive" boolean NOT NULL DEFAULT true,
    "AddedById" bigint NOT NULL,
    "AddedDateTime" timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT "UQ_PolicyVersionLeaveType_Version_LeaveType" UNIQUE ("PolicyVersionId", "LeaveTypeId")
);

CREATE TABLE IF NOT EXISTS axionpro."PolicyRuleLeaveType" (
    "Id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "TenantId" bigint NOT NULL,
    "PolicyRuleId" bigint NOT NULL REFERENCES axionpro."PolicyRule"("Id") ON DELETE CASCADE,
    "LeaveTypeId" integer NOT NULL REFERENCES axionpro."LeaveType"("Id") ON DELETE RESTRICT,
    CONSTRAINT "UQ_PolicyRuleLeaveType_Rule_LeaveType" UNIQUE ("PolicyRuleId", "LeaveTypeId")
);

CREATE TABLE IF NOT EXISTS axionpro."PolicyApplicabilityLeaveType" (
    "Id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "TenantId" bigint NOT NULL,
    "PolicyApplicabilityId" bigint NOT NULL REFERENCES axionpro."PolicyApplicability"("Id") ON DELETE CASCADE,
    "LeaveTypeId" integer NOT NULL REFERENCES axionpro."LeaveType"("Id") ON DELETE RESTRICT,
    CONSTRAINT "UQ_PolicyApplicabilityLeaveType_Scope_LeaveType" UNIQUE ("PolicyApplicabilityId", "LeaveTypeId")
);

CREATE INDEX IF NOT EXISTS "IX_PolicyVersionLeaveType_Tenant_LeaveType"
    ON axionpro."PolicyVersionLeaveType" ("TenantId", "LeaveTypeId");
CREATE INDEX IF NOT EXISTS "IX_PolicyRuleLeaveType_Tenant_LeaveType"
    ON axionpro."PolicyRuleLeaveType" ("TenantId", "LeaveTypeId");
CREATE INDEX IF NOT EXISTS "IX_PolicyApplicabilityLeaveType_Tenant_LeaveType"
    ON axionpro."PolicyApplicabilityLeaveType" ("TenantId", "LeaveTypeId");

INSERT INTO axionpro."LeaveType"
    ("TenantId", "LeaveName", "Description", "IsActive", "AddedById", "AddedDateTime", "IsSoftDeleted")
SELECT tenant."Id", seed."LeaveName", seed."Description", true, admin."EmployeeId", CURRENT_TIMESTAMP, false
FROM axionpro."Tenant" tenant
CROSS JOIN (VALUES
    ('Casual Leave', 'Short personal leave; normally lapses at the end of the policy year.'),
    ('Earned Leave', 'Service-earned leave that can accrue periodically and may carry forward.'),
    ('Sick Leave', 'Health-related leave governed by eligibility and evidence rules.'),
    ('Maternity Leave', 'Statutory maternity leave governed by employee eligibility.'),
    ('Paternity Leave', 'Paternity leave governed by employee eligibility.')
) AS seed("LeaveName", "Description")
CROSS JOIN LATERAL (
    SELECT employee."Id" AS "EmployeeId"
    FROM axionpro."Employee" employee
    WHERE employee."TenantId" = tenant."Id"
    ORDER BY employee."Id"
    LIMIT 1
) admin
WHERE tenant."IsActive" = true
  AND NOT EXISTS (
      SELECT 1 FROM axionpro."LeaveType" existing
      WHERE existing."TenantId" = tenant."Id"
        AND lower(existing."LeaveName") = lower(seed."LeaveName")
        AND existing."IsSoftDeleted" IS NOT TRUE
  );

COMMIT;
