-- Secure initial device provisioning and protected command payload support.
-- Run once against AxionPro PostgreSQL BEFORE deploying the matching API build.
-- This migration is additive and does not alter an existing device connection.

BEGIN;

ALTER TABLE axionpro."DeviceCommand"
    ADD COLUMN IF NOT EXISTS "IsSensitivePayload" boolean NOT NULL DEFAULT false;

ALTER TABLE axionpro."DeviceCredential"
    DROP CONSTRAINT IF EXISTS "CK_DeviceCredential_Type";

ALTER TABLE axionpro."DeviceCredential"
    ADD CONSTRAINT "CK_DeviceCredential_Type"
    CHECK ("CredentialType" IN (1, 2, 3, 4));

CREATE TABLE IF NOT EXISTS axionpro."DeviceInitialProvisioning"
(
    "Id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "DeviceMasterId" bigint NOT NULL,
    "IngressTokenHash" character varying(64) NOT NULL,
    "HeartbeatIntervalSeconds" integer NOT NULL DEFAULT 20,
    "ExpiresDateTime" timestamp with time zone NOT NULL,
    "FirstConnectedDateTime" timestamp with time zone NULL,
    "LastConnectedDateTime" timestamp with time zone NULL,
    "RevokedDateTime" timestamp with time zone NULL,
    "IssuedById" bigint NOT NULL,
    "IssuedDateTime" timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "RevokedById" bigint NULL,
    CONSTRAINT "CK_DeviceInitialProvisioning_Heartbeat"
        CHECK ("HeartbeatIntervalSeconds" BETWEEN 10 AND 3600),
    CONSTRAINT "CK_DeviceInitialProvisioning_ExpiresAfterIssue"
        CHECK ("ExpiresDateTime" > "IssuedDateTime"),
    CONSTRAINT "CK_DeviceInitialProvisioning_TokenHash"
        CHECK ("IngressTokenHash" ~ '^[0-9a-f]{64}$'),
    CONSTRAINT "FK_DeviceInitialProvisioning_DeviceMaster"
        FOREIGN KEY ("DeviceMasterId") REFERENCES axionpro."DeviceMaster" ("Id") ON DELETE RESTRICT
);

CREATE UNIQUE INDEX IF NOT EXISTS "UX_DeviceInitialProvisioning_IngressTokenHash"
    ON axionpro."DeviceInitialProvisioning" ("IngressTokenHash");

CREATE INDEX IF NOT EXISTS "IX_DeviceInitialProvisioning_DeviceMaster_Active"
    ON axionpro."DeviceInitialProvisioning" ("DeviceMasterId", "RevokedDateTime", "ExpiresDateTime");

COMMIT;
