BEGIN;

CREATE TABLE IF NOT EXISTS axionpro."PaymentGateway" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "GatewayCode" varchar(30) NOT NULL,
    "GatewayName" varchar(100) NOT NULL,
    "Environment" varchar(20) NOT NULL DEFAULT 'Sandbox',
    "ClientIdEnvironmentVariable" varchar(100) NOT NULL,
    "ClientSecretEnvironmentVariable" varchar(100) NOT NULL,
    "WebhookSecretEnvironmentVariable" varchar(100) NOT NULL,
    "BaseUrl" varchar(500) NOT NULL,
    "IsActive" boolean NOT NULL DEFAULT TRUE,
    "AddedDateTime" timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "UpdatedDateTime" timestamptz NULL,
    CONSTRAINT "UQ_PaymentGateway_Code" UNIQUE ("GatewayCode"),
    CONSTRAINT "CK_PaymentGateway_Environment" CHECK ("Environment" IN ('Sandbox','Production'))
);

CREATE TABLE IF NOT EXISTS axionpro."HostBillingConfiguration" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "PaymentGatewayId" integer NOT NULL REFERENCES axionpro."PaymentGateway"("Id") ON DELETE RESTRICT,
    "SellerLegalName" varchar(200) NULL,
    "SellerBillingEmail" varchar(250) NULL,
    "SellerBillingPhone" varchar(30) NULL,
    "CountryCode" char(2) NOT NULL DEFAULT 'IN',
    "StateCode" varchar(20) NULL,
    "PostalCode" varchar(20) NULL,
    "AddressLine1" varchar(300) NULL,
    "AddressLine2" varchar(300) NULL,
    "TaxRegistrationNumber" varchar(50) NULL,
    "InvoicePrefix" varchar(20) NOT NULL DEFAULT 'AXP',
    "PaymentRetryCount" integer NOT NULL DEFAULT 3,
    "GracePeriodDays" integer NOT NULL DEFAULT 1,
    "PaymentTimeoutMinutes" integer NOT NULL DEFAULT 30,
    "ReconciliationLookbackDays" integer NOT NULL DEFAULT 7,
    "IsActive" boolean NOT NULL DEFAULT FALSE,
    "AddedByHostUserId" bigint NULL,
    "AddedDateTime" timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "UpdatedByHostUserId" bigint NULL,
    "UpdatedDateTime" timestamptz NULL,
    "Version" integer NOT NULL DEFAULT 1,
    CONSTRAINT "CK_HostBillingConfiguration_Retry" CHECK ("PaymentRetryCount" BETWEEN 1 AND 10),
    CONSTRAINT "CK_HostBillingConfiguration_Grace" CHECK ("GracePeriodDays" BETWEEN 0 AND 30),
    CONSTRAINT "CK_HostBillingConfiguration_Timeout" CHECK ("PaymentTimeoutMinutes" BETWEEN 5 AND 1440),
    CONSTRAINT "CK_HostBillingConfiguration_Lookback" CHECK ("ReconciliationLookbackDays" BETWEEN 1 AND 90)
);
CREATE UNIQUE INDEX IF NOT EXISTS "UX_HostBillingConfiguration_Active"
ON axionpro."HostBillingConfiguration" ((TRUE)) WHERE "IsActive" = TRUE;

CREATE TABLE IF NOT EXISTS axionpro."SubscriptionPlanPrice" (
    "Id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "SubscriptionPlanId" integer NOT NULL REFERENCES axionpro."SubscriptionPlan"("Id") ON DELETE RESTRICT,
    "CountryCode" char(2) NOT NULL,
    "CurrencyCode" char(3) NOT NULL,
    "BillingCycle" varchar(10) NOT NULL,
    "BaseAmount" numeric(18,2) NOT NULL,
    "EffectiveFrom" date NOT NULL,
    "EffectiveTo" date NULL,
    "IsActive" boolean NOT NULL DEFAULT TRUE,
    "AddedByHostUserId" bigint NULL,
    "AddedDateTime" timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "UpdatedByHostUserId" bigint NULL,
    "UpdatedDateTime" timestamptz NULL,
    CONSTRAINT "CK_SubscriptionPlanPrice_Cycle" CHECK ("BillingCycle" IN ('Monthly','Yearly')),
    CONSTRAINT "CK_SubscriptionPlanPrice_Amount" CHECK ("BaseAmount" >= 0),
    CONSTRAINT "CK_SubscriptionPlanPrice_Dates" CHECK ("EffectiveTo" IS NULL OR "EffectiveTo" >= "EffectiveFrom")
);
CREATE UNIQUE INDEX IF NOT EXISTS "UX_SubscriptionPlanPrice_Live"
ON axionpro."SubscriptionPlanPrice" ("SubscriptionPlanId", "CountryCode", "CurrencyCode", "BillingCycle", "EffectiveFrom")
WHERE "IsActive" = TRUE;

CREATE TABLE IF NOT EXISTS axionpro."BillingTaxRule" (
    "Id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "CountryCode" char(2) NOT NULL,
    "TaxCode" varchar(30) NOT NULL,
    "TaxName" varchar(100) NOT NULL,
    "RatePercent" numeric(7,4) NOT NULL,
    "EffectiveFrom" date NOT NULL,
    "EffectiveTo" date NULL,
    "IsActive" boolean NOT NULL DEFAULT TRUE,
    "ConfigurationJson" jsonb NULL,
    "AddedByHostUserId" bigint NULL,
    "AddedDateTime" timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "UpdatedByHostUserId" bigint NULL,
    "UpdatedDateTime" timestamptz NULL,
    CONSTRAINT "CK_BillingTaxRule_Rate" CHECK ("RatePercent" >= 0 AND "RatePercent" <= 100),
    CONSTRAINT "CK_BillingTaxRule_Dates" CHECK ("EffectiveTo" IS NULL OR "EffectiveTo" >= "EffectiveFrom")
);
CREATE UNIQUE INDEX IF NOT EXISTS "UX_BillingTaxRule_Live"
ON axionpro."BillingTaxRule" ("CountryCode", "TaxCode", "EffectiveFrom") WHERE "IsActive" = TRUE;

ALTER TABLE axionpro."SubscriptionPlanPrice"
    ADD COLUMN IF NOT EXISTS "AddedByHostUserId" bigint NULL,
    ADD COLUMN IF NOT EXISTS "UpdatedByHostUserId" bigint NULL;
ALTER TABLE axionpro."BillingTaxRule"
    ADD COLUMN IF NOT EXISTS "AddedByHostUserId" bigint NULL,
    ADD COLUMN IF NOT EXISTS "UpdatedByHostUserId" bigint NULL,
    ADD COLUMN IF NOT EXISTS "UpdatedDateTime" timestamptz NULL;

CREATE TABLE IF NOT EXISTS axionpro."TenantBillingProfile" (
    "Id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "TenantId" bigint NOT NULL REFERENCES axionpro."Tenant"("Id") ON DELETE RESTRICT,
    "LegalName" varchar(200) NOT NULL,
    "BillingEmail" varchar(250) NOT NULL,
    "BillingPhone" varchar(30) NULL,
    "CountryCode" char(2) NOT NULL,
    "StateCode" varchar(20) NULL,
    "PostalCode" varchar(20) NULL,
    "AddressLine1" varchar(300) NOT NULL,
    "AddressLine2" varchar(300) NULL,
    "TaxRegistrationNumber" varchar(50) NULL,
    "DefaultCurrencyCode" char(3) NOT NULL,
    "GatewayCustomerId" varchar(100) NULL,
    "IsActive" boolean NOT NULL DEFAULT TRUE,
    "AddedDateTime" timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "UpdatedDateTime" timestamptz NULL
);
CREATE UNIQUE INDEX IF NOT EXISTS "UX_TenantBillingProfile_Active"
ON axionpro."TenantBillingProfile" ("TenantId") WHERE "IsActive" = TRUE;

CREATE TABLE IF NOT EXISTS axionpro."TenantBillingSubscription" (
    "Id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "TenantId" bigint NOT NULL REFERENCES axionpro."Tenant"("Id") ON DELETE RESTRICT,
    "TenantSubscriptionId" bigint NULL REFERENCES axionpro."TenantSubscription"("Id") ON DELETE RESTRICT,
    "SubscriptionPlanPriceId" bigint NOT NULL REFERENCES axionpro."SubscriptionPlanPrice"("Id") ON DELETE RESTRICT,
    "PaymentGatewayId" integer NOT NULL REFERENCES axionpro."PaymentGateway"("Id") ON DELETE RESTRICT,
    "GatewaySubscriptionId" varchar(100) NULL,
    "GatewayMandateId" varchar(100) NULL,
    "BillingCycle" varchar(10) NOT NULL,
    "Status" varchar(30) NOT NULL,
    "CurrentPeriodStart" timestamptz NULL,
    "CurrentPeriodEnd" timestamptz NULL,
    "GraceEndsAt" timestamptz NULL,
    "CancelAtPeriodEnd" boolean NOT NULL DEFAULT FALSE,
    "CancelledAt" timestamptz NULL,
    "Version" integer NOT NULL DEFAULT 1,
    "AddedDateTime" timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "UpdatedDateTime" timestamptz NULL,
    CONSTRAINT "CK_TenantBillingSubscription_Cycle" CHECK ("BillingCycle" IN ('Monthly','Yearly')),
    CONSTRAINT "CK_TenantBillingSubscription_Status" CHECK ("Status" IN ('PendingAuthorization','Active','PastDue','GracePeriod','Cancelled','Expired','Suspended'))
);
CREATE UNIQUE INDEX IF NOT EXISTS "UX_TenantBillingSubscription_Current"
ON axionpro."TenantBillingSubscription" ("TenantId")
WHERE "Status" IN ('PendingAuthorization','Active','PastDue','GracePeriod');
CREATE UNIQUE INDEX IF NOT EXISTS "UX_TenantBillingSubscription_Gateway"
ON axionpro."TenantBillingSubscription" ("PaymentGatewayId", "GatewaySubscriptionId")
WHERE "GatewaySubscriptionId" IS NOT NULL;

CREATE TABLE IF NOT EXISTS axionpro."BillingOrder" (
    "Id" uuid PRIMARY KEY,
    "TenantId" bigint NOT NULL REFERENCES axionpro."Tenant"("Id") ON DELETE RESTRICT,
    "TenantBillingSubscriptionId" bigint NULL REFERENCES axionpro."TenantBillingSubscription"("Id") ON DELETE RESTRICT,
    "SubscriptionPlanPriceId" bigint NOT NULL REFERENCES axionpro."SubscriptionPlanPrice"("Id") ON DELETE RESTRICT,
    "PaymentGatewayId" integer NOT NULL REFERENCES axionpro."PaymentGateway"("Id") ON DELETE RESTRICT,
    "GatewayOrderId" varchar(100) NULL,
    "IdempotencyKey" uuid NOT NULL,
    "OrderType" varchar(20) NOT NULL,
    "Status" varchar(20) NOT NULL,
    "CurrencyCode" char(3) NOT NULL,
    "SubtotalAmount" numeric(18,2) NOT NULL,
    "DiscountAmount" numeric(18,2) NOT NULL DEFAULT 0,
    "TaxAmount" numeric(18,2) NOT NULL DEFAULT 0,
    "TotalAmount" numeric(18,2) NOT NULL,
    "ExpiresAt" timestamptz NOT NULL,
    "AddedById" bigint NOT NULL,
    "AddedDateTime" timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "UpdatedDateTime" timestamptz NULL,
    CONSTRAINT "UQ_BillingOrder_Idempotency" UNIQUE ("IdempotencyKey"),
    CONSTRAINT "CK_BillingOrder_Type" CHECK ("OrderType" IN ('New','Renewal','Upgrade','Adjustment')),
    CONSTRAINT "CK_BillingOrder_Status" CHECK ("Status" IN ('Created','Pending','Paid','Failed','Expired','Cancelled','Refunded','PartiallyRefunded')),
    CONSTRAINT "CK_BillingOrder_Amounts" CHECK ("SubtotalAmount" >= 0 AND "DiscountAmount" >= 0 AND "TaxAmount" >= 0 AND "TotalAmount" >= 0)
);
CREATE UNIQUE INDEX IF NOT EXISTS "UX_BillingOrder_GatewayOrder"
ON axionpro."BillingOrder" ("PaymentGatewayId", "GatewayOrderId") WHERE "GatewayOrderId" IS NOT NULL;

CREATE TABLE IF NOT EXISTS axionpro."PaymentTransaction" (
    "Id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "BillingOrderId" uuid NOT NULL REFERENCES axionpro."BillingOrder"("Id") ON DELETE RESTRICT,
    "GatewayPaymentId" varchar(100) NULL,
    "Status" varchar(20) NOT NULL,
    "PaymentMethod" varchar(50) NULL,
    "CurrencyCode" char(3) NOT NULL,
    "Amount" numeric(18,2) NOT NULL,
    "GatewayFeeAmount" numeric(18,2) NULL,
    "GatewayTaxAmount" numeric(18,2) NULL,
    "BankReference" varchar(150) NULL,
    "FailureCode" varchar(100) NULL,
    "FailureMessage" varchar(1000) NULL,
    "PaidAt" timestamptz NULL,
    "AddedDateTime" timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "UpdatedDateTime" timestamptz NULL,
    CONSTRAINT "CK_PaymentTransaction_Status" CHECK ("Status" IN ('Pending','Succeeded','Failed','UserDropped','Reversed','Refunded','PartiallyRefunded')),
    CONSTRAINT "CK_PaymentTransaction_Amount" CHECK ("Amount" >= 0)
);
CREATE UNIQUE INDEX IF NOT EXISTS "UX_PaymentTransaction_GatewayPayment"
ON axionpro."PaymentTransaction" ("GatewayPaymentId") WHERE "GatewayPaymentId" IS NOT NULL;

CREATE TABLE IF NOT EXISTS axionpro."PaymentAttempt" (
    "Id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "BillingOrderId" uuid NOT NULL REFERENCES axionpro."BillingOrder"("Id") ON DELETE RESTRICT,
    "AttemptNumber" integer NOT NULL,
    "Status" varchar(20) NOT NULL,
    "RequestedAt" timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "CompletedAt" timestamptz NULL,
    "NextRetryAt" timestamptz NULL,
    "FailureCode" varchar(100) NULL,
    "FailureMessage" varchar(1000) NULL,
    CONSTRAINT "UQ_PaymentAttempt_Number" UNIQUE ("BillingOrderId", "AttemptNumber"),
    CONSTRAINT "CK_PaymentAttempt_Number" CHECK ("AttemptNumber" > 0)
);

CREATE TABLE IF NOT EXISTS axionpro."PaymentWebhookEvent" (
    "Id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "PaymentGatewayId" integer NOT NULL REFERENCES axionpro."PaymentGateway"("Id") ON DELETE RESTRICT,
    "GatewayEventId" varchar(150) NOT NULL,
    "EventType" varchar(100) NOT NULL,
    "Signature" varchar(500) NULL,
    "PayloadJson" jsonb NOT NULL,
    "SignatureVerified" boolean NOT NULL DEFAULT FALSE,
    "ProcessingStatus" varchar(20) NOT NULL DEFAULT 'Pending',
    "RetryCount" integer NOT NULL DEFAULT 0,
    "ReceivedAt" timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "ProcessedAt" timestamptz NULL,
    "ErrorMessage" varchar(2000) NULL,
    CONSTRAINT "UQ_PaymentWebhookEvent_GatewayEvent" UNIQUE ("PaymentGatewayId", "GatewayEventId"),
    CONSTRAINT "CK_PaymentWebhookEvent_Status" CHECK ("ProcessingStatus" IN ('Pending','Processed','Ignored','Failed'))
);

CREATE TABLE IF NOT EXISTS axionpro."BillingInvoice" (
    "Id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "InvoiceNumber" varchar(50) NOT NULL,
    "TenantId" bigint NOT NULL REFERENCES axionpro."Tenant"("Id") ON DELETE RESTRICT,
    "BillingOrderId" uuid NOT NULL REFERENCES axionpro."BillingOrder"("Id") ON DELETE RESTRICT,
    "InvoiceDate" date NOT NULL,
    "DueDate" date NOT NULL,
    "CountryCode" char(2) NOT NULL,
    "CurrencyCode" char(3) NOT NULL,
    "SellerTaxRegistrationNumber" varchar(50) NULL,
    "BuyerTaxRegistrationNumber" varchar(50) NULL,
    "PlaceOfSupplyCode" varchar(20) NULL,
    "SubtotalAmount" numeric(18,2) NOT NULL,
    "TaxAmount" numeric(18,2) NOT NULL,
    "TotalAmount" numeric(18,2) NOT NULL,
    "Status" varchar(20) NOT NULL,
    "IssuedAt" timestamptz NULL,
    "PaidAt" timestamptz NULL,
    "DocumentPath" varchar(1000) NULL,
    "AddedDateTime" timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT "UQ_BillingInvoice_Number" UNIQUE ("InvoiceNumber"),
    CONSTRAINT "UQ_BillingInvoice_Order" UNIQUE ("BillingOrderId"),
    CONSTRAINT "CK_BillingInvoice_Status" CHECK ("Status" IN ('Draft','Issued','Paid','PartiallyRefunded','Refunded','Void'))
);

CREATE TABLE IF NOT EXISTS axionpro."BillingInvoiceLine" (
    "Id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "BillingInvoiceId" bigint NOT NULL REFERENCES axionpro."BillingInvoice"("Id") ON DELETE RESTRICT,
    "Description" varchar(500) NOT NULL,
    "Quantity" numeric(18,4) NOT NULL,
    "UnitPrice" numeric(18,2) NOT NULL,
    "TaxCode" varchar(30) NULL,
    "TaxRatePercent" numeric(7,4) NOT NULL DEFAULT 0,
    "TaxAmount" numeric(18,2) NOT NULL DEFAULT 0,
    "LineTotal" numeric(18,2) NOT NULL,
    CONSTRAINT "CK_BillingInvoiceLine_Values" CHECK ("Quantity" > 0 AND "UnitPrice" >= 0 AND "TaxAmount" >= 0 AND "LineTotal" >= 0)
);

CREATE TABLE IF NOT EXISTS axionpro."BillingRefund" (
    "Id" uuid PRIMARY KEY,
    "PaymentTransactionId" bigint NOT NULL REFERENCES axionpro."PaymentTransaction"("Id") ON DELETE RESTRICT,
    "GatewayRefundId" varchar(100) NULL,
    "IdempotencyKey" uuid NOT NULL,
    "Amount" numeric(18,2) NOT NULL,
    "CurrencyCode" char(3) NOT NULL,
    "Reason" varchar(500) NOT NULL,
    "Status" varchar(20) NOT NULL,
    "RequestedByHostUserId" bigint NOT NULL,
    "RequestedAt" timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "CompletedAt" timestamptz NULL,
    "FailureMessage" varchar(1000) NULL,
    CONSTRAINT "UQ_BillingRefund_Idempotency" UNIQUE ("IdempotencyKey"),
    CONSTRAINT "CK_BillingRefund_Amount" CHECK ("Amount" > 0),
    CONSTRAINT "CK_BillingRefund_Status" CHECK ("Status" IN ('Requested','Processing','Succeeded','Failed','Cancelled'))
);
CREATE UNIQUE INDEX IF NOT EXISTS "UX_BillingRefund_GatewayRefund"
ON axionpro."BillingRefund" ("GatewayRefundId") WHERE "GatewayRefundId" IS NOT NULL;

CREATE TABLE IF NOT EXISTS axionpro."BillingSubscriptionChange" (
    "Id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "TenantBillingSubscriptionId" bigint NOT NULL REFERENCES axionpro."TenantBillingSubscription"("Id") ON DELETE RESTRICT,
    "FromSubscriptionPlanPriceId" bigint NOT NULL REFERENCES axionpro."SubscriptionPlanPrice"("Id") ON DELETE RESTRICT,
    "ToSubscriptionPlanPriceId" bigint NOT NULL REFERENCES axionpro."SubscriptionPlanPrice"("Id") ON DELETE RESTRICT,
    "ChangeType" varchar(20) NOT NULL,
    "EffectiveAt" timestamptz NOT NULL,
    "ProrationAmount" numeric(18,2) NOT NULL DEFAULT 0,
    "Status" varchar(20) NOT NULL,
    "RequestedById" bigint NOT NULL,
    "RequestedAt" timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "AppliedAt" timestamptz NULL,
    CONSTRAINT "CK_BillingSubscriptionChange_Type" CHECK ("ChangeType" IN ('Upgrade','Downgrade')),
    CONSTRAINT "CK_BillingSubscriptionChange_Status" CHECK ("Status" IN ('PendingPayment','Scheduled','Applied','Failed','Cancelled'))
);

CREATE TABLE IF NOT EXISTS axionpro."BillingAuditLog" (
    "Id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "TenantId" bigint NULL,
    "EntityType" varchar(50) NOT NULL,
    "EntityId" varchar(100) NOT NULL,
    "Action" varchar(100) NOT NULL,
    "OldStatus" varchar(50) NULL,
    "NewStatus" varchar(50) NULL,
    "ActorType" varchar(20) NOT NULL,
    "ActorId" bigint NULL,
    "CorrelationId" varchar(100) NULL,
    "MetadataJson" jsonb NULL,
    "AddedDateTime" timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT "CK_BillingAuditLog_Actor" CHECK ("ActorType" IN ('TenantUser','HostUser','Webhook','Worker','System'))
);

INSERT INTO axionpro."PaymentGateway"
("GatewayCode", "GatewayName", "Environment", "ClientIdEnvironmentVariable", "ClientSecretEnvironmentVariable", "WebhookSecretEnvironmentVariable", "BaseUrl", "IsActive")
SELECT 'CASHFREE', 'Cashfree Payments', 'Sandbox', 'CASHFREE_CLIENT_ID', 'CASHFREE_CLIENT_SECRET', 'CASHFREE_WEBHOOK_SECRET', 'https://sandbox.cashfree.com', TRUE
WHERE NOT EXISTS (SELECT 1 FROM axionpro."PaymentGateway" WHERE "GatewayCode" = 'CASHFREE');

INSERT INTO axionpro."HostBillingConfiguration"
("PaymentGatewayId", "CountryCode", "InvoicePrefix", "PaymentRetryCount", "GracePeriodDays", "PaymentTimeoutMinutes", "ReconciliationLookbackDays", "IsActive")
SELECT gateway."Id", 'IN', 'AXP', 3, 1, 30, 7, FALSE
FROM axionpro."PaymentGateway" gateway
WHERE gateway."GatewayCode" = 'CASHFREE'
  AND NOT EXISTS (SELECT 1 FROM axionpro."HostBillingConfiguration");

INSERT INTO axionpro."BillingTaxRule"
("CountryCode", "TaxCode", "TaxName", "RatePercent", "EffectiveFrom", "IsActive", "ConfigurationJson")
SELECT 'IN', 'GST', 'Goods and Services Tax', 18.0000, DATE '2017-07-01', TRUE,
       '{"splitByPlaceOfSupply":true,"intraStateComponents":["CGST","SGST"],"interStateComponents":["IGST"]}'::jsonb
WHERE NOT EXISTS (
    SELECT 1 FROM axionpro."BillingTaxRule"
    WHERE "CountryCode"='IN' AND "TaxCode"='GST' AND "EffectiveFrom"=DATE '2017-07-01');

COMMIT;
