-- ============================================================================
-- AxionPro Production - Consolidated Module and Operation Setup
-- Author      : Deepesh Gupta
-- Company     : Quecksilber Technologies
-- Role        : CEO
--
-- Purpose:
--   1. DefaultEmailConfig table create / upgrade.
--   2. Existing active TenantEmailConfig se default SMTP seed.
--   3. Email modules     : Host default, Host Tenant email, Tenant email,
--                          and Host email templates.
--   4. Device modules    : Host device setup, Tenant device setup, Host initial
--                          provisioning, and Tenant runtime configuration.
--   5. Employee password : Child module, dedicated Reset Password operation,
--                          operation mapping, and inherited plan mappings.
--   6. Existing module / operation records ko normalize/update karna.
--   7. Identity / auto-increment sequence safely synchronize karna.
--
-- IMPORTANT:
--   * SMTP password/secret hard-code nahi kiya gaya hai.
--   * Existing role permissions are never auto-granted.
--   * Existing production IDs ko reset/delete nahi kiya jayega.
--   * Script re-run safe/idempotent rakhi gayi hai.
-- ============================================================================


BEGIN;


-- ============================================================================
-- SECTION 1 : DEFAULT EMAIL CONFIGURATION TABLE
-- ============================================================================

CREATE TABLE IF NOT EXISTS axionpro."DefaultEmailConfig"
(
    "Id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    "ConfigName" CHARACTER VARYING(100) NOT NULL,

    "SmtpHost" CHARACTER VARYING(200) NOT NULL,

    "SmtpPort" INTEGER NOT NULL,

    "SmtpUsername" CHARACTER VARYING(200) NOT NULL,

    "SmtpPasswordEncrypted" CHARACTER VARYING(500) NOT NULL,

    "FromEmail" CHARACTER VARYING(200) NOT NULL,

    "FromName" CHARACTER VARYING(100) NOT NULL,

    "IsActive" BOOLEAN NOT NULL DEFAULT TRUE,

    "IsDefault" BOOLEAN NOT NULL DEFAULT FALSE,

    "SecrateKey" CHARACTER VARYING(500) NOT NULL,

    "CreatedDateTime"
        TIMESTAMP WITHOUT TIME ZONE
        NOT NULL
        DEFAULT CURRENT_TIMESTAMP,

    "UpdatedDateTime"
        TIMESTAMP WITHOUT TIME ZONE NULL
);


-- ============================================================================
-- SECTION 2 : SAFE TABLE UPGRADE
-- ============================================================================

ALTER TABLE axionpro."DefaultEmailConfig"
ADD COLUMN IF NOT EXISTS
    "IsDefault" BOOLEAN NOT NULL DEFAULT FALSE;


-- ============================================================================
-- SECTION 2A : OPERATION AUDIT COLUMN STANDARDISATION
-- ============================================================================
-- The original schema used "UpdateDateTime" only on Operation.  All other
-- audit models use "UpdatedDateTime"; rename the physical column once so the
-- database, EF entity, API DTOs, and seed script share one contract.
DO
$$
DECLARE
    legacy_column_exists BOOLEAN;
    canonical_column_exists BOOLEAN;
BEGIN
    IF to_regclass('axionpro."Operation"') IS NULL THEN
        RAISE EXCEPTION 'Required table axionpro."Operation" does not exist.';
    END IF;

    SELECT EXISTS
    (
        SELECT 1
        FROM information_schema.columns
        WHERE table_schema = 'axionpro'
          AND table_name = 'Operation'
          AND column_name = 'UpdateDateTime'
    )
    INTO legacy_column_exists;

    SELECT EXISTS
    (
        SELECT 1
        FROM information_schema.columns
        WHERE table_schema = 'axionpro'
          AND table_name = 'Operation'
          AND column_name = 'UpdatedDateTime'
    )
    INTO canonical_column_exists;

    IF legacy_column_exists AND canonical_column_exists THEN
        RAISE EXCEPTION
            'axionpro."Operation" contains both "UpdateDateTime" and "UpdatedDateTime". Resolve the duplicate columns before running this script.';
    ELSIF legacy_column_exists THEN
        ALTER TABLE axionpro."Operation"
        RENAME COLUMN "UpdateDateTime" TO "UpdatedDateTime";
    ELSIF NOT canonical_column_exists THEN
        RAISE EXCEPTION
            'Audit column "UpdatedDateTime" is missing from axionpro."Operation".';
    END IF;
END;
$$;


-- ============================================================================
-- SMTP PORT VALIDATION
-- ============================================================================

DO
$$
BEGIN

    IF NOT EXISTS
    (
        SELECT 1
        FROM pg_constraint
        WHERE conname = 'CK_DefaultEmailConfig_SmtpPort'
          AND conrelid = 'axionpro."DefaultEmailConfig"'::regclass
    )
    THEN

        ALTER TABLE axionpro."DefaultEmailConfig"
        ADD CONSTRAINT "CK_DefaultEmailConfig_SmtpPort"
        CHECK ("SmtpPort" BETWEEN 1 AND 65535);

    END IF;

END;
$$;


-- ============================================================================
-- CONFIG NAME UNIQUE CONSTRAINT
-- ============================================================================

DO
$$
BEGIN

    IF NOT EXISTS
    (
        SELECT 1
        FROM pg_constraint
        WHERE conname = 'UX_DefaultEmailConfig_ConfigName'
          AND conrelid = 'axionpro."DefaultEmailConfig"'::regclass
    )
    THEN

        ALTER TABLE axionpro."DefaultEmailConfig"
        ADD CONSTRAINT "UX_DefaultEmailConfig_ConfigName"
        UNIQUE ("ConfigName");

    END IF;

END;
$$;


-- ============================================================================
-- ONLY ONE DEFAULT SMTP CONFIGURATION
-- ============================================================================

DROP INDEX IF EXISTS
axionpro."UX_DefaultEmailConfig_OneActive";


CREATE UNIQUE INDEX IF NOT EXISTS
"UX_DefaultEmailConfig_OneDefault"
ON axionpro."DefaultEmailConfig"
(
    "IsDefault"
)
WHERE "IsDefault" = TRUE;


-- ============================================================================
-- SECTION 3 : SEED DEFAULT EMAIL CONFIGURATION
-- ============================================================================
--
-- Latest complete active TenantEmailConfig configuration ko source banaya jayega.
--
-- Isliye production SQL me:
-- Password
-- Secret
-- SMTP Username
--
-- manually paste nahi karna padega.
-- ============================================================================

DO
$$
BEGIN

    INSERT INTO axionpro."DefaultEmailConfig"
    (
        "ConfigName",
        "SmtpHost",
        "SmtpPort",
        "SmtpUsername",
        "SmtpPasswordEncrypted",
        "FromEmail",
        "FromName",
        "IsActive",
        "IsDefault",
        "SecrateKey"
    )

    SELECT

        'DEFAULT_REGISTRATION_SMTP',

        BTRIM(configuration."SmtpHost"),

        configuration."SmtpPort",

        BTRIM(configuration."SmtpUsername"),

        COALESCE
        (
            NULLIF
            (
                BTRIM(configuration."SmtpPasswordEncrypted"),
                ''
            ),

            NULLIF
            (
                BTRIM(configuration."SecrateKey"),
                ''
            )
        ),

        BTRIM(configuration."FromEmail"),

        BTRIM(configuration."FromName"),

        TRUE,

        NOT EXISTS
        (
            SELECT 1

            FROM axionpro."DefaultEmailConfig"
                existingDefault

            WHERE existingDefault."IsDefault" = TRUE
        ),

        COALESCE
        (
            NULLIF
            (
                BTRIM(configuration."SecrateKey"),
                ''
            ),

            NULLIF
            (
                BTRIM(configuration."SmtpPasswordEncrypted"),
                ''
            )
        )

    FROM axionpro."TenantEmailConfig"
        configuration

    WHERE configuration."IsActive" = TRUE

      AND NULLIF
          (
              BTRIM(configuration."SmtpHost"),
              ''
          ) IS NOT NULL

      AND configuration."SmtpPort"
          BETWEEN 1 AND 65535

      AND NULLIF
          (
              BTRIM(configuration."SmtpUsername"),
              ''
          ) IS NOT NULL

      AND COALESCE
          (
              NULLIF
              (
                  BTRIM(configuration."SmtpPasswordEncrypted"),
                  ''
              ),

              NULLIF
              (
                  BTRIM(configuration."SecrateKey"),
                  ''
              )
          ) IS NOT NULL

      AND NULLIF
          (
              BTRIM(configuration."FromEmail"),
              ''
          ) IS NOT NULL

      AND NULLIF
          (
              BTRIM(configuration."FromName"),
              ''
          ) IS NOT NULL

    ORDER BY configuration."Id" DESC

    LIMIT 1


    ON CONFLICT ("ConfigName")

    DO UPDATE SET

        "SmtpHost"
            = EXCLUDED."SmtpHost",

        "SmtpPort"
            = EXCLUDED."SmtpPort",

        "SmtpUsername"
            = EXCLUDED."SmtpUsername",

        "SmtpPasswordEncrypted"
            = EXCLUDED."SmtpPasswordEncrypted",

        "FromEmail"
            = EXCLUDED."FromEmail",

        "FromName"
            = EXCLUDED."FromName",

        "IsActive"
            = TRUE,

        "SecrateKey"
            = EXCLUDED."SecrateKey",

        "UpdatedDateTime"
            = CURRENT_TIMESTAMP;


    IF NOT FOUND THEN

        RAISE EXCEPTION
        'No complete active TenantEmailConfig found. DefaultEmailConfig could not be seeded.';

    END IF;

END;
$$;


-- ============================================================================
-- DEFAULT CONFIG MARK
-- ============================================================================
--
-- Agar pehle se koi IsDefault = true nahi hai,
-- to DEFAULT_REGISTRATION_SMTP ko default bana diya jayega.
-- ============================================================================

UPDATE axionpro."DefaultEmailConfig"
SET
    "IsDefault" = TRUE,

    "UpdatedDateTime" = CURRENT_TIMESTAMP

WHERE "ConfigName" = 'DEFAULT_REGISTRATION_SMTP'

  AND "IsActive" = TRUE

  AND "IsDefault" = FALSE

  AND NOT EXISTS
  (
      SELECT 1

      FROM axionpro."DefaultEmailConfig"

      WHERE "IsDefault" = TRUE
  );


-- ============================================================================
-- SECTION 4
-- HOST MODULE : PLATFORM EMAIL DEFAULTS
-- ============================================================================
--
-- ModuleScope = 2
-- Host Admin module
--
-- Purpose:
-- New Tenant registration ke waqt selected/default SMTP configuration
-- TenantEmailConfig me copy hogi.
-- ============================================================================


-- ---------------------------------------------------------------------------
-- Existing module hai to usko complete/normalize karo.
-- ---------------------------------------------------------------------------

UPDATE axionpro."Module"

SET

    "TenantId" = NULL,

    "ModuleName"
        = 'Platform Email Defaults',

    "DisplayName"
        = 'Platform Email Defaults',

    "URLPath"
        = '/app/default-email-config',

    "ParentModuleId"
        = NULL,

    "IsLeafNode"
        = TRUE,

    "IsModuleDisplayInUI"
        = TRUE,

    "IsCommonMenu"
        = FALSE,

    "IsActive"
        = TRUE,

    "ImageIconWeb"
        = 'bi bi-envelope-gear',

    "ImageIconMobile"
        = 'mail-settings',

    "ItemPriority"
        = 410,

    "Remark"
        = 'Host-managed default SMTP profile copied when a tenant is registered.',

    "UpdatedById"
        = 1,

    "UpdatedDateTime"
        = CURRENT_TIMESTAMP,

    "ModuleScope"
        = 2

WHERE "ModuleCode"
    = 'HOST_DEFAULT_EMAIL_CONFIG';


-- ---------------------------------------------------------------------------
-- Existing module nahi hai to create karo.
-- Id explicitly nahi diya gaya hai.
-- PostgreSQL identity automatically next Id generate karega.
-- ---------------------------------------------------------------------------

INSERT INTO axionpro."Module"
(
    "TenantId",

    "ModuleCode",

    "ModuleName",

    "DisplayName",

    "URLPath",

    "ParentModuleId",

    "IsLeafNode",

    "IsModuleDisplayInUI",

    "IsCommonMenu",

    "IsActive",

    "ImageIconWeb",

    "ImageIconMobile",

    "ItemPriority",

    "Remark",

    "AddedById",

    "AddedDateTime",

    "UpdatedById",

    "UpdatedDateTime",

    "ModuleScope"
)

SELECT

    NULL,

    'HOST_DEFAULT_EMAIL_CONFIG',

    'Platform Email Defaults',

    'Platform Email Defaults',

    '/app/default-email-config',

    NULL,

    TRUE,

    TRUE,

    FALSE,

    TRUE,

    'bi bi-envelope-gear',

    'mail-settings',

    410,

    'Host-managed default SMTP profile copied when a tenant is registered.',

    1,

    CURRENT_TIMESTAMP,

    NULL,

    NULL,

    2

WHERE NOT EXISTS
(
    SELECT 1

    FROM axionpro."Module"

    WHERE "ModuleCode"
        = 'HOST_DEFAULT_EMAIL_CONFIG'
);


-- ============================================================================
-- SECTION 5
-- TENANT MODULE : EMAIL DELIVERY SETTINGS
-- ============================================================================
--
-- ModuleScope = 1
--
-- APIs:
--
-- POST
-- /api/TenantEmailConfig/create
--
-- GET
-- /api/TenantEmailConfig/get-all
--
-- GET
-- /api/TenantEmailConfig/get-by-id/{id}
--
-- POST
-- /api/TenantEmailConfig/update
--
-- DELETE
-- /api/TenantEmailConfig/delete/{id}
--
-- ============================================================================


-- ---------------------------------------------------------------------------
-- Existing module normalize/update.
-- ---------------------------------------------------------------------------

UPDATE axionpro."Module"

SET

    "TenantId"
        = NULL,

    "ModuleName"
        = 'Email Delivery Settings',

    "DisplayName"
        = 'Email Settings',

    "URLPath"
        = '/app/tenant-email-config',

    "ParentModuleId"
        = NULL,

    "IsLeafNode"
        = TRUE,

    "IsModuleDisplayInUI"
        = TRUE,

    "IsCommonMenu"
        = FALSE,

    "IsActive"
        = TRUE,

    "ImageIconWeb"
        = 'bi bi-envelope-at',

    "ImageIconMobile"
        = 'mail',

    "ItemPriority"
        = 410,

    "Remark"
        = 'Tenant-owned SMTP settings for authorised transactional and notification email delivery.',

    "UpdatedById"
        = 1,

    "UpdatedDateTime"
        = CURRENT_TIMESTAMP,

    "ModuleScope"
        = 1

WHERE "ModuleCode"
    = 'TENANT_EMAIL_CONFIG';


-- ---------------------------------------------------------------------------
-- Create when missing.
-- ---------------------------------------------------------------------------

INSERT INTO axionpro."Module"
(
    "TenantId",

    "ModuleCode",

    "ModuleName",

    "DisplayName",

    "URLPath",

    "ParentModuleId",

    "IsLeafNode",

    "IsModuleDisplayInUI",

    "IsCommonMenu",

    "IsActive",

    "ImageIconWeb",

    "ImageIconMobile",

    "ItemPriority",

    "Remark",

    "AddedById",

    "AddedDateTime",

    "UpdatedById",

    "UpdatedDateTime",

    "ModuleScope"
)

SELECT

    NULL,

    'TENANT_EMAIL_CONFIG',

    'Email Delivery Settings',

    'Email Settings',

    '/app/tenant-email-config',

    NULL,

    TRUE,

    TRUE,

    FALSE,

    TRUE,

    'bi bi-envelope-at',

    'mail',

    410,

    'Tenant-owned SMTP settings for authorised transactional and notification email delivery.',

    1,

    CURRENT_TIMESTAMP,

    NULL,

    NULL,

    1

WHERE NOT EXISTS
(
    SELECT 1

    FROM axionpro."Module"

    WHERE "ModuleCode"
        = 'TENANT_EMAIL_CONFIG'
);


-- ============================================================================
-- SECTION 6
-- HOST DEFAULT EMAIL CONFIG MODULE OPERATION MAPPING
-- ============================================================================
--
-- Existing Operation master reuse hoga.
--
-- Supported operation names:
--
-- View / Read
-- Create / Add
-- Update / Edit
-- Delete
--
-- ============================================================================

INSERT INTO axionpro."ModuleOperationMapping"
(
    "ModuleId",

    "OperationId",

    "IsCommonItem",

    "IsOperational",

    "Priority",

    "Remark",

    "IsActive",

    "AddedById",

    "AddedDateTime"
)

SELECT

    module."Id",

    operation."Id",

    FALSE,

    TRUE,

    CASE

        WHEN LOWER(BTRIM(operation."OperationName"))
             IN ('view', 'read')
            THEN 1

        WHEN LOWER(BTRIM(operation."OperationName"))
             IN ('create', 'add')
            THEN 2

        WHEN LOWER(BTRIM(operation."OperationName"))
             IN ('update', 'edit')
            THEN 3

        WHEN LOWER(BTRIM(operation."OperationName"))
             = 'delete'
            THEN 4

        ELSE 10

    END,

    CASE

        WHEN LOWER(BTRIM(operation."OperationName"))
             IN ('view', 'read')

            THEN
            'View Host default email configuration.'

        WHEN LOWER(BTRIM(operation."OperationName"))
             IN ('create', 'add')

            THEN
            'Create Host default email configuration.'

        WHEN LOWER(BTRIM(operation."OperationName"))
             IN ('update', 'edit')

            THEN
            'Update Host default email configuration.'

        WHEN LOWER(BTRIM(operation."OperationName"))
             = 'delete'

            THEN
            'Delete Host default email configuration.'

        ELSE
            'Host default email configuration operation.'

    END,

    TRUE,

    1,

    CURRENT_TIMESTAMP

FROM axionpro."Module" module

INNER JOIN axionpro."Operation" operation

    ON LOWER(BTRIM(operation."OperationName"))

       IN
       (
           'view',
           'read',
           'create',
           'add',
           'update',
           'edit',
           'delete'
       )

WHERE module."ModuleCode"
      = 'HOST_DEFAULT_EMAIL_CONFIG'

  AND operation."IsActive"
      = TRUE

  AND NOT EXISTS
  (
      SELECT 1

      FROM axionpro."ModuleOperationMapping"
          existingMapping

      WHERE existingMapping."ModuleId"
            = module."Id"

        AND existingMapping."OperationId"
            = operation."Id"
  );


-- ============================================================================
-- SECTION 7
-- TENANT EMAIL CONFIG MODULE OPERATION MAPPING
-- ============================================================================

INSERT INTO axionpro."ModuleOperationMapping"
(
    "ModuleId",

    "OperationId",

    "IsCommonItem",

    "IsOperational",

    "Priority",

    "Remark",

    "IsActive",

    "AddedById",

    "AddedDateTime"
)

SELECT

    module."Id",

    operation."Id",

    FALSE,

    TRUE,

    CASE

        WHEN LOWER(BTRIM(operation."OperationName"))
             IN ('view', 'read')
            THEN 1

        WHEN LOWER(BTRIM(operation."OperationName"))
             IN ('create', 'add')
            THEN 2

        WHEN LOWER(BTRIM(operation."OperationName"))
             IN ('update', 'edit')
            THEN 3

        WHEN LOWER(BTRIM(operation."OperationName"))
             = 'delete'
            THEN 4

        ELSE 10

    END,

    CASE

        WHEN LOWER(BTRIM(operation."OperationName"))
             IN ('view', 'read')

            THEN
            'View Tenant email configuration.'

        WHEN LOWER(BTRIM(operation."OperationName"))
             IN ('create', 'add')

            THEN
            'Create Tenant email configuration.'

        WHEN LOWER(BTRIM(operation."OperationName"))
             IN ('update', 'edit')

            THEN
            'Update Tenant email configuration.'

        WHEN LOWER(BTRIM(operation."OperationName"))
             = 'delete'

            THEN
            'Delete Tenant email configuration.'

        ELSE
            'Tenant email configuration operation.'

    END,

    TRUE,

    1,

    CURRENT_TIMESTAMP

FROM axionpro."Module" module

INNER JOIN axionpro."Operation" operation

    ON LOWER(BTRIM(operation."OperationName"))

       IN
       (
           'view',
           'read',
           'create',
           'add',
           'update',
           'edit',
           'delete'
       )

WHERE module."ModuleCode"
      = 'TENANT_EMAIL_CONFIG'

  AND operation."IsActive"
      = TRUE

  AND NOT EXISTS
  (
      SELECT 1

      FROM axionpro."ModuleOperationMapping"
          existingMapping

      WHERE existingMapping."ModuleId"
            = module."Id"

        AND existingMapping."OperationId"
            = operation."Id"
  );


-- ============================================================================
-- SECTION 8
-- NORMALIZE EXISTING MODULE OPERATION MAPPINGS
-- ============================================================================

UPDATE axionpro."ModuleOperationMapping"
    mapping

SET

    "IsCommonItem"
        = FALSE,

    "IsOperational"
        = TRUE,

    "Priority"
        =
        CASE

            WHEN LOWER(BTRIM(operation."OperationName"))
                 IN ('view', 'read')
                THEN 1

            WHEN LOWER(BTRIM(operation."OperationName"))
                 IN ('create', 'add')
                THEN 2

            WHEN LOWER(BTRIM(operation."OperationName"))
                 IN ('update', 'edit')
                THEN 3

            WHEN LOWER(BTRIM(operation."OperationName"))
                 = 'delete'
                THEN 4

            ELSE mapping."Priority"

        END,

    "Remark"
        =
        CASE

            WHEN module."ModuleCode"
                 = 'HOST_DEFAULT_EMAIL_CONFIG'

                 AND LOWER(BTRIM(operation."OperationName"))
                     IN ('view', 'read')

                THEN
                'View Host default email configuration.'


            WHEN module."ModuleCode"
                 = 'HOST_DEFAULT_EMAIL_CONFIG'

                 AND LOWER(BTRIM(operation."OperationName"))
                     IN ('create', 'add')

                THEN
                'Create Host default email configuration.'


            WHEN module."ModuleCode"
                 = 'HOST_DEFAULT_EMAIL_CONFIG'

                 AND LOWER(BTRIM(operation."OperationName"))
                     IN ('update', 'edit')

                THEN
                'Update Host default email configuration.'


            WHEN module."ModuleCode"
                 = 'HOST_DEFAULT_EMAIL_CONFIG'

                 AND LOWER(BTRIM(operation."OperationName"))
                     = 'delete'

                THEN
                'Delete Host default email configuration.'


            WHEN module."ModuleCode"
                 = 'TENANT_EMAIL_CONFIG'

                 AND LOWER(BTRIM(operation."OperationName"))
                     IN ('view', 'read')

                THEN
                'View Tenant email configuration.'


            WHEN module."ModuleCode"
                 = 'TENANT_EMAIL_CONFIG'

                 AND LOWER(BTRIM(operation."OperationName"))
                     IN ('create', 'add')

                THEN
                'Create Tenant email configuration.'


            WHEN module."ModuleCode"
                 = 'TENANT_EMAIL_CONFIG'

                 AND LOWER(BTRIM(operation."OperationName"))
                     IN ('update', 'edit')

                THEN
                'Update Tenant email configuration.'


            WHEN module."ModuleCode"
                 = 'TENANT_EMAIL_CONFIG'

                 AND LOWER(BTRIM(operation."OperationName"))
                     = 'delete'

                THEN
                'Delete Tenant email configuration.'


            ELSE mapping."Remark"

        END,

    "IsActive"
        = TRUE

FROM axionpro."Module"
    module,

     axionpro."Operation"
    operation

WHERE mapping."ModuleId"
      = module."Id"

  AND mapping."OperationId"
      = operation."Id"

  AND module."ModuleCode"
      IN
      (
          'HOST_DEFAULT_EMAIL_CONFIG',
          'TENANT_EMAIL_CONFIG'
      );


-- ============================================================================
-- SECTION 8A
-- CONSOLIDATED HOST / TENANT EMAIL AND DEVICE MODULES
-- ============================================================================
-- This transaction-local seed replaces the former standalone module seed files.
-- ModuleCode is an immutable permission contract; ModuleName/DisplayName are
-- the professional labels presented to administrators and end users.
-- ItemPriority is ascending within each parent/scope. A negative priority is
-- reserved for terminal Common-menu items such as Sign out.
-- It drives module normalization and standard CRUD operation mappings.
-- ============================================================================

CREATE TEMPORARY TABLE module_seed
(
    "ModuleCode" CHARACTER VARYING(100) PRIMARY KEY,
    "ModuleName" CHARACTER VARYING(200) NOT NULL,
    "DisplayName" CHARACTER VARYING(200) NOT NULL,
    "URLPath" CHARACTER VARYING(500) NOT NULL,
    "IsModuleDisplayInUI" BOOLEAN NOT NULL,
    "ImageIconWeb" CHARACTER VARYING(100) NULL,
    "ImageIconMobile" CHARACTER VARYING(100) NULL,
    "ModuleScope" SMALLINT NOT NULL,
    "ItemPriority" INTEGER NOT NULL,
    "Remark" CHARACTER VARYING(1000) NOT NULL
)
ON COMMIT DROP;

INSERT INTO module_seed
(
    "ModuleCode", "ModuleName", "DisplayName", "URLPath",
    "IsModuleDisplayInUI", "ImageIconWeb", "ImageIconMobile",
    "ModuleScope", "ItemPriority", "Remark"
)
VALUES
(
    'HOST_DEFAULT_EMAIL_CONFIG',
    'Platform Email Defaults',
    'Platform Email Defaults',
    '/app/default-email-config',
    TRUE,
    'bi bi-envelope-gear',
    'mail-settings',
    2,
    410,
    'Host-managed default SMTP profile copied when a tenant is registered.'
),
(
    'TENANT_EMAIL_CONFIG',
    'Email Delivery Settings',
    'Email Settings',
    '/app/tenant-email-config',
    TRUE,
    'bi bi-envelope-at',
    'mail',
    1,
    410,
    'Tenant-owned SMTP settings for authorised transactional and notification email delivery.'
),
(
    'HOST_TENANT_EMAIL_CONFIG',
    'Tenant Email Administration',
    'Tenant Email Administration',
    '/app/tenants/tenant-email-config',
    TRUE,
    'bi bi-envelope-at',
    'mail',
    2,
    420,
    'Host administration of a selected tenant''s SMTP configuration.'
),
(
    'HOST_EMAIL_TEMPLATE',
    'Email Template Library',
    'Email Templates',
    '/app/email-templates',
    TRUE,
    'bi bi-envelope',
    'mail',
    2,
    430,
    'Host-managed reusable templates for platform email communication.'
),
(
    'HOST_DEVICE_SETUP',
    'Device Catalogue',
    'Device Catalogue',
    '/app/device-masters',
    TRUE,
    'bi bi-cpu',
    'memory',
    2,
    510,
    'Host-managed device models, hardware capabilities, and supported transport profiles.'
),
(
    'TENANT_DEVICE_SETUP',
    'Installed Devices',
    'Installed Devices',
    '/app/tenant-devices',
    TRUE,
    'bi bi-hdd-network',
    'devices',
    1,
    510,
    'Tenant device installation, location assignment, activation, and lifecycle management.'
),
(
    'HOST_INITIAL_DEVICE_CONFIGURATION',
    'Device Provisioning',
    'Device Provisioning',
    '/app/device-masters',
    FALSE,
    'bi bi-router',
    'router',
    2,
    520,
    'Host-only permission for issuing one-time device bootstrap URLs from the device onboarding flow.'
),
(
    'TENANT_DEVICE_CONFIGURATION',
    'Device Connectivity',
    'Device Connectivity',
    '/app/tenant-device-configurations',
    TRUE,
    'bi bi-sliders',
    'settings',
    1,
    520,
    'Tenant-admin configuration of device connectivity, gateway rotation, heartbeat, and reboot.'
);

UPDATE axionpro."Module" module
SET
    "TenantId" = NULL,
    "ModuleName" = seed."ModuleName",
    "DisplayName" = seed."DisplayName",
    "URLPath" = seed."URLPath",
    "ParentModuleId" = NULL,
    "IsLeafNode" = TRUE,
    "IsModuleDisplayInUI" = seed."IsModuleDisplayInUI",
    "IsCommonMenu" = FALSE,
    "IsActive" = TRUE,
    "ImageIconWeb" = seed."ImageIconWeb",
    "ImageIconMobile" = seed."ImageIconMobile",
    "ItemPriority" = seed."ItemPriority",
    "Remark" = seed."Remark",
    "UpdatedById" = 1,
    "UpdatedDateTime" = CURRENT_TIMESTAMP,
    "ModuleScope" = seed."ModuleScope"
FROM module_seed seed
WHERE module."ModuleCode" = seed."ModuleCode";

INSERT INTO axionpro."Module"
(
    "TenantId", "ModuleCode", "ModuleName", "DisplayName", "URLPath",
    "ParentModuleId", "IsLeafNode", "IsModuleDisplayInUI", "IsCommonMenu",
    "IsActive", "ImageIconWeb", "ImageIconMobile", "ItemPriority", "Remark",
    "AddedById", "AddedDateTime", "ModuleScope"
)
SELECT
    NULL,
    seed."ModuleCode",
    seed."ModuleName",
    seed."DisplayName",
    seed."URLPath",
    NULL,
    TRUE,
    seed."IsModuleDisplayInUI",
    FALSE,
    TRUE,
    seed."ImageIconWeb",
    seed."ImageIconMobile",
    seed."ItemPriority",
    seed."Remark",
    1,
    CURRENT_TIMESTAMP,
    seed."ModuleScope"
FROM module_seed seed
WHERE NOT EXISTS
(
    SELECT 1
    FROM axionpro."Module" existing
    WHERE existing."ModuleCode" = seed."ModuleCode"
);

INSERT INTO axionpro."ModuleOperationMapping"
(
    "ModuleId", "OperationId", "PageURL", "IconURL", "IsCommonItem",
    "IsOperational", "Priority", "Remark", "IsActive", "AddedById", "AddedDateTime"
)
SELECT
    module."Id",
    operation."Id",
    module."URLPath",
    COALESCE(NULLIF(BTRIM(operation."IconImage"), ''), module."ImageIconWeb"),
    FALSE,
    TRUE,
    CASE
        WHEN LOWER(BTRIM(operation."OperationName")) IN ('view', 'read') THEN 10
        WHEN LOWER(BTRIM(operation."OperationName")) IN ('create', 'add') THEN 20
        WHEN LOWER(BTRIM(operation."OperationName")) IN ('update', 'edit') THEN 30
        WHEN LOWER(BTRIM(operation."OperationName")) = 'delete' THEN 40
        ELSE 99
    END,
    CASE
        WHEN LOWER(BTRIM(operation."OperationName")) IN ('view', 'read')
            THEN 'View ' || module."DisplayName" || '.'
        WHEN LOWER(BTRIM(operation."OperationName")) IN ('create', 'add')
            THEN 'Create ' || module."DisplayName" || '.'
        WHEN LOWER(BTRIM(operation."OperationName")) IN ('update', 'edit')
            THEN 'Update ' || module."DisplayName" || '.'
        WHEN LOWER(BTRIM(operation."OperationName")) = 'delete'
            THEN 'Delete ' || module."DisplayName" || '.'
        ELSE module."DisplayName" || ' permission.'
    END,
    TRUE,
    1,
    CURRENT_TIMESTAMP
FROM axionpro."Module" module
INNER JOIN module_seed seed
    ON seed."ModuleCode" = module."ModuleCode"
INNER JOIN axionpro."Operation" operation
    ON LOWER(BTRIM(operation."OperationName")) IN
       ('view', 'read', 'create', 'add', 'update', 'edit', 'delete')
WHERE operation."IsActive" = TRUE
  AND NOT EXISTS
  (
      SELECT 1
      FROM axionpro."ModuleOperationMapping" existing
      WHERE existing."ModuleId" = module."Id"
        AND existing."OperationId" = operation."Id"
  );

UPDATE axionpro."ModuleOperationMapping" mapping
SET
    "PageURL" = module."URLPath",
    "IconURL" = COALESCE(NULLIF(BTRIM(operation."IconImage"), ''), module."ImageIconWeb"),
    "IsCommonItem" = FALSE,
    "IsOperational" = TRUE,
    "Priority" = CASE
        WHEN LOWER(BTRIM(operation."OperationName")) IN ('view', 'read') THEN 10
        WHEN LOWER(BTRIM(operation."OperationName")) IN ('create', 'add') THEN 20
        WHEN LOWER(BTRIM(operation."OperationName")) IN ('update', 'edit') THEN 30
        WHEN LOWER(BTRIM(operation."OperationName")) = 'delete' THEN 40
        ELSE 99
    END,
    "Remark" = CASE
        WHEN LOWER(BTRIM(operation."OperationName")) IN ('view', 'read')
            THEN 'View ' || module."DisplayName" || '.'
        WHEN LOWER(BTRIM(operation."OperationName")) IN ('create', 'add')
            THEN 'Create ' || module."DisplayName" || '.'
        WHEN LOWER(BTRIM(operation."OperationName")) IN ('update', 'edit')
            THEN 'Update ' || module."DisplayName" || '.'
        WHEN LOWER(BTRIM(operation."OperationName")) = 'delete'
            THEN 'Delete ' || module."DisplayName" || '.'
        ELSE module."DisplayName" || ' permission.'
    END,
    "IsActive" = TRUE,
    "UpdatedById" = 1,
    "UpdatedDateTime" = CURRENT_TIMESTAMP
FROM axionpro."Module" module,
     module_seed seed,
     axionpro."Operation" operation
WHERE mapping."ModuleId" = module."Id"
  AND seed."ModuleCode" = module."ModuleCode"
  AND operation."Id" = mapping."OperationId"
  AND LOWER(BTRIM(operation."OperationName")) IN
      ('view', 'read', 'create', 'add', 'update', 'edit', 'delete');


-- ============================================================================
-- SECTION 8B
-- EMPLOYEE PASSWORD MANAGEMENT MODULE, OPERATION, AND PLAN INHERITANCE
-- ============================================================================
-- Reset Password is a dedicated security permission. Plans inherit it only
-- where EMP_LIST is already enabled; no role permission is granted here.
-- ============================================================================

DO
$$
DECLARE
    employee_parent_count INTEGER;
BEGIN
    SELECT COUNT(*)
    INTO employee_parent_count
    FROM axionpro."Module"
    WHERE "ModuleCode" = 'EMP_MGMT'
      AND "ParentModuleId" IS NULL
      AND "IsLeafNode" = FALSE
      AND "ModuleScope" = 1;

    IF employee_parent_count <> 1 THEN
        RAISE EXCEPTION
            'Expected exactly one Tenant-scope EMP_MGMT parent Module, found %.',
            employee_parent_count;
    END IF;
END;
$$;

INSERT INTO axionpro."Module"
(
    "TenantId", "ModuleCode", "ModuleName", "DisplayName", "URLPath",
    "ParentModuleId", "IsLeafNode", "IsModuleDisplayInUI", "IsCommonMenu",
    "IsActive", "ImageIconWeb", "ImageIconMobile", "ItemPriority", "Remark",
    "AddedById", "AddedDateTime", "ModuleScope"
)
SELECT
    NULL,
    'EMP_PASSWORD_MANAGEMENT',
    'Employee-Password-Management',
    'Employee Password Management',
    '/employees/password-management',
    parent."Id",
    TRUE,
    TRUE,
    FALSE,
    TRUE,
    'bi bi-key',
    'key',
    40,
    'Tenant-admin reset of a selected employee login password.',
    1,
    CURRENT_TIMESTAMP,
    1
FROM axionpro."Module" parent
WHERE parent."ModuleCode" = 'EMP_MGMT'
  AND parent."ParentModuleId" IS NULL
  AND parent."IsLeafNode" = FALSE
  AND parent."ModuleScope" = 1
  AND NOT EXISTS
  (
      SELECT 1
      FROM axionpro."Module" existing
      WHERE existing."ModuleCode" = 'EMP_PASSWORD_MANAGEMENT'
  );

UPDATE axionpro."Module" module
SET
    "TenantId" = NULL,
    "ModuleName" = 'Employee-Password-Management',
    "DisplayName" = 'Employee Password Management',
    "URLPath" = '/employees/password-management',
    "ParentModuleId" =
    (
        SELECT parent."Id"
        FROM axionpro."Module" parent
        WHERE parent."ModuleCode" = 'EMP_MGMT'
          AND parent."ParentModuleId" IS NULL
          AND parent."IsLeafNode" = FALSE
          AND parent."ModuleScope" = 1
    ),
    "IsLeafNode" = TRUE,
    "IsModuleDisplayInUI" = TRUE,
    "IsCommonMenu" = FALSE,
    "IsActive" = TRUE,
    "ImageIconWeb" = 'bi bi-key',
    "ImageIconMobile" = 'key',
    "ItemPriority" = 40,
    "Remark" = 'Tenant-admin reset of a selected employee login password.',
    "UpdatedById" = 1,
    "UpdatedDateTime" = CURRENT_TIMESTAMP,
    "ModuleScope" = 1
WHERE module."ModuleCode" = 'EMP_PASSWORD_MANAGEMENT';

INSERT INTO axionpro."Operation"
(
    "OperationName", "Remark", "OperationType", "IsActive",
    "AddedById", "AddedDateTime", "IconImage"
)
SELECT
    'Reset Password',
    'Reset the login password of a selected tenant employee',
    4,
    TRUE,
    1,
    CURRENT_TIMESTAMP,
    'key-round'
WHERE NOT EXISTS
(
    SELECT 1
    FROM axionpro."Operation"
    WHERE LOWER(BTRIM("OperationName")) = LOWER('Reset Password')
);

UPDATE axionpro."Operation"
SET
    "Remark" = 'Reset the login password of a selected tenant employee',
    "OperationType" = 4,
    "IsActive" = TRUE,
    "IconImage" = 'key-round',
    "UpdatedById" = 1,
    "UpdatedDateTime" = CURRENT_TIMESTAMP
WHERE LOWER(BTRIM("OperationName")) = LOWER('Reset Password');

INSERT INTO axionpro."ModuleOperationMapping"
(
    "ModuleId", "OperationId", "PageURL", "IconURL", "IsCommonItem",
    "IsOperational", "Priority", "Remark", "IsActive", "AddedById", "AddedDateTime"
)
SELECT
    module."Id",
    operation."Id",
    '/employees/password-management',
    'key-round',
    FALSE,
    TRUE,
    10,
    'Allow an authorized tenant administrator to reset an employee password',
    TRUE,
    1,
    CURRENT_TIMESTAMP
FROM axionpro."Module" module
INNER JOIN axionpro."Operation" operation
    ON LOWER(BTRIM(operation."OperationName")) = LOWER('Reset Password')
WHERE module."ModuleCode" = 'EMP_PASSWORD_MANAGEMENT'
  AND module."IsLeafNode" = TRUE
  AND module."ModuleScope" = 1
  AND NOT EXISTS
  (
      SELECT 1
      FROM axionpro."ModuleOperationMapping" existing
      WHERE existing."ModuleId" = module."Id"
        AND existing."OperationId" = operation."Id"
  );

UPDATE axionpro."ModuleOperationMapping" mapping
SET
    "PageURL" = '/employees/password-management',
    "IconURL" = 'key-round',
    "IsCommonItem" = FALSE,
    "IsOperational" = TRUE,
    "Priority" = 10,
    "Remark" = 'Allow an authorized tenant administrator to reset an employee password',
    "IsActive" = TRUE,
    "UpdatedById" = 1,
    "UpdatedDateTime" = CURRENT_TIMESTAMP
FROM axionpro."Module" module
INNER JOIN axionpro."Operation" operation
    ON LOWER(BTRIM(operation."OperationName")) = LOWER('Reset Password')
WHERE mapping."ModuleId" = module."Id"
  AND mapping."OperationId" = operation."Id"
  AND module."ModuleCode" = 'EMP_PASSWORD_MANAGEMENT';

-- ============================================================================
-- SECTION 8B
-- TENANT PLATFORM FEATURE PLAN INHERITANCE
-- ============================================================================
-- A Tenant entitlement is sourced only from an active PlanModuleMapping.
-- These baseline Tenant features inherit precisely the active plan coverage of
-- EMP_LIST. This is the established baseline module already present in plans;
-- Host-only modules are deliberately not assigned to any Subscription Plan.
-- Existing mappings are never altered, so a Host's later plan-specific choice
-- remains authoritative.

DO
$$
DECLARE
    employee_list_plan_count INTEGER;
    target_module_count INTEGER;
BEGIN
    SELECT COUNT(DISTINCT source."SubscriptionPlanId")
    INTO employee_list_plan_count
    FROM axionpro."PlanModuleMapping" source
    INNER JOIN axionpro."Module" source_module
        ON source_module."Id" = source."ModuleId"
    WHERE source_module."ModuleCode" = 'EMP_LIST'
      AND source."IsActive" = TRUE;

    IF employee_list_plan_count = 0 THEN
        RAISE EXCEPTION
            'No active EMP_LIST PlanModuleMapping exists. Tenant feature plan mappings cannot be seeded.';
    END IF;

    SELECT COUNT(*)
    INTO target_module_count
    FROM axionpro."Module" target_module
    WHERE target_module."ModuleCode" IN
          (
              'TENANT_EMAIL_CONFIG',
              'TENANT_DEVICE_SETUP',
              'TENANT_DEVICE_CONFIGURATION',
              'EMP_PASSWORD_MANAGEMENT'
          )
      AND target_module."ModuleScope" = 1
      AND target_module."IsActive" = TRUE;

    IF target_module_count <> 4 THEN
        RAISE EXCEPTION
            'Expected four active Tenant feature modules before plan inheritance; found %.',
            target_module_count;
    END IF;

    INSERT INTO axionpro."PlanModuleMapping"
    (
        "SubscriptionPlanId", "ModuleId", "IsActive", "Remark",
        "AddedById", "AddedDateTime", "UpdatedById", "UpdatedDateTime"
    )
    SELECT DISTINCT
        source."SubscriptionPlanId",
        target_module."Id",
        TRUE,
        'Baseline Tenant feature inherited from active EMP_LIST plan coverage.',
        1,
        CURRENT_TIMESTAMP,
        1,
        CURRENT_TIMESTAMP
    FROM axionpro."PlanModuleMapping" source
    INNER JOIN axionpro."Module" source_module
        ON source_module."Id" = source."ModuleId"
       AND source_module."ModuleCode" = 'EMP_LIST'
    INNER JOIN axionpro."Module" target_module
        ON target_module."ModuleCode" IN
           (
               'TENANT_EMAIL_CONFIG',
               'TENANT_DEVICE_SETUP',
               'TENANT_DEVICE_CONFIGURATION',
               'EMP_PASSWORD_MANAGEMENT'
           )
       AND target_module."ModuleScope" = 1
       AND target_module."IsActive" = TRUE
    WHERE source."IsActive" = TRUE
      AND NOT EXISTS
      (
          SELECT 1
          FROM axionpro."PlanModuleMapping" existing
          WHERE existing."SubscriptionPlanId" = source."SubscriptionPlanId"
            AND existing."ModuleId" = target_module."Id"
      );
END;
$$;


-- ============================================================================
-- SECTION 8C
-- HOST TENANT LIST CREATE ACTION
-- ============================================================================
-- The Host Tenant List page owns its row actions.  Keep Create attached to
-- this leaf module so Navigation/my-menu can render the action from the same
-- permission object.  This does not grant the permission to any Host role.

DO
$$
DECLARE
    host_tenant_list_module_id INTEGER;
    create_operation_id INTEGER;
BEGIN
    INSERT INTO axionpro."Operation"
    (
        "OperationName", "Remark", "OperationType", "IsActive",
        "AddedById", "AddedDateTime", "IconImage"
    )
    SELECT
        'Create',
        'Create a new record.',
        1,
        TRUE,
        1,
        CURRENT_TIMESTAMP,
        'plus'
    WHERE NOT EXISTS
    (
        SELECT 1
        FROM axionpro."Operation"
        WHERE LOWER(BTRIM("OperationName")) = 'create'
    );

    SELECT "Id"
    INTO host_tenant_list_module_id
    FROM axionpro."Module"
    WHERE "ModuleCode" = 'HOST_TENANT_LIST'
      AND "ModuleScope" = 2
      AND "IsLeafNode" = TRUE
    ORDER BY "Id"
    LIMIT 1;

    IF host_tenant_list_module_id IS NULL THEN
        RAISE EXCEPTION
            'HOST_TENANT_LIST module was not found; Create navigation mapping cannot be seeded.';
    END IF;

    SELECT "Id"
    INTO create_operation_id
    FROM axionpro."Operation"
    WHERE LOWER(BTRIM("OperationName")) = 'create'
      AND "IsActive" = TRUE
    ORDER BY "Id"
    LIMIT 1;

    IF create_operation_id IS NULL THEN
        RAISE EXCEPTION
            'Active Create operation was not found; HOST_TENANT_LIST mapping cannot be seeded.';
    END IF;

    INSERT INTO axionpro."ModuleOperationMapping"
    (
        "ModuleId", "OperationId", "PageURL", "IconURL", "IsCommonItem",
        "IsOperational", "Priority", "Remark", "IsActive", "AddedById", "AddedDateTime"
    )
    SELECT
        module."Id",
        operation."Id",
        module."URLPath",
        COALESCE(NULLIF(BTRIM(operation."IconImage"), ''), 'plus'),
        FALSE,
        TRUE,
        20,
        'Create a new tenant from the Host Tenant List.',
        TRUE,
        1,
        CURRENT_TIMESTAMP
    FROM axionpro."Module" module
    INNER JOIN axionpro."Operation" operation
        ON operation."Id" = create_operation_id
    WHERE module."Id" = host_tenant_list_module_id
      AND NOT EXISTS
      (
          SELECT 1
          FROM axionpro."ModuleOperationMapping" existing
          WHERE existing."ModuleId" = module."Id"
            AND existing."OperationId" = operation."Id"
      );

    UPDATE axionpro."ModuleOperationMapping" mapping
    SET
        "PageURL" = module."URLPath",
        "IconURL" = COALESCE(NULLIF(BTRIM(operation."IconImage"), ''), 'plus'),
        "IsCommonItem" = FALSE,
        "IsOperational" = TRUE,
        "Priority" = 20,
        "Remark" = 'Create a new tenant from the Host Tenant List.',
        "IsActive" = TRUE,
        "UpdatedById" = 1,
        "UpdatedDateTime" = CURRENT_TIMESTAMP
    FROM axionpro."Module" module
    INNER JOIN axionpro."Operation" operation
        ON operation."Id" = create_operation_id
    WHERE mapping."ModuleId" = module."Id"
      AND mapping."OperationId" = operation."Id"
      AND module."Id" = host_tenant_list_module_id;
END;
$$;


-- ============================================================================
-- SECTION 8D
-- CONSOLIDATED MODULE VALIDATION
-- ============================================================================

DO
$$
DECLARE
    invalid_module_count INTEGER;
    missing_crud_mapping_count INTEGER;
    password_module_count INTEGER;
    reset_password_operation_count INTEGER;
    reset_password_mapping_count INTEGER;
BEGIN
    SELECT COUNT(*)
    INTO invalid_module_count
    FROM module_seed seed
    WHERE
    (
        SELECT COUNT(*)
        FROM axionpro."Module" module
        WHERE module."ModuleCode" = seed."ModuleCode"
    ) <> 1;

    IF invalid_module_count <> 0 THEN
        RAISE EXCEPTION
            'Consolidated module validation failed: % seeded module code(s) did not resolve to exactly one Module row.',
            invalid_module_count;
    END IF;

    SELECT COUNT(*)
    INTO missing_crud_mapping_count
    FROM module_seed seed
    WHERE NOT EXISTS
    (
        SELECT 1
        FROM axionpro."ModuleOperationMapping" mapping
        INNER JOIN axionpro."Module" module
            ON module."Id" = mapping."ModuleId"
        INNER JOIN axionpro."Operation" operation
            ON operation."Id" = mapping."OperationId"
        WHERE module."ModuleCode" = seed."ModuleCode"
          AND mapping."IsActive" = TRUE
          AND operation."IsActive" = TRUE
          AND LOWER(BTRIM(operation."OperationName")) IN
              ('view', 'read', 'create', 'add', 'update', 'edit', 'delete')
    );

    IF missing_crud_mapping_count <> 0 THEN
        RAISE EXCEPTION
            'Consolidated mapping validation failed: % seeded module code(s) have no active CRUD mapping.',
            missing_crud_mapping_count;
    END IF;

    SELECT COUNT(*)
    INTO password_module_count
    FROM axionpro."Module"
    WHERE "ModuleCode" = 'EMP_PASSWORD_MANAGEMENT'
      AND "IsLeafNode" = TRUE
      AND "ModuleScope" = 1;

    SELECT COUNT(*)
    INTO reset_password_operation_count
    FROM axionpro."Operation"
    WHERE LOWER(BTRIM("OperationName")) = LOWER('Reset Password')
      AND "IsActive" = TRUE;

    SELECT COUNT(*)
    INTO reset_password_mapping_count
    FROM axionpro."ModuleOperationMapping" mapping
    INNER JOIN axionpro."Module" module
        ON module."Id" = mapping."ModuleId"
    INNER JOIN axionpro."Operation" operation
        ON operation."Id" = mapping."OperationId"
    WHERE module."ModuleCode" = 'EMP_PASSWORD_MANAGEMENT'
      AND LOWER(BTRIM(operation."OperationName")) = LOWER('Reset Password')
      AND mapping."IsActive" = TRUE;

    IF password_module_count <> 1 THEN
        RAISE EXCEPTION
            'EMP_PASSWORD_MANAGEMENT module validation failed. Expected 1, found %.',
            password_module_count;
    END IF;

    IF reset_password_operation_count <> 1 THEN
        RAISE EXCEPTION
            'Reset Password operation validation failed. Expected 1, found %.',
            reset_password_operation_count;
    END IF;

    IF reset_password_mapping_count <> 1 THEN
        RAISE EXCEPTION
            'EMP_PASSWORD_MANAGEMENT mapping validation failed. Expected 1, found %.',
            reset_password_mapping_count;
    END IF;
END;
$$;


-- ============================================================================
-- SECTION 9
-- PRODUCTION VALIDATION
-- ============================================================================
--
-- Agar required module ya operation mapping create nahi hui
-- to transaction COMMIT nahi hogi.
-- ============================================================================

DO
$$
DECLARE

    host_module_count INTEGER;

    tenant_module_count INTEGER;

    host_mapping_count INTEGER;

    tenant_mapping_count INTEGER;

BEGIN

    SELECT COUNT(*)

    INTO host_module_count

    FROM axionpro."Module"

    WHERE "ModuleCode"
          = 'HOST_DEFAULT_EMAIL_CONFIG';


    SELECT COUNT(*)

    INTO tenant_module_count

    FROM axionpro."Module"

    WHERE "ModuleCode"
          = 'TENANT_EMAIL_CONFIG';


    IF host_module_count <> 1 THEN

        RAISE EXCEPTION
        'Expected exactly one HOST_DEFAULT_EMAIL_CONFIG module. Found: %',
        host_module_count;

    END IF;


    IF tenant_module_count <> 1 THEN

        RAISE EXCEPTION
        'Expected exactly one TENANT_EMAIL_CONFIG module. Found: %',
        tenant_module_count;

    END IF;


    SELECT COUNT(*)

    INTO host_mapping_count

    FROM axionpro."ModuleOperationMapping"
        mapping

    INNER JOIN axionpro."Module"
        module

        ON module."Id"
           = mapping."ModuleId"

    WHERE module."ModuleCode"
          = 'HOST_DEFAULT_EMAIL_CONFIG'

      AND mapping."IsActive"
          = TRUE;


    SELECT COUNT(*)

    INTO tenant_mapping_count

    FROM axionpro."ModuleOperationMapping"
        mapping

    INNER JOIN axionpro."Module"
        module

        ON module."Id"
           = mapping."ModuleId"

    WHERE module."ModuleCode"
          = 'TENANT_EMAIL_CONFIG'

      AND mapping."IsActive"
          = TRUE;


    IF host_mapping_count = 0 THEN

        RAISE EXCEPTION
        'No CRUD Operation mapping found for HOST_DEFAULT_EMAIL_CONFIG. Check Operation master data.';

    END IF;


    IF tenant_mapping_count = 0 THEN

        RAISE EXCEPTION
        'No CRUD Operation mapping found for TENANT_EMAIL_CONFIG. Check Operation master data.';

    END IF;

END;
$$;


-- ============================================================================
-- SECTION 10
-- SAFE AUTO-INCREMENT / IDENTITY SYNCHRONIZATION
-- ============================================================================
--
-- IMPORTANT:
--
-- Empty table:
--     next ID = 1
--
-- Existing table:
--     next ID = MAX(Id) + 1
--
-- Existing production IDs kabhi backward reset nahi honge.
-- ============================================================================

DO
$$
DECLARE

    sequence_name TEXT;

    maximum_id BIGINT;

BEGIN


    -- ========================================================================
    -- DefaultEmailConfig
    -- ========================================================================

    sequence_name :=
        pg_get_serial_sequence
        (
            'axionpro."DefaultEmailConfig"',
            'Id'
        );


    IF sequence_name IS NOT NULL THEN

        SELECT COALESCE(MAX("Id"), 0)

        INTO maximum_id

        FROM axionpro."DefaultEmailConfig";


        IF maximum_id = 0 THEN

            PERFORM setval
            (
                sequence_name::regclass,
                1,
                FALSE
            );

        ELSE

            PERFORM setval
            (
                sequence_name::regclass,
                maximum_id,
                TRUE
            );

        END IF;

    END IF;



    -- ========================================================================
    -- Module
    -- ========================================================================

    sequence_name :=
        pg_get_serial_sequence
        (
            'axionpro."Module"',
            'Id'
        );


    IF sequence_name IS NOT NULL THEN

        SELECT COALESCE(MAX("Id"), 0)

        INTO maximum_id

        FROM axionpro."Module";


        IF maximum_id = 0 THEN

            PERFORM setval
            (
                sequence_name::regclass,
                1,
                FALSE
            );

        ELSE

            PERFORM setval
            (
                sequence_name::regclass,
                maximum_id,
                TRUE
            );

        END IF;

    END IF;



    -- ========================================================================
    -- ModuleOperationMapping
    -- ========================================================================

    sequence_name :=
        pg_get_serial_sequence
        (
            'axionpro."ModuleOperationMapping"',
            'Id'
        );


    IF sequence_name IS NOT NULL THEN

        SELECT COALESCE(MAX("Id"), 0)

        INTO maximum_id

        FROM axionpro."ModuleOperationMapping";


        IF maximum_id = 0 THEN

            PERFORM setval
            (
                sequence_name::regclass,
                1,
                FALSE
            );

        ELSE

            PERFORM setval
            (
                sequence_name::regclass,
                maximum_id,
                TRUE
            );

        END IF;

    END IF;

END;
$$;


-- ============================================================================
-- EVERYTHING SUCCESSFUL
-- ============================================================================

COMMIT;


-- ============================================================================
-- VERIFICATION 1
-- DEFAULT EMAIL CONFIGURATION
-- ============================================================================
--
-- Password / Secret intentionally SELECT nahi kiya gaya.
-- ============================================================================

SELECT

    "Id",

    "ConfigName",

    "SmtpHost",

    "SmtpPort",

    "SmtpUsername",

    "FromEmail",

    "FromName",

    "IsActive",

    "IsDefault",

    "CreatedDateTime",

    "UpdatedDateTime"

FROM axionpro."DefaultEmailConfig"

ORDER BY "Id";


-- ============================================================================
-- VERIFICATION 2
-- CONSOLIDATED MODULES WITH ALL CURRENT MODULE PROPERTIES
-- ============================================================================

SELECT

    "Id",

    "TenantId",

    "ModuleCode",

    "ModuleName",

    "DisplayName",

    "URLPath",

    "ParentModuleId",

    "IsLeafNode",

    "IsModuleDisplayInUI",

    "IsCommonMenu",

    "IsActive",

    "ImageIconWeb",

    "ImageIconMobile",

    "ItemPriority",

    "Remark",

    "AddedById",

    "AddedDateTime",

    "UpdatedById",

    "UpdatedDateTime",

    "ModuleScope"

FROM axionpro."Module"

WHERE "ModuleCode"
      IN
      (
          'HOST_DEFAULT_EMAIL_CONFIG',
          'HOST_TENANT_EMAIL_CONFIG',
          'TENANT_EMAIL_CONFIG',
          'HOST_EMAIL_TEMPLATE',
          'HOST_DEVICE_SETUP',
          'TENANT_DEVICE_SETUP',
          'HOST_INITIAL_DEVICE_CONFIGURATION',
          'TENANT_DEVICE_CONFIGURATION',
          'EMP_PASSWORD_MANAGEMENT'
      )

ORDER BY
    "ModuleScope",
    "Id";


-- ============================================================================
-- VERIFICATION 3
-- MODULE OPERATION MAPPINGS
-- ============================================================================

SELECT

    module."Id"
        AS "ModuleId",

    module."ModuleCode",

    module."ModuleName",

    module."ModuleScope",

    operation."Id"
        AS "OperationId",

    operation."OperationName",

    mapping."Priority",

    mapping."IsCommonItem",

    mapping."IsOperational",

    mapping."Remark",

    mapping."IsActive"

FROM axionpro."ModuleOperationMapping"
    mapping

INNER JOIN axionpro."Module"
    module

    ON module."Id"
       = mapping."ModuleId"

INNER JOIN axionpro."Operation"
    operation

    ON operation."Id"
       = mapping."OperationId"

WHERE module."ModuleCode"
      IN
      (
          'HOST_DEFAULT_EMAIL_CONFIG',
          'HOST_TENANT_EMAIL_CONFIG',
          'TENANT_EMAIL_CONFIG',
          'HOST_EMAIL_TEMPLATE',
          'HOST_DEVICE_SETUP',
          'TENANT_DEVICE_SETUP',
          'HOST_INITIAL_DEVICE_CONFIGURATION',
          'TENANT_DEVICE_CONFIGURATION',
          'EMP_PASSWORD_MANAGEMENT'
      )

ORDER BY

    module."ModuleScope",

    module."ModuleCode",

    mapping."Priority",

    operation."OperationName";


-- ============================================================================
-- VERIFICATION 4
-- TENANT PLATFORM FEATURE PLAN MAPPINGS
-- ============================================================================

SELECT

    plan_mapping.*,

    module."ModuleCode",

    module."DisplayName"

FROM axionpro."PlanModuleMapping"
    plan_mapping

INNER JOIN axionpro."Module"
    module

    ON module."Id"
       = plan_mapping."ModuleId"

WHERE module."ModuleCode"
      IN
      (
          'TENANT_EMAIL_CONFIG',
          'TENANT_DEVICE_SETUP',
          'TENANT_DEVICE_CONFIGURATION',
          'EMP_PASSWORD_MANAGEMENT'
      )

ORDER BY
    plan_mapping."SubscriptionPlanId",
    module."ModuleCode";
