-- ============================================================================
-- AxionPro Production - Consolidated Module and Operation Setup
-- Author      : Deepesh Gupta
-- Company     : Quecksilber Technologies
-- Role        : CEO
--
-- Purpose:
--   1. DefaultEmailConfig table create / upgrade.
--   2. Existing active TenantEmailConfig se default SMTP seed.
--   3. Email modules     : Host default, Host Tenant email, Tenant email,
--                          and Host email templates.
--   4. Device modules    : Host device setup, Tenant device setup, Host initial
--                          provisioning, and Tenant runtime configuration.
--   5. Device and work management : Tenant locations, attendance policies,
--                          employee-device enrollment, employee work setup,
--                          and Host card inventory permission modules.
--   6. Employee password : Child module, dedicated Reset Password operation,
--                          operation mapping, and inherited plan mappings.
--   7. Existing module / operation records ko normalize/update karna.
--   8. Host administration hierarchy and Host authorization baseline.
--   9. Bulk module planning is documented in BULK_MODULE_SEED_REFERENCE.md.
--      EmployeeType catalogue is maintained by SeedTenantEmployeeTypeModule.sql.
--   9. Identity / auto-increment sequence safely synchronize karna.
--
-- IMPORTANT:
--   * SMTP password/secret hard-code nahi kiya gaya hai.
--   * Host-Super-Admin (HostRole Id = 1) receives persisted permission rows for
--     every active Host-scope operational mapping. Runtime authorization always
--     uses the persisted HostRoleModuleAndPermission rows; there is no role
--     bypass in the request behaviours or MyMenu query.
--   * Host authorization data is deliberately rebuilt by this seed: old Host
--     users, roles, grants, and Host refresh tokens are removed, then the
--     identity sequences are restarted and the canonical Host user is inserted.
--   * Script re-run safe/idempotent rakhi gayi hai.
--   * Shared modules intentionally have TenantId = NULL; root modules
--     intentionally have ParentModuleId = NULL. Those two NULLs model scope
--     and hierarchy, not incomplete seed data.
-- ============================================================================


BEGIN;


-- ============================================================================
-- SECTION 1 : DEFAULT EMAIL CONFIGURATION TABLE
-- ============================================================================

CREATE TABLE IF NOT EXISTS axionpro."DefaultEmailConfig"
(
    "Id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    "ConfigName" CHARACTER VARYING(100) NOT NULL,

    "SmtpHost" CHARACTER VARYING(200) NOT NULL,

    "SmtpPort" INTEGER NOT NULL,

    "SmtpUsername" CHARACTER VARYING(200) NOT NULL,

    "SmtpPasswordEncrypted" CHARACTER VARYING(500) NOT NULL,

    "FromEmail" CHARACTER VARYING(200) NOT NULL,

    "FromName" CHARACTER VARYING(100) NOT NULL,

    "IsActive" BOOLEAN NOT NULL DEFAULT TRUE,

    "IsDefault" BOOLEAN NOT NULL DEFAULT FALSE,

    "SecrateKey" CHARACTER VARYING(500) NOT NULL,

    "CreatedDateTime"
        TIMESTAMP WITHOUT TIME ZONE
        NOT NULL
        DEFAULT CURRENT_TIMESTAMP,

    "UpdatedDateTime"
        TIMESTAMP WITHOUT TIME ZONE NULL
);


-- ============================================================================
-- SECTION 2 : SAFE TABLE UPGRADE
-- ============================================================================

ALTER TABLE axionpro."DefaultEmailConfig"
ADD COLUMN IF NOT EXISTS
    "IsDefault" BOOLEAN NOT NULL DEFAULT FALSE;


-- ============================================================================
-- SECTION 2B : IMMUTABLE MODULE PAGE COMPONENT KEY
-- ============================================================================
-- PageName is a stable Angular component-registration key, not a route. URLPath
-- may change when navigation changes; PageName must remain unchanged forever.
-- ============================================================================

ALTER TABLE axionpro."Module"
ADD COLUMN IF NOT EXISTS
    "PageName" CHARACTER VARYING(100) NULL;


-- ============================================================================
-- SECTION 2A : OPERATION AUDIT COLUMN STANDARDISATION
-- ============================================================================
-- The original schema used "UpdateDateTime" only on Operation.  All other
-- audit models use "UpdatedDateTime"; rename the physical column once so the
-- database, EF entity, API DTOs, and seed script share one contract.
DO
$$
DECLARE
    legacy_column_exists BOOLEAN;
    canonical_column_exists BOOLEAN;
BEGIN
    IF to_regclass('axionpro."Operation"') IS NULL THEN
        RAISE EXCEPTION 'Required table axionpro."Operation" does not exist.';
    END IF;

    SELECT EXISTS
    (
        SELECT 1
        FROM information_schema.columns
        WHERE table_schema = 'axionpro'
          AND table_name = 'Operation'
          AND column_name = 'UpdateDateTime'
    )
    INTO legacy_column_exists;

    SELECT EXISTS
    (
        SELECT 1
        FROM information_schema.columns
        WHERE table_schema = 'axionpro'
          AND table_name = 'Operation'
          AND column_name = 'UpdatedDateTime'
    )
    INTO canonical_column_exists;

    IF legacy_column_exists AND canonical_column_exists THEN
        RAISE EXCEPTION
            'axionpro."Operation" contains both "UpdateDateTime" and "UpdatedDateTime". Resolve the duplicate columns before running this script.';
    ELSIF legacy_column_exists THEN
        ALTER TABLE axionpro."Operation"
        RENAME COLUMN "UpdateDateTime" TO "UpdatedDateTime";
    ELSIF NOT canonical_column_exists THEN
        RAISE EXCEPTION
            'Audit column "UpdatedDateTime" is missing from axionpro."Operation".';
    END IF;
END;
$$;


-- ============================================================================
-- SMTP PORT VALIDATION
-- ============================================================================

DO
$$
BEGIN

    IF NOT EXISTS
    (
        SELECT 1
        FROM pg_constraint
        WHERE conname = 'CK_DefaultEmailConfig_SmtpPort'
          AND conrelid = 'axionpro."DefaultEmailConfig"'::regclass
    )
    THEN

        ALTER TABLE axionpro."DefaultEmailConfig"
        ADD CONSTRAINT "CK_DefaultEmailConfig_SmtpPort"
        CHECK ("SmtpPort" BETWEEN 1 AND 65535);

    END IF;

END;
$$;


-- ============================================================================
-- CONFIG NAME UNIQUE CONSTRAINT
-- ============================================================================

DO
$$
BEGIN

    IF NOT EXISTS
    (
        SELECT 1
        FROM pg_constraint
        WHERE conname = 'UX_DefaultEmailConfig_ConfigName'
          AND conrelid = 'axionpro."DefaultEmailConfig"'::regclass
    )
    THEN

        ALTER TABLE axionpro."DefaultEmailConfig"
        ADD CONSTRAINT "UX_DefaultEmailConfig_ConfigName"
        UNIQUE ("ConfigName");

    END IF;

END;
$$;


-- ============================================================================
-- ONLY ONE DEFAULT SMTP CONFIGURATION
-- ============================================================================

DROP INDEX IF EXISTS
axionpro."UX_DefaultEmailConfig_OneActive";


CREATE UNIQUE INDEX IF NOT EXISTS
"UX_DefaultEmailConfig_OneDefault"
ON axionpro."DefaultEmailConfig"
(
    "IsDefault"
)
WHERE "IsDefault" = TRUE;


-- ============================================================================
-- SECTION 3 : SEED DEFAULT EMAIL CONFIGURATION
-- ============================================================================
--
-- Latest complete active TenantEmailConfig configuration ko source banaya jayega.
--
-- Isliye production SQL me:
-- Password
-- Secret
-- SMTP Username
--
-- manually paste nahi karna padega.
-- ============================================================================

DO
$$
BEGIN

    INSERT INTO axionpro."DefaultEmailConfig"
    (
        "ConfigName",
        "SmtpHost",
        "SmtpPort",
        "SmtpUsername",
        "SmtpPasswordEncrypted",
        "FromEmail",
        "FromName",
        "IsActive",
        "IsDefault",
        "SecrateKey"
    )

    SELECT

        'DEFAULT_REGISTRATION_SMTP',

        BTRIM(configuration."SmtpHost"),

        configuration."SmtpPort",

        BTRIM(configuration."SmtpUsername"),

        COALESCE
        (
            NULLIF
            (
                BTRIM(configuration."SmtpPasswordEncrypted"),
                ''
            ),

            NULLIF
            (
                BTRIM(configuration."SecrateKey"),
                ''
            )
        ),

        BTRIM(configuration."FromEmail"),

        BTRIM(configuration."FromName"),

        TRUE,

        NOT EXISTS
        (
            SELECT 1

            FROM axionpro."DefaultEmailConfig"
                existingDefault

            WHERE existingDefault."IsDefault" = TRUE
        ),

        COALESCE
        (
            NULLIF
            (
                BTRIM(configuration."SecrateKey"),
                ''
            ),

            NULLIF
            (
                BTRIM(configuration."SmtpPasswordEncrypted"),
                ''
            )
        )

    FROM axionpro."TenantEmailConfig"
        configuration

    WHERE configuration."IsActive" = TRUE

      AND NULLIF
          (
              BTRIM(configuration."SmtpHost"),
              ''
          ) IS NOT NULL

      AND configuration."SmtpPort"
          BETWEEN 1 AND 65535

      AND NULLIF
          (
              BTRIM(configuration."SmtpUsername"),
              ''
          ) IS NOT NULL

      AND COALESCE
          (
              NULLIF
              (
                  BTRIM(configuration."SmtpPasswordEncrypted"),
                  ''
              ),

              NULLIF
              (
                  BTRIM(configuration."SecrateKey"),
                  ''
              )
          ) IS NOT NULL

      AND NULLIF
          (
              BTRIM(configuration."FromEmail"),
              ''
          ) IS NOT NULL

      AND NULLIF
          (
              BTRIM(configuration."FromName"),
              ''
          ) IS NOT NULL

    ORDER BY configuration."Id" DESC

    LIMIT 1


    ON CONFLICT ("ConfigName")

    DO UPDATE SET

        "SmtpHost"
            = EXCLUDED."SmtpHost",

        "SmtpPort"
            = EXCLUDED."SmtpPort",

        "SmtpUsername"
            = EXCLUDED."SmtpUsername",

        "SmtpPasswordEncrypted"
            = EXCLUDED."SmtpPasswordEncrypted",

        "FromEmail"
            = EXCLUDED."FromEmail",

        "FromName"
            = EXCLUDED."FromName",

        "IsActive"
            = TRUE,

        "SecrateKey"
            = EXCLUDED."SecrateKey",

        "UpdatedDateTime"
            = CURRENT_TIMESTAMP;


    IF NOT FOUND THEN

        RAISE EXCEPTION
        'No complete active TenantEmailConfig found. DefaultEmailConfig could not be seeded.';

    END IF;

END;
$$;


-- ============================================================================
-- DEFAULT CONFIG MARK
-- ============================================================================
--
-- Agar pehle se koi IsDefault = true nahi hai,
-- to DEFAULT_REGISTRATION_SMTP ko default bana diya jayega.
-- ============================================================================

UPDATE axionpro."DefaultEmailConfig"
SET
    "IsDefault" = TRUE,

    "UpdatedDateTime" = CURRENT_TIMESTAMP

WHERE "ConfigName" = 'DEFAULT_REGISTRATION_SMTP'

  AND "IsActive" = TRUE

  AND "IsDefault" = FALSE

  AND NOT EXISTS
  (
      SELECT 1

      FROM axionpro."DefaultEmailConfig"

      WHERE "IsDefault" = TRUE
  );


-- ============================================================================
-- SECTION 4
-- HOST MODULE : PLATFORM EMAIL DEFAULTS
-- ============================================================================
--
-- ModuleScope = 2
-- Host-scope platform module
--
-- Purpose:
-- New Tenant registration ke waqt selected/default SMTP configuration
-- TenantEmailConfig me copy hogi.
-- ============================================================================


-- ---------------------------------------------------------------------------
-- Existing module hai to usko complete/normalize karo.
-- ---------------------------------------------------------------------------

UPDATE axionpro."Module"

SET

    "TenantId" = NULL,

    "ModuleName"
        = 'Platform Email Defaults',

    "DisplayName"
        = 'Platform Email Defaults',

    "URLPath"
        = '/app/default-email-config',

    "ParentModuleId"
        = NULL,

    "IsLeafNode"
        = TRUE,

    "IsModuleDisplayInUI"
        = TRUE,

    "IsCommonMenu"
        = FALSE,

    "IsActive"
        = TRUE,

    "ImageIconWeb"
        = 'bi bi-envelope-gear',

    "ImageIconMobile"
        = 'mail-settings',

    "ItemPriority"
        = 410,

    "Remark"
        = 'Host-managed default SMTP profile copied when a tenant is registered.',

    "UpdatedById"
        = 1,

    "UpdatedDateTime"
        = CURRENT_TIMESTAMP,

    "ModuleScope"
        = 2

WHERE "ModuleCode"
    = 'HOST_DEFAULT_EMAIL_CONFIG';


-- ---------------------------------------------------------------------------
-- Existing module nahi hai to create karo.
-- Id explicitly nahi diya gaya hai.
-- PostgreSQL identity automatically next Id generate karega.
-- ---------------------------------------------------------------------------

INSERT INTO axionpro."Module"
(
    "TenantId",

    "ModuleCode",

    "ModuleName",

    "PageName",

    "DisplayName",

    "URLPath",

    "ParentModuleId",

    "IsLeafNode",

    "IsModuleDisplayInUI",

    "IsCommonMenu",

    "IsActive",

    "ImageIconWeb",

    "ImageIconMobile",

    "ItemPriority",

    "Remark",

    "AddedById",

    "AddedDateTime",

    "UpdatedById",

    "UpdatedDateTime",

    "ModuleScope"
)

SELECT

    NULL,

    'HOST_DEFAULT_EMAIL_CONFIG',

    'Platform Email Defaults',

    'platform-email-defaults',

    'Platform Email Defaults',

    '/app/default-email-config',

    NULL,

    TRUE,

    TRUE,

    FALSE,

    TRUE,

    'bi bi-envelope-gear',

    'mail-settings',

    410,

    'Host-managed default SMTP profile copied when a tenant is registered.',

    1,

    CURRENT_TIMESTAMP,

    NULL,

    NULL,

    2

WHERE NOT EXISTS
(
    SELECT 1

    FROM axionpro."Module"

    WHERE "ModuleCode"
        = 'HOST_DEFAULT_EMAIL_CONFIG'
);


-- ============================================================================
-- SECTION 5
-- TENANT MODULE : EMAIL DELIVERY SETTINGS
-- ============================================================================
--
-- ModuleScope = 1
--
-- APIs:
--
-- POST
-- /api/TenantEmailConfig/create
--
-- GET
-- /api/TenantEmailConfig/get-all
--
-- GET
-- /api/TenantEmailConfig/get-by-id/{id}
--
-- POST
-- /api/TenantEmailConfig/update
--
-- DELETE
-- /api/TenantEmailConfig/delete/{id}
--
-- ============================================================================


-- ---------------------------------------------------------------------------
-- Existing module normalize/update.
-- ---------------------------------------------------------------------------

UPDATE axionpro."Module"

SET

    "TenantId"
        = NULL,

    "ModuleName"
        = 'Email Delivery Settings',

    "DisplayName"
        = 'Email Settings',

    "URLPath"
        = '/app/tenant-email-config',

    "ParentModuleId"
        = NULL,

    "IsLeafNode"
        = TRUE,

    "IsModuleDisplayInUI"
        = TRUE,

    "IsCommonMenu"
        = FALSE,

    "IsActive"
        = TRUE,

    "ImageIconWeb"
        = 'bi bi-envelope-at',

    "ImageIconMobile"
        = 'mail',

    "ItemPriority"
        = 410,

    "Remark"
        = 'Tenant-owned SMTP settings for authorised transactional and notification email delivery.',

    "UpdatedById"
        = 1,

    "UpdatedDateTime"
        = CURRENT_TIMESTAMP,

    "ModuleScope"
        = 1

WHERE "ModuleCode"
    = 'TENANT_EMAIL_CONFIG';


-- ---------------------------------------------------------------------------
-- Create when missing.
-- ---------------------------------------------------------------------------

INSERT INTO axionpro."Module"
(
    "TenantId",

    "ModuleCode",

    "ModuleName",

    "PageName",

    "DisplayName",

    "URLPath",

    "ParentModuleId",

    "IsLeafNode",

    "IsModuleDisplayInUI",

    "IsCommonMenu",

    "IsActive",

    "ImageIconWeb",

    "ImageIconMobile",

    "ItemPriority",

    "Remark",

    "AddedById",

    "AddedDateTime",

    "UpdatedById",

    "UpdatedDateTime",

    "ModuleScope"
)

SELECT

    NULL,

    'TENANT_EMAIL_CONFIG',

    'Email Delivery Settings',

    'email-delivery-settings',

    'Email Settings',

    '/app/tenant-email-config',

    NULL,

    TRUE,

    TRUE,

    FALSE,

    TRUE,

    'bi bi-envelope-at',

    'mail',

    410,

    'Tenant-owned SMTP settings for authorised transactional and notification email delivery.',

    1,

    CURRENT_TIMESTAMP,

    NULL,

    NULL,

    1

WHERE NOT EXISTS
(
    SELECT 1

    FROM axionpro."Module"

    WHERE "ModuleCode"
        = 'TENANT_EMAIL_CONFIG'
);


-- ============================================================================
-- SECTION 6
-- HOST DEFAULT EMAIL CONFIG MODULE OPERATION MAPPING
-- ============================================================================
--
-- Existing Operation master reuse hoga.
--
-- Supported operation names:
--
-- View / Read
-- Create / Add
-- Update / Edit
-- Delete
--
-- ============================================================================

INSERT INTO axionpro."ModuleOperationMapping"
(
    "ModuleId",

    "OperationId",

    "IsCommonItem",

    "IsOperational",

    "Priority",

    "Remark",

    "IsActive",

    "AddedById",

    "AddedDateTime"
)

SELECT

    module."Id",

    operation."Id",

    FALSE,

    TRUE,

    CASE

        WHEN LOWER(BTRIM(operation."OperationName"))
             IN ('view', 'read')
            THEN 1

        WHEN LOWER(BTRIM(operation."OperationName"))
             IN ('create', 'add')
            THEN 2

        WHEN LOWER(BTRIM(operation."OperationName"))
             IN ('update', 'edit')
            THEN 3

        WHEN LOWER(BTRIM(operation."OperationName"))
             = 'delete'
            THEN 4

        ELSE 10

    END,

    CASE

        WHEN LOWER(BTRIM(operation."OperationName"))
             IN ('view', 'read')

            THEN
            'View Host default email configuration.'

        WHEN LOWER(BTRIM(operation."OperationName"))
             IN ('create', 'add')

            THEN
            'Create Host default email configuration.'

        WHEN LOWER(BTRIM(operation."OperationName"))
             IN ('update', 'edit')

            THEN
            'Update Host default email configuration.'

        WHEN LOWER(BTRIM(operation."OperationName"))
             = 'delete'

            THEN
            'Delete Host default email configuration.'

        ELSE
            'Host default email configuration operation.'

    END,

    TRUE,

    1,

    CURRENT_TIMESTAMP

FROM axionpro."Module" module

INNER JOIN axionpro."Operation" operation

    ON LOWER(BTRIM(operation."OperationName"))

       IN
       (
           'view',
           'read',
           'create',
           'add',
           'update',
           'edit',
           'delete'
       )

WHERE module."ModuleCode"
      = 'HOST_DEFAULT_EMAIL_CONFIG'

  AND operation."IsActive"
      = TRUE

  AND NOT EXISTS
  (
      SELECT 1

      FROM axionpro."ModuleOperationMapping"
          existingMapping

      WHERE existingMapping."ModuleId"
            = module."Id"

        AND existingMapping."OperationId"
            = operation."Id"
  );


-- ============================================================================
-- SECTION 7
-- TENANT EMAIL CONFIG MODULE OPERATION MAPPING
-- ============================================================================

INSERT INTO axionpro."ModuleOperationMapping"
(
    "ModuleId",

    "OperationId",

    "IsCommonItem",

    "IsOperational",

    "Priority",

    "Remark",

    "IsActive",

    "AddedById",

    "AddedDateTime"
)

SELECT

    module."Id",

    operation."Id",

    FALSE,

    TRUE,

    CASE

        WHEN LOWER(BTRIM(operation."OperationName"))
             IN ('view', 'read')
            THEN 1

        WHEN LOWER(BTRIM(operation."OperationName"))
             IN ('create', 'add')
            THEN 2

        WHEN LOWER(BTRIM(operation."OperationName"))
             IN ('update', 'edit')
            THEN 3

        WHEN LOWER(BTRIM(operation."OperationName"))
             = 'delete'
            THEN 4

        ELSE 10

    END,

    CASE

        WHEN LOWER(BTRIM(operation."OperationName"))
             IN ('view', 'read')

            THEN
            'View Tenant email configuration.'

        WHEN LOWER(BTRIM(operation."OperationName"))
             IN ('create', 'add')

            THEN
            'Create Tenant email configuration.'

        WHEN LOWER(BTRIM(operation."OperationName"))
             IN ('update', 'edit')

            THEN
            'Update Tenant email configuration.'

        WHEN LOWER(BTRIM(operation."OperationName"))
             = 'delete'

            THEN
            'Delete Tenant email configuration.'

        ELSE
            'Tenant email configuration operation.'

    END,

    TRUE,

    1,

    CURRENT_TIMESTAMP

FROM axionpro."Module" module

INNER JOIN axionpro."Operation" operation

    ON LOWER(BTRIM(operation."OperationName"))

       IN
       (
           'view',
           'read',
           'create',
           'add',
           'update',
           'edit',
           'delete'
       )

WHERE module."ModuleCode"
      = 'TENANT_EMAIL_CONFIG'

  AND operation."IsActive"
      = TRUE

  AND NOT EXISTS
  (
      SELECT 1

      FROM axionpro."ModuleOperationMapping"
          existingMapping

      WHERE existingMapping."ModuleId"
            = module."Id"

        AND existingMapping."OperationId"
            = operation."Id"
  );


-- ============================================================================
-- SECTION 8
-- NORMALIZE EXISTING MODULE OPERATION MAPPINGS
-- ============================================================================

UPDATE axionpro."ModuleOperationMapping"
    mapping

SET

    "IsCommonItem"
        = FALSE,

    "IsOperational"
        = TRUE,

    "Priority"
        =
        CASE

            WHEN LOWER(BTRIM(operation."OperationName"))
                 IN ('view', 'read')
                THEN 1

            WHEN LOWER(BTRIM(operation."OperationName"))
                 IN ('create', 'add')
                THEN 2

            WHEN LOWER(BTRIM(operation."OperationName"))
                 IN ('update', 'edit')
                THEN 3

            WHEN LOWER(BTRIM(operation."OperationName"))
                 = 'delete'
                THEN 4

            ELSE mapping."Priority"

        END,

    "Remark"
        =
        CASE

            WHEN module."ModuleCode"
                 = 'HOST_DEFAULT_EMAIL_CONFIG'

                 AND LOWER(BTRIM(operation."OperationName"))
                     IN ('view', 'read')

                THEN
                'View Host default email configuration.'


            WHEN module."ModuleCode"
                 = 'HOST_DEFAULT_EMAIL_CONFIG'

                 AND LOWER(BTRIM(operation."OperationName"))
                     IN ('create', 'add')

                THEN
                'Create Host default email configuration.'


            WHEN module."ModuleCode"
                 = 'HOST_DEFAULT_EMAIL_CONFIG'

                 AND LOWER(BTRIM(operation."OperationName"))
                     IN ('update', 'edit')

                THEN
                'Update Host default email configuration.'


            WHEN module."ModuleCode"
                 = 'HOST_DEFAULT_EMAIL_CONFIG'

                 AND LOWER(BTRIM(operation."OperationName"))
                     = 'delete'

                THEN
                'Delete Host default email configuration.'


            WHEN module."ModuleCode"
                 = 'TENANT_EMAIL_CONFIG'

                 AND LOWER(BTRIM(operation."OperationName"))
                     IN ('view', 'read')

                THEN
                'View Tenant email configuration.'


            WHEN module."ModuleCode"
                 = 'TENANT_EMAIL_CONFIG'

                 AND LOWER(BTRIM(operation."OperationName"))
                     IN ('create', 'add')

                THEN
                'Create Tenant email configuration.'


            WHEN module."ModuleCode"
                 = 'TENANT_EMAIL_CONFIG'

                 AND LOWER(BTRIM(operation."OperationName"))
                     IN ('update', 'edit')

                THEN
                'Update Tenant email configuration.'


            WHEN module."ModuleCode"
                 = 'TENANT_EMAIL_CONFIG'

                 AND LOWER(BTRIM(operation."OperationName"))
                     = 'delete'

                THEN
                'Delete Tenant email configuration.'


            ELSE mapping."Remark"

        END,

    "IsActive"
        = TRUE

FROM axionpro."Module"
    module,

     axionpro."Operation"
    operation

WHERE mapping."ModuleId"
      = module."Id"

  AND mapping."OperationId"
      = operation."Id"

  AND module."ModuleCode"
      IN
      (
          'HOST_DEFAULT_EMAIL_CONFIG',
          'TENANT_EMAIL_CONFIG'
      );


-- ============================================================================
-- SECTION 8A
-- CONSOLIDATED HOST / TENANT EMAIL AND DEVICE MODULES
-- ============================================================================
-- This transaction-local seed replaces the former standalone module seed files.
-- ModuleCode is an immutable permission contract; ModuleName/DisplayName are
-- the professional labels presented to administrators and end users.
-- ItemPriority is ascending within each parent/scope. A negative priority is
-- reserved for terminal Common-menu items such as Sign out.
-- It drives module normalization and standard CRUD operation mappings.
-- ============================================================================

-- Host administration is a real Host-scope parent module.  Its children are
-- the pages visible in the Host UI for Host users, roles, role permissions,
-- modules, submodules, operations, mappings, and subscriptions.
UPDATE axionpro."Module"
SET
    "TenantId" = NULL,
    "ModuleName" = 'Host-Management',
    "PageName" = COALESCE("PageName", 'host-management'),
    "DisplayName" = 'Host Management',
    "URLPath" = NULL,
    "ParentModuleId" = NULL,
    "IsLeafNode" = FALSE,
    "IsModuleDisplayInUI" = TRUE,
    "IsCommonMenu" = FALSE,
    "IsActive" = TRUE,
    "ImageIconWeb" = 'bi bi-shield-lock',
    "ImageIconMobile" = 'admin-panel-settings',
    "ItemPriority" = 100,
    "Remark" = 'Host-only administration for users, roles, permissions, modules, operations, mappings, and subscriptions.',
    "AddedById" = COALESCE("AddedById", 1),
    "AddedDateTime" = COALESCE("AddedDateTime", CURRENT_TIMESTAMP),
    "UpdatedById" = 1,
    "UpdatedDateTime" = CURRENT_TIMESTAMP,
    "ModuleScope" = 2
WHERE "ModuleCode" = 'HOST_MANAGEMENT';

INSERT INTO axionpro."Module"
(
    "TenantId", "ModuleCode", "ModuleName", "PageName", "DisplayName", "URLPath",
    "ParentModuleId", "IsLeafNode", "IsModuleDisplayInUI", "IsCommonMenu",
    "IsActive", "ImageIconWeb", "ImageIconMobile", "ItemPriority", "Remark",
    "AddedById", "AddedDateTime", "UpdatedById", "UpdatedDateTime", "ModuleScope"
)
SELECT
    NULL,
    'HOST_MANAGEMENT',
    'Host-Management',
    'host-management',
    'Host Management',
    NULL,
    NULL,
    FALSE,
    TRUE,
    FALSE,
    TRUE,
    'bi bi-shield-lock',
    'admin-panel-settings',
    100,
    'Host-only administration for users, roles, permissions, modules, operations, mappings, and subscriptions.',
    1,
    CURRENT_TIMESTAMP,
    1,
    CURRENT_TIMESTAMP,
    2
WHERE NOT EXISTS
(
    SELECT 1
    FROM axionpro."Module"
    WHERE "ModuleCode" = 'HOST_MANAGEMENT'
);

-- Tenant RFID Management is the Host-scope parent for card inventory.  The
-- parent is navigation-only; all CRUD operations remain bound to its Card
-- Inventory child module.
UPDATE axionpro."Module"
SET
    "TenantId" = NULL,
    "ModuleName" = 'Host-Tenant-RFID-Management',
    "PageName" = 'tenant-rfid-management',
    "DisplayName" = 'Tenant RFID Management',
    "URLPath" = NULL,
    "ParentModuleId" = NULL,
    "IsLeafNode" = FALSE,
    "IsModuleDisplayInUI" = TRUE,
    "IsCommonMenu" = FALSE,
    "IsActive" = TRUE,
    "ImageIconWeb" = 'bi bi-broadcast-pin',
    "ImageIconMobile" = 'contactless',
    "ItemPriority" = 525,
    "Remark" = 'Host management of tenant RFID cards and card inventory.',
    "AddedById" = COALESCE("AddedById", 1),
    "AddedDateTime" = COALESCE("AddedDateTime", CURRENT_TIMESTAMP),
    "UpdatedById" = 1,
    "UpdatedDateTime" = CURRENT_TIMESTAMP,
    "ModuleScope" = 2
WHERE "ModuleCode" = 'HOST_TENANT_RFID_MANAGEMENT';

INSERT INTO axionpro."Module"
(
    "TenantId", "ModuleCode", "ModuleName", "PageName", "DisplayName", "URLPath",
    "ParentModuleId", "IsLeafNode", "IsModuleDisplayInUI", "IsCommonMenu",
    "IsActive", "ImageIconWeb", "ImageIconMobile", "ItemPriority", "Remark",
    "AddedById", "AddedDateTime", "UpdatedById", "UpdatedDateTime", "ModuleScope"
)
SELECT
    NULL,
    'HOST_TENANT_RFID_MANAGEMENT',
    'Host-Tenant-RFID-Management',
    'tenant-rfid-management',
    'Tenant RFID Management',
    NULL,
    NULL,
    FALSE,
    TRUE,
    FALSE,
    TRUE,
    'bi bi-broadcast-pin',
    'contactless',
    525,
    'Host management of tenant RFID cards and card inventory.',
    1,
    CURRENT_TIMESTAMP,
    1,
    CURRENT_TIMESTAMP,
    2
WHERE NOT EXISTS
(
    SELECT 1
    FROM axionpro."Module"
    WHERE "ModuleCode" = 'HOST_TENANT_RFID_MANAGEMENT'
);

CREATE TEMPORARY TABLE module_seed
(
    "ModuleCode" CHARACTER VARYING(100) PRIMARY KEY,
    "ModuleName" CHARACTER VARYING(200) NOT NULL,
    "PageName" CHARACTER VARYING(100) NOT NULL,
    "DisplayName" CHARACTER VARYING(200) NOT NULL,
    "URLPath" CHARACTER VARYING(500) NOT NULL,
    "ParentModuleCode" CHARACTER VARYING(100) NULL,
    "IsModuleDisplayInUI" BOOLEAN NOT NULL,
    "ImageIconWeb" CHARACTER VARYING(100) NOT NULL,
    "ImageIconMobile" CHARACTER VARYING(100) NOT NULL,
    "ModuleScope" SMALLINT NOT NULL,
    "ItemPriority" INTEGER NOT NULL,
    "Remark" CHARACTER VARYING(1000) NOT NULL
)
ON COMMIT DROP;

-- Employee management child modules are part of the existing EMP_MGMT menu.
-- Check this once before resolving ParentModuleId below so a partial or
-- incorrectly scoped installation cannot silently create root-level modules.
DO
$$
DECLARE
    employee_parent_count INTEGER;
BEGIN
    SELECT COUNT(*)
    INTO employee_parent_count
    FROM axionpro."Module"
    WHERE "ModuleCode" = 'EMP_MGMT'
      AND "ParentModuleId" IS NULL
      AND "IsLeafNode" = FALSE
      AND "ModuleScope" = 1;

    IF employee_parent_count <> 1 THEN
        RAISE EXCEPTION
            'Expected exactly one Tenant-scope EMP_MGMT parent Module, found %. Cannot seed employee device and work-management modules.',
            employee_parent_count;
    END IF;
END;
$$;

INSERT INTO module_seed
(
    "ModuleCode", "ModuleName", "PageName", "DisplayName", "URLPath",
    "ParentModuleCode", "IsModuleDisplayInUI", "ImageIconWeb", "ImageIconMobile",
    "ModuleScope", "ItemPriority", "Remark"
)
VALUES
(
    'HOST_DEFAULT_EMAIL_CONFIG',
    'Platform Email Defaults',
    'platform-email-defaults',
    'Platform Email Defaults',
    '/app/default-email-config',
    NULL,
    TRUE,
    'bi bi-envelope-gear',
    'mail-settings',
    2,
    410,
    'Host-managed default SMTP profile copied when a tenant is registered.'
),
(
    'HOST_USERS',
    'Host Users',
    'host-users',
    'Users',
    '/app/host-users',
    'HOST_MANAGEMENT',
    TRUE,
    'bi bi-people',
    'people',
    2,
    110,
    'Creates and manages authenticated Host users and their assigned Host roles.'
),
(
    'HOST_ROLES',
    'Host Roles',
    'host-roles',
    'Roles',
    '/app/host-roles',
    'HOST_MANAGEMENT',
    TRUE,
    'bi bi-shield-check',
    'verified-user',
    2,
    120,
    'Creates and manages Host roles used by the Host authorization model.'
),
(
    'HOST_ROLE_PERMISSIONS',
    'Host Role Permissions',
    'host-role-permissions',
    'Role Permissions',
    '/app/host-roles/permissions',
    'HOST_MANAGEMENT',
    TRUE,
    'bi bi-check2-square',
    'rule',
    2,
    130,
    'Assigns active Host module-operation permissions to a Host role.'
),
(
    'HOST_MODULES',
    'Host Modules',
    'host-modules',
    'Modules',
    '/app/modules',
    'HOST_MANAGEMENT',
    TRUE,
    'bi bi-grid-3x3-gap',
    'apps',
    2,
    140,
    'Maintains Host-scope parent modules and their presentation metadata.'
),
(
    'HOST_SUBMODULES',
    'Host Submodules',
    'host-submodules',
    'Submodules',
    '/app/modules/sub-modules',
    'HOST_MANAGEMENT',
    TRUE,
    'bi bi-diagram-3',
    'account-tree',
    2,
    150,
    'Maintains Host-scope child modules beneath a Host parent module.'
),
(
    'HOST_OPERATIONS',
    'Host Operations',
    'host-operations',
    'Operations',
    '/app/modules/operations',
    'HOST_MANAGEMENT',
    TRUE,
    'bi bi-lightning-charge',
    'bolt',
    2,
    160,
    'Maintains reusable Host operations and their UI/audit metadata.'
),
(
    'HOST_MODULE_OPERATIONS',
    'Host Module Operations',
    'host-module-operations',
    'Module Operations',
    '/app/modules/module-operations',
    'HOST_MANAGEMENT',
    TRUE,
    'bi bi-link-45deg',
    'link',
    2,
    170,
    'Maps active Host modules to active operations used by MyMenu and role permissions.'
),
(
    'HOST_SUBSCRIPTIONS',
    'Host Subscriptions',
    'host-subscriptions',
    'Subscriptions',
    '/app/subscriptions',
    'HOST_MANAGEMENT',
    TRUE,
    'bi bi-credit-card-2-front',
    'subscriptions',
    2,
    180,
    'Manages Host-owned subscription plans and tenant plan assignment.'
),
(
    'TENANT_EMAIL_CONFIG',
    'Email Delivery Settings',
    'email-delivery-settings',
    'Email Settings',
    '/app/tenant-email-config',
    NULL,
    TRUE,
    'bi bi-envelope-at',
    'mail',
    1,
    410,
    'Tenant-owned SMTP settings for authorised transactional and notification email delivery.'
),
(
    'HOST_TENANT_EMAIL_CONFIG',
    'Tenant Email Administration',
    'tenant-email-administration',
    'Tenant Email Administration',
    '/app/tenants/tenant-email-config',
    NULL,
    TRUE,
    'bi bi-envelope-at',
    'mail',
    2,
    420,
    'Host administration of a selected tenant''s SMTP configuration.'
),
(
    'HOST_EMAIL_TEMPLATE',
    'Email Template Library',
    'email-templates',
    'Email Templates',
    '/app/email-templates',
    NULL,
    TRUE,
    'bi bi-envelope',
    'mail',
    2,
    430,
    'Host-managed reusable templates for platform email communication.'
),
(
    'HOST_DEVICE_SETUP',
    'Device Catalogue',
    'device-catalogue',
    'Device Catalogue',
    '/app/device-masters',
    NULL,
    TRUE,
    'bi bi-cpu',
    'memory',
    2,
    510,
    'Host-managed device models, hardware capabilities, and supported transport profiles.'
),
(
    'TENANT_DEVICE_SETUP',
    'Installed Devices',
    'installed-devices',
    'Installed Devices',
    '/app/tenant-devices',
    NULL,
    TRUE,
    'bi bi-hdd-network',
    'devices',
    1,
    510,
    'Tenant device installation, location assignment, activation, and lifecycle management.'
),
(
    'HOST_INITIAL_DEVICE_CONFIGURATION',
    'Device Provisioning',
    'device-provisioning',
    'Device Provisioning',
    '/app/device-masters',
    NULL,
    FALSE,
    'bi bi-router',
    'router',
    2,
    520,
    'Host-only permission for issuing one-time device bootstrap URLs from the device onboarding flow.'
),
(
    'TENANT_DEVICE_CONFIGURATION',
    'Device Connectivity',
    'device-connectivity',
    'Device Connectivity',
    '/app/tenant-device-configurations',
    NULL,
    TRUE,
    'bi bi-sliders',
    'settings',
    1,
    520,
    'Tenant-admin configuration of device connectivity, gateway rotation, heartbeat, runtime settings, and reboot.'
),
(
    'HOST_TENANT_CARD_INVENTORY',
    'Host Tenant Card Inventory',
    'tenant-card-inventory',
    'Card Inventory',
    '/app/tenant-card-inventory',
    'HOST_TENANT_RFID_MANAGEMENT',
    TRUE,
    'bi bi-credit-card',
    'credit-card',
    2,
    530,
    'Host-only procurement, tax, issue, and lifecycle inventory for Tenant-issued physical access cards.'
),
(
    'TENANT_LOCATIONS',
    'Tenant Locations',
    'tenant-locations',
    'Locations',
    '/app/tenant-locations',
    NULL,
    TRUE,
    'bi bi-geo-alt',
    'location-on',
    1,
    500,
    'Tenant-owned office, client-site, and remote-work locations used by devices, employee assignments, and attendance rules.'
),
(
    'TENANT_ATTENDANCE_POLICIES',
    'Tenant Attendance Policies',
    'attendance-policies',
    'Attendance Policies',
    '/app/attendance-policies',
    NULL,
    TRUE,
    'bi bi-calendar2-check',
    'fact-check',
    1,
    505,
    'Tenant-owned rules that define allowed biometric, mobile, web, manual, office, and work-from-home attendance modes.'
),
(
    'EMP_DEVICES',
    'Employee Device Enrollments',
    'employee-device-enrollment',
    'Employee Device Enrollments',
    '/employees/device-enrollment',
    'EMP_MGMT',
    TRUE,
    'bi bi-person-vcard',
    'badge',
    1,
    50,
    'Maps an employee to authorised Tenant devices and queues the employee user, face, card, PIN, and access-window changes.'
),
(
    'EMP_WORK_LOCATIONS',
    'Employee Work Locations',
    'employee-work-locations',
    'Employee Work Locations',
    '/employees/work-locations',
    'EMP_MGMT',
    TRUE,
    'bi bi-buildings',
    'business',
    1,
    60,
    'Assigns an employee to one or more Tenant locations with effective dates, primary-location status, and attendance eligibility.'
),
(
    'EMP_WORK_ARRANGEMENT',
    'Employee Work Arrangements',
    'employee-work-arrangements',
    'Employee Work Arrangements',
    '/employees/work-arrangements',
    'EMP_MGMT',
    TRUE,
    'bi bi-calendar-week',
    'calendar-month',
    1,
    70,
    'Defines an employee''s long-running office, remote, hybrid, or work-from-home attendance arrangement.'
),
(
    'EMP_WORK_PATTERN',
    'Employee Work Patterns',
    'employee-work-patterns',
    'Employee Work Patterns',
    '/employees/work-patterns',
    'EMP_MGMT',
    TRUE,
    'bi bi-calendar3-range',
    'date-range',
    1,
    80,
    'Defines recurring weekday work patterns and applicable location context beneath an employee work arrangement.'
),
(
    'EMP_OVERRIDES',
    'Employee Work Mode Overrides',
    'employee-work-mode-overrides',
    'Employee Work Mode Overrides',
    '/employees/work-mode-overrides',
    'EMP_MGMT',
    TRUE,
    'bi bi-calendar-event',
    'event-repeat',
    1,
    90,
    'Records a time-bound exception to an employee''s normal work arrangement without rewriting the standing arrangement.'
);

UPDATE axionpro."Module" module
SET
    "TenantId" = NULL,
    "ModuleName" = seed."ModuleName",
    "DisplayName" = seed."DisplayName",
    "URLPath" = seed."URLPath",
    "ParentModuleId" = parent."Id",
    "IsLeafNode" = TRUE,
    "IsModuleDisplayInUI" = seed."IsModuleDisplayInUI",
    "IsCommonMenu" = FALSE,
    "IsActive" = TRUE,
    "ImageIconWeb" = seed."ImageIconWeb",
    "ImageIconMobile" = seed."ImageIconMobile",
    "ItemPriority" = seed."ItemPriority",
    "Remark" = seed."Remark",
    "AddedById" = COALESCE(module."AddedById", 1),
    "AddedDateTime" = COALESCE(module."AddedDateTime", CURRENT_TIMESTAMP),
    "UpdatedById" = 1,
    "UpdatedDateTime" = CURRENT_TIMESTAMP,
    "ModuleScope" = seed."ModuleScope"
FROM module_seed seed
LEFT JOIN axionpro."Module" parent
    ON parent."ModuleCode" = seed."ParentModuleCode"
   AND parent."ParentModuleId" IS NULL
   AND parent."IsLeafNode" = FALSE
   AND parent."ModuleScope" = seed."ModuleScope"
WHERE module."ModuleCode" = seed."ModuleCode";

INSERT INTO axionpro."Module"
(
    "TenantId", "ModuleCode", "ModuleName", "PageName", "DisplayName", "URLPath",
    "ParentModuleId", "IsLeafNode", "IsModuleDisplayInUI", "IsCommonMenu",
    "IsActive", "ImageIconWeb", "ImageIconMobile", "ItemPriority", "Remark",
    "AddedById", "AddedDateTime", "UpdatedById", "UpdatedDateTime", "ModuleScope"
)
SELECT
    NULL,
    seed."ModuleCode",
    seed."ModuleName",
    seed."PageName",
    seed."DisplayName",
    seed."URLPath",
    parent."Id",
    TRUE,
    seed."IsModuleDisplayInUI",
    FALSE,
    TRUE,
    seed."ImageIconWeb",
    seed."ImageIconMobile",
    seed."ItemPriority",
    seed."Remark",
    1,
    CURRENT_TIMESTAMP,
    1,
    CURRENT_TIMESTAMP,
    seed."ModuleScope"
FROM module_seed seed
LEFT JOIN axionpro."Module" parent
    ON parent."ModuleCode" = seed."ParentModuleCode"
   AND parent."ParentModuleId" IS NULL
   AND parent."IsLeafNode" = FALSE
   AND parent."ModuleScope" = seed."ModuleScope"
WHERE NOT EXISTS
(
    SELECT 1
    FROM axionpro."Module" existing
    WHERE existing."ModuleCode" = seed."ModuleCode"
)
  AND (seed."ParentModuleCode" IS NULL OR parent."Id" IS NOT NULL);

-- The module seed consumes the platform-wide CRUD actions.  The Operation
-- master may have been deployed before this script, so create a missing
-- semantic action only when neither supported spelling exists, then ensure
-- every action used by these menus has complete labels, icon, type, and audit
-- metadata. OperationType values are the established OperationType enum:
-- Add=1, Update=2, Delete=3, View=4.
INSERT INTO axionpro."Operation"
(
    "OperationName", "Remark", "OperationType", "IsActive",
    "AddedById", "AddedDateTime", "UpdatedById", "UpdatedDateTime", "IconImage"
)
SELECT seed."OperationName", seed."Remark", seed."OperationType", TRUE,
       1, CURRENT_TIMESTAMP, 1, CURRENT_TIMESTAMP, seed."IconImage"
FROM
(
    VALUES
        ('View',   'View permitted records and details.', 4, 'eye'),
        ('Create', 'Create a permitted record or queue a new request.', 1, 'plus-circle'),
        ('Update', 'Update a permitted record or apply an approved change.', 2, 'pencil-square'),
        ('Delete', 'Soft-delete or remove a permitted record.', 3, 'trash3')
) AS seed("OperationName", "Remark", "OperationType", "IconImage")
WHERE NOT EXISTS
(
    SELECT 1
    FROM axionpro."Operation" existing
    WHERE
        (seed."OperationName" = 'View' AND LOWER(BTRIM(existing."OperationName")) IN ('view', 'read'))
        OR (seed."OperationName" = 'Create' AND LOWER(BTRIM(existing."OperationName")) IN ('create', 'add'))
        OR (seed."OperationName" = 'Update' AND LOWER(BTRIM(existing."OperationName")) IN ('update', 'edit'))
        OR (seed."OperationName" = 'Delete' AND LOWER(BTRIM(existing."OperationName")) = 'delete')
);

UPDATE axionpro."Operation" operation
SET
    "Remark" = CASE
        WHEN LOWER(BTRIM(operation."OperationName")) IN ('view', 'read')
            THEN 'View permitted records and details.'
        WHEN LOWER(BTRIM(operation."OperationName")) IN ('create', 'add')
            THEN 'Create a permitted record or queue a new request.'
        WHEN LOWER(BTRIM(operation."OperationName")) IN ('update', 'edit')
            THEN 'Update a permitted record or apply an approved change.'
        WHEN LOWER(BTRIM(operation."OperationName")) = 'delete'
            THEN 'Soft-delete or remove a permitted record.'
        ELSE operation."Remark"
    END,
    "OperationType" = CASE
        WHEN LOWER(BTRIM(operation."OperationName")) IN ('view', 'read') THEN 4
        WHEN LOWER(BTRIM(operation."OperationName")) IN ('create', 'add') THEN 1
        WHEN LOWER(BTRIM(operation."OperationName")) IN ('update', 'edit') THEN 2
        WHEN LOWER(BTRIM(operation."OperationName")) = 'delete' THEN 3
        ELSE operation."OperationType"
    END,
    "IconImage" = CASE
        WHEN LOWER(BTRIM(operation."OperationName")) IN ('view', 'read') THEN 'eye'
        WHEN LOWER(BTRIM(operation."OperationName")) IN ('create', 'add') THEN 'plus-circle'
        WHEN LOWER(BTRIM(operation."OperationName")) IN ('update', 'edit') THEN 'pencil-square'
        WHEN LOWER(BTRIM(operation."OperationName")) = 'delete' THEN 'trash3'
        ELSE operation."IconImage"
    END,
    "IsActive" = TRUE,
    "AddedById" = COALESCE(operation."AddedById", 1),
    "AddedDateTime" = COALESCE(operation."AddedDateTime", CURRENT_TIMESTAMP),
    "UpdatedById" = 1,
    "UpdatedDateTime" = CURRENT_TIMESTAMP
WHERE LOWER(BTRIM(operation."OperationName")) IN
      ('view', 'read', 'create', 'add', 'update', 'edit', 'delete');

INSERT INTO axionpro."ModuleOperationMapping"
(
    "ModuleId", "OperationId", "PageURL", "IconURL", "IsCommonItem",
    "IsOperational", "Priority", "Remark", "IsActive", "AddedById", "AddedDateTime"
)
SELECT
    module."Id",
    operation."Id",
    module."URLPath",
    COALESCE(NULLIF(BTRIM(operation."IconImage"), ''), module."ImageIconWeb"),
    FALSE,
    TRUE,
    CASE
        WHEN LOWER(BTRIM(operation."OperationName")) IN ('view', 'read') THEN 10
        WHEN LOWER(BTRIM(operation."OperationName")) IN ('create', 'add') THEN 20
        WHEN LOWER(BTRIM(operation."OperationName")) IN ('update', 'edit') THEN 30
        WHEN LOWER(BTRIM(operation."OperationName")) = 'delete' THEN 40
        ELSE 99
    END,
    CASE
        WHEN LOWER(BTRIM(operation."OperationName")) IN ('view', 'read')
            THEN 'View ' || module."DisplayName" || '.'
        WHEN LOWER(BTRIM(operation."OperationName")) IN ('create', 'add')
            THEN 'Create ' || module."DisplayName" || '.'
        WHEN LOWER(BTRIM(operation."OperationName")) IN ('update', 'edit')
            THEN 'Update ' || module."DisplayName" || '.'
        WHEN LOWER(BTRIM(operation."OperationName")) = 'delete'
            THEN 'Delete ' || module."DisplayName" || '.'
        ELSE module."DisplayName" || ' permission.'
    END,
    TRUE,
    1,
    CURRENT_TIMESTAMP
FROM axionpro."Module" module
INNER JOIN module_seed seed
    ON seed."ModuleCode" = module."ModuleCode"
INNER JOIN axionpro."Operation" operation
    ON LOWER(BTRIM(operation."OperationName")) IN
       ('view', 'read', 'create', 'add', 'update', 'edit', 'delete')
WHERE operation."IsActive" = TRUE
  AND NOT EXISTS
  (
      SELECT 1
      FROM axionpro."ModuleOperationMapping" existing
      WHERE existing."ModuleId" = module."Id"
        AND existing."OperationId" = operation."Id"
  );

UPDATE axionpro."ModuleOperationMapping" mapping
SET
    "PageURL" = module."URLPath",
    "IconURL" = COALESCE(NULLIF(BTRIM(operation."IconImage"), ''), module."ImageIconWeb"),
    "IsCommonItem" = FALSE,
    "IsOperational" = TRUE,
    "Priority" = CASE
        WHEN LOWER(BTRIM(operation."OperationName")) IN ('view', 'read') THEN 10
        WHEN LOWER(BTRIM(operation."OperationName")) IN ('create', 'add') THEN 20
        WHEN LOWER(BTRIM(operation."OperationName")) IN ('update', 'edit') THEN 30
        WHEN LOWER(BTRIM(operation."OperationName")) = 'delete' THEN 40
        ELSE 99
    END,
    "Remark" = CASE
        WHEN LOWER(BTRIM(operation."OperationName")) IN ('view', 'read')
            THEN 'View ' || module."DisplayName" || '.'
        WHEN LOWER(BTRIM(operation."OperationName")) IN ('create', 'add')
            THEN 'Create ' || module."DisplayName" || '.'
        WHEN LOWER(BTRIM(operation."OperationName")) IN ('update', 'edit')
            THEN 'Update ' || module."DisplayName" || '.'
        WHEN LOWER(BTRIM(operation."OperationName")) = 'delete'
            THEN 'Delete ' || module."DisplayName" || '.'
        ELSE module."DisplayName" || ' permission.'
    END,
    "IsActive" = TRUE,
    "UpdatedById" = 1,
    "UpdatedDateTime" = CURRENT_TIMESTAMP
FROM axionpro."Module" module,
     module_seed seed,
     axionpro."Operation" operation
WHERE mapping."ModuleId" = module."Id"
  AND seed."ModuleCode" = module."ModuleCode"
  AND operation."Id" = mapping."OperationId"
  AND LOWER(BTRIM(operation."OperationName")) IN
      ('view', 'read', 'create', 'add', 'update', 'edit', 'delete');

-- A pre-existing installation can contain a non-standard operation already
-- attached to one of these modules. Preserve its operation and active state,
-- while completing every menu/audit property instead of leaving an ambiguous
-- NULL in the navigation payload. Standard CRUD rows above retain their
-- action-specific priority and remark; this block only supplies a safe
-- fallback for any remaining operation type.
UPDATE axionpro."ModuleOperationMapping" mapping
SET
    "PageURL" = COALESCE(NULLIF(BTRIM(mapping."PageURL"), ''), module."URLPath"),
    "IconURL" = COALESCE(
        NULLIF(BTRIM(mapping."IconURL"), ''),
        NULLIF(BTRIM(operation."IconImage"), ''),
        module."ImageIconWeb"),
    "IsCommonItem" = COALESCE(mapping."IsCommonItem", FALSE),
    "IsOperational" = COALESCE(mapping."IsOperational", TRUE),
    "Priority" = COALESCE(mapping."Priority", 99),
    "Remark" = COALESCE(
        NULLIF(BTRIM(mapping."Remark"), ''),
        operation."OperationName" || ' permission for ' || module."DisplayName" || '.'),
    "IsActive" = COALESCE(mapping."IsActive", TRUE),
    "AddedById" = COALESCE(mapping."AddedById", 1),
    "AddedDateTime" = COALESCE(mapping."AddedDateTime", CURRENT_TIMESTAMP),
    "UpdatedById" = 1,
    "UpdatedDateTime" = CURRENT_TIMESTAMP
FROM axionpro."Module" module,
     module_seed seed,
     axionpro."Operation" operation
WHERE mapping."ModuleId" = module."Id"
  AND seed."ModuleCode" = module."ModuleCode"
  AND operation."Id" = mapping."OperationId";


-- ============================================================================
-- SECTION 8B
-- EMPLOYEE PASSWORD MANAGEMENT MODULE, OPERATION, AND PLAN INHERITANCE
-- ============================================================================
-- Reset Password is a dedicated security permission. Plans inherit it only
-- where EMP_LIST is already enabled; no role permission is granted here.
-- ============================================================================

DO
$$
DECLARE
    employee_parent_count INTEGER;
BEGIN
    SELECT COUNT(*)
    INTO employee_parent_count
    FROM axionpro."Module"
    WHERE "ModuleCode" = 'EMP_MGMT'
      AND "ParentModuleId" IS NULL
      AND "IsLeafNode" = FALSE
      AND "ModuleScope" = 1;

    IF employee_parent_count <> 1 THEN
        RAISE EXCEPTION
            'Expected exactly one Tenant-scope EMP_MGMT parent Module, found %.',
            employee_parent_count;
    END IF;
END;
$$;

INSERT INTO axionpro."Module"
(
    "TenantId", "ModuleCode", "ModuleName", "PageName", "DisplayName", "URLPath",
    "ParentModuleId", "IsLeafNode", "IsModuleDisplayInUI", "IsCommonMenu",
    "IsActive", "ImageIconWeb", "ImageIconMobile", "ItemPriority", "Remark",
    "AddedById", "AddedDateTime", "UpdatedById", "UpdatedDateTime", "ModuleScope"
)
SELECT
    NULL,
    'EMP_PASSWORD_MANAGEMENT',
    'Employee-Password-Management',
    'employee-password-management',
    'Employee Password Management',
    '/employees/password-management',
    parent."Id",
    TRUE,
    TRUE,
    FALSE,
    TRUE,
    'bi bi-key',
    'key',
    40,
    'Tenant-admin reset of a selected employee login password.',
    1,
    CURRENT_TIMESTAMP,
    1,
    CURRENT_TIMESTAMP,
    1
FROM axionpro."Module" parent
WHERE parent."ModuleCode" = 'EMP_MGMT'
  AND parent."ParentModuleId" IS NULL
  AND parent."IsLeafNode" = FALSE
  AND parent."ModuleScope" = 1
  AND NOT EXISTS
  (
      SELECT 1
      FROM axionpro."Module" existing
      WHERE existing."ModuleCode" = 'EMP_PASSWORD_MANAGEMENT'
  );

UPDATE axionpro."Module" module
SET
    "TenantId" = NULL,
    "ModuleName" = 'Employee-Password-Management',
    "DisplayName" = 'Employee Password Management',
    "URLPath" = '/employees/password-management',
    "ParentModuleId" =
    (
        SELECT parent."Id"
        FROM axionpro."Module" parent
        WHERE parent."ModuleCode" = 'EMP_MGMT'
          AND parent."ParentModuleId" IS NULL
          AND parent."IsLeafNode" = FALSE
          AND parent."ModuleScope" = 1
    ),
    "IsLeafNode" = TRUE,
    "IsModuleDisplayInUI" = TRUE,
    "IsCommonMenu" = FALSE,
    "IsActive" = TRUE,
    "ImageIconWeb" = 'bi bi-key',
    "ImageIconMobile" = 'key',
    "ItemPriority" = 40,
    "Remark" = 'Tenant-admin reset of a selected employee login password.',
    "AddedById" = COALESCE(module."AddedById", 1),
    "AddedDateTime" = COALESCE(module."AddedDateTime", CURRENT_TIMESTAMP),
    "UpdatedById" = 1,
    "UpdatedDateTime" = CURRENT_TIMESTAMP,
    "ModuleScope" = 1
WHERE module."ModuleCode" = 'EMP_PASSWORD_MANAGEMENT';

INSERT INTO axionpro."Operation"
(
    "OperationName", "Remark", "OperationType", "IsActive",
    "AddedById", "AddedDateTime", "IconImage"
)
SELECT
    'Reset Password',
    'Reset the login password of a selected tenant employee',
    2,
    TRUE,
    1,
    CURRENT_TIMESTAMP,
    'key-round'
WHERE NOT EXISTS
(
    SELECT 1
    FROM axionpro."Operation"
    WHERE LOWER(BTRIM("OperationName")) = LOWER('Reset Password')
);

UPDATE axionpro."Operation"
SET
    "Remark" = 'Reset the login password of a selected tenant employee',
    "OperationType" = 2,
    "IsActive" = TRUE,
    "IconImage" = 'key-round',
    "AddedById" = COALESCE("AddedById", 1),
    "AddedDateTime" = COALESCE("AddedDateTime", CURRENT_TIMESTAMP),
    "UpdatedById" = 1,
    "UpdatedDateTime" = CURRENT_TIMESTAMP
WHERE LOWER(BTRIM("OperationName")) = LOWER('Reset Password');

INSERT INTO axionpro."ModuleOperationMapping"
(
    "ModuleId", "OperationId", "PageURL", "IconURL", "IsCommonItem",
    "IsOperational", "Priority", "Remark", "IsActive", "AddedById", "AddedDateTime"
)
SELECT
    module."Id",
    operation."Id",
    '/employees/password-management',
    'key-round',
    FALSE,
    TRUE,
    10,
    'Allow an authorized tenant administrator to reset an employee password',
    TRUE,
    1,
    CURRENT_TIMESTAMP
FROM axionpro."Module" module
INNER JOIN axionpro."Operation" operation
    ON LOWER(BTRIM(operation."OperationName")) = LOWER('Reset Password')
WHERE module."ModuleCode" = 'EMP_PASSWORD_MANAGEMENT'
  AND module."IsLeafNode" = TRUE
  AND module."ModuleScope" = 1
  AND NOT EXISTS
  (
      SELECT 1
      FROM axionpro."ModuleOperationMapping" existing
      WHERE existing."ModuleId" = module."Id"
        AND existing."OperationId" = operation."Id"
  );

UPDATE axionpro."ModuleOperationMapping" mapping
SET
    "PageURL" = '/employees/password-management',
    "IconURL" = 'key-round',
    "IsCommonItem" = FALSE,
    "IsOperational" = TRUE,
    "Priority" = 10,
    "Remark" = 'Allow an authorized tenant administrator to reset an employee password',
    "IsActive" = TRUE,
    "UpdatedById" = 1,
    "UpdatedDateTime" = CURRENT_TIMESTAMP
FROM axionpro."Module" module
INNER JOIN axionpro."Operation" operation
    ON LOWER(BTRIM(operation."OperationName")) = LOWER('Reset Password')
WHERE mapping."ModuleId" = module."Id"
  AND mapping."OperationId" = operation."Id"
  AND module."ModuleCode" = 'EMP_PASSWORD_MANAGEMENT';

-- ============================================================================
-- SECTION 8B
-- TENANT PLATFORM FEATURE PLAN INHERITANCE
-- ============================================================================
-- A Tenant entitlement is sourced only from an active PlanModuleMapping.
-- These baseline Tenant features inherit precisely the active plan coverage of
-- EMP_LIST. This is the established baseline module already present in plans;
-- Host-only modules are deliberately not assigned to any Subscription Plan.
-- Existing mappings are never altered, so a Host's later plan-specific choice
-- remains authoritative.

DO
$$
DECLARE
    employee_list_plan_count INTEGER;
    target_module_count INTEGER;
BEGIN
    SELECT COUNT(DISTINCT source."SubscriptionPlanId")
    INTO employee_list_plan_count
    FROM axionpro."PlanModuleMapping" source
    INNER JOIN axionpro."Module" source_module
        ON source_module."Id" = source."ModuleId"
    WHERE source_module."ModuleCode" = 'EMP_LIST'
      AND source."IsActive" = TRUE;

    IF employee_list_plan_count = 0 THEN
        RAISE EXCEPTION
            'No active EMP_LIST PlanModuleMapping exists. Tenant feature plan mappings cannot be seeded.';
    END IF;

    SELECT COUNT(*)
    INTO target_module_count
    FROM axionpro."Module" target_module
    WHERE target_module."ModuleCode" IN
          (
              'TENANT_EMAIL_CONFIG',
              'TENANT_LOCATIONS',
              'TENANT_ATTENDANCE_POLICIES',
              'TENANT_DEVICE_SETUP',
              'TENANT_DEVICE_CONFIGURATION',
              'EMP_PASSWORD_MANAGEMENT',
              'EMP_DEVICES',
              'EMP_WORK_LOCATIONS',
              'EMP_WORK_ARRANGEMENT',
              'EMP_WORK_PATTERN',
              'EMP_OVERRIDES'
          )
      AND target_module."ModuleScope" = 1
      AND target_module."IsActive" = TRUE;

    IF target_module_count <> 11 THEN
        RAISE EXCEPTION
            'Expected eleven active Tenant feature modules before plan inheritance; found %.',
            target_module_count;
    END IF;

    INSERT INTO axionpro."PlanModuleMapping"
    (
        "SubscriptionPlanId", "ModuleId", "IsActive", "Remark",
        "AddedById", "AddedDateTime", "UpdatedById", "UpdatedDateTime"
    )
    SELECT DISTINCT
        source."SubscriptionPlanId",
        target_module."Id",
        TRUE,
        'Baseline Tenant feature inherited from active EMP_LIST plan coverage.',
        1,
        CURRENT_TIMESTAMP,
        1,
        CURRENT_TIMESTAMP
    FROM axionpro."PlanModuleMapping" source
    INNER JOIN axionpro."Module" source_module
        ON source_module."Id" = source."ModuleId"
       AND source_module."ModuleCode" = 'EMP_LIST'
    INNER JOIN axionpro."Module" target_module
        ON target_module."ModuleCode" IN
           (
               'TENANT_EMAIL_CONFIG',
               'TENANT_LOCATIONS',
               'TENANT_ATTENDANCE_POLICIES',
               'TENANT_DEVICE_SETUP',
               'TENANT_DEVICE_CONFIGURATION',
               'EMP_PASSWORD_MANAGEMENT',
               'EMP_DEVICES',
               'EMP_WORK_LOCATIONS',
               'EMP_WORK_ARRANGEMENT',
               'EMP_WORK_PATTERN',
               'EMP_OVERRIDES'
           )
       AND target_module."ModuleScope" = 1
       AND target_module."IsActive" = TRUE
    WHERE source."IsActive" = TRUE
      AND NOT EXISTS
      (
          SELECT 1
          FROM axionpro."PlanModuleMapping" existing
          WHERE existing."SubscriptionPlanId" = source."SubscriptionPlanId"
            AND existing."ModuleId" = target_module."Id"
      );
END;
$$;


-- ============================================================================
-- SECTION 8C
-- HOST TENANT LIST CREATE ACTION
-- ============================================================================
-- The Host Tenant List page owns its row actions.  Keep Create attached to
-- this leaf module so Navigation/my-menu can render the action from the same
-- permission object.  This does not grant the permission to any Host role.

DO
$$
DECLARE
    host_tenant_list_module_id INTEGER;
    create_operation_id INTEGER;
BEGIN
    -- Operation.Id = 1 is the existing canonical Create operation.  Do not
    -- insert a duplicate operation; only ensure the existing record is active
    -- because Navigation/my-menu excludes inactive operations.
    UPDATE axionpro."Operation"
    SET
        "IsActive" = TRUE,
        "IconImage" = COALESCE(NULLIF(BTRIM("IconImage"), ''), 'plus'),
        "UpdatedById" = 1,
        "UpdatedDateTime" = CURRENT_TIMESTAMP
    WHERE "Id" = 1
      AND "IsActive" IS DISTINCT FROM TRUE;

    SELECT "Id"
    INTO host_tenant_list_module_id
    FROM axionpro."Module"
    WHERE "ModuleCode" = 'HOST_TENANT_LIST'
      AND "ModuleScope" = 2
      AND "IsLeafNode" = TRUE
    ORDER BY "Id"
    LIMIT 1;

    IF host_tenant_list_module_id IS NULL THEN
        RAISE EXCEPTION
            'HOST_TENANT_LIST module was not found; Create navigation mapping cannot be seeded.';
    END IF;

    SELECT "Id"
    INTO create_operation_id
    FROM axionpro."Operation"
    WHERE "Id" = 1
      AND "IsActive" = TRUE
    LIMIT 1;

    IF create_operation_id IS NULL THEN
        RAISE EXCEPTION
            'The existing Create operation (Operation.Id = 1) must be active before HOST_TENANT_LIST can be mapped.';
    END IF;

    INSERT INTO axionpro."ModuleOperationMapping"
    (
        "ModuleId", "OperationId", "PageURL", "IconURL", "IsCommonItem",
        "IsOperational", "Priority", "Remark", "IsActive", "AddedById", "AddedDateTime"
    )
    SELECT
        module."Id",
        operation."Id",
        module."URLPath",
        COALESCE(NULLIF(BTRIM(operation."IconImage"), ''), 'plus'),
        FALSE,
        TRUE,
        20,
        'Create a new tenant from the Host Tenant List.',
        TRUE,
        1,
        CURRENT_TIMESTAMP
    FROM axionpro."Module" module
    INNER JOIN axionpro."Operation" operation
        ON operation."Id" = create_operation_id
    WHERE module."Id" = host_tenant_list_module_id
      AND NOT EXISTS
      (
          SELECT 1
          FROM axionpro."ModuleOperationMapping" existing
          WHERE existing."ModuleId" = module."Id"
            AND existing."OperationId" = operation."Id"
      );

    UPDATE axionpro."ModuleOperationMapping" mapping
    SET
        "PageURL" = module."URLPath",
        "IconURL" = COALESCE(NULLIF(BTRIM(operation."IconImage"), ''), 'plus'),
        "IsCommonItem" = FALSE,
        "IsOperational" = TRUE,
        "Priority" = 20,
        "Remark" = 'Create a new tenant from the Host Tenant List.',
        "IsActive" = TRUE,
        "UpdatedById" = 1,
        "UpdatedDateTime" = CURRENT_TIMESTAMP
    FROM axionpro."Module" module
    INNER JOIN axionpro."Operation" operation
        ON operation."Id" = create_operation_id
    WHERE mapping."ModuleId" = module."Id"
      AND mapping."OperationId" = operation."Id"
      AND module."Id" = host_tenant_list_module_id;
END;
$$;


-- ============================================================================
-- SECTION 8D
-- CONSOLIDATED MODULE VALIDATION
-- ============================================================================

DO
$$
DECLARE
    invalid_module_count INTEGER;
    incomplete_module_metadata_count INTEGER;
    missing_standard_action_mapping_count INTEGER;
    incomplete_mapping_metadata_count INTEGER;
    incomplete_operation_metadata_count INTEGER;
    password_module_count INTEGER;
    reset_password_operation_count INTEGER;
    reset_password_mapping_count INTEGER;
BEGIN
    SELECT COUNT(*)
    INTO invalid_module_count
    FROM module_seed seed
    WHERE
    (
        SELECT COUNT(*)
        FROM axionpro."Module" module
        WHERE module."ModuleCode" = seed."ModuleCode"
    ) <> 1;

    IF invalid_module_count <> 0 THEN
        RAISE EXCEPTION
            'Consolidated module validation failed: % seeded module code(s) did not resolve to exactly one Module row.',
            invalid_module_count;
    END IF;

    SELECT COUNT(*)
    INTO incomplete_module_metadata_count
    FROM axionpro."Module" module
    INNER JOIN module_seed seed
        ON seed."ModuleCode" = module."ModuleCode"
    WHERE NULLIF(BTRIM(module."ModuleName"), '') IS NULL
       OR NULLIF(BTRIM(module."DisplayName"), '') IS NULL
       OR NULLIF(BTRIM(module."URLPath"), '') IS NULL
       OR NULLIF(BTRIM(module."ImageIconWeb"), '') IS NULL
       OR NULLIF(BTRIM(module."ImageIconMobile"), '') IS NULL
       OR NULLIF(BTRIM(module."Remark"), '') IS NULL
       OR module."ItemPriority" IS NULL
       OR module."AddedById" IS NULL
       OR module."AddedDateTime" IS NULL
       OR module."UpdatedById" IS NULL
       OR module."UpdatedDateTime" IS NULL;

    IF incomplete_module_metadata_count <> 0 THEN
        RAISE EXCEPTION
            'Consolidated module validation failed: % seeded module row(s) have incomplete presentation or audit metadata.',
            incomplete_module_metadata_count;
    END IF;

    -- Every menu feature receives all four standard action permissions.
    -- DataViewStructureId and PageTypeId remain intentionally NULL because
    -- they are optional foreign-key metadata and no neutral IDs can safely be
    -- invented by a permission seed.
    SELECT COUNT(*)
    INTO missing_standard_action_mapping_count
    FROM module_seed seed
    CROSS JOIN
    (
        VALUES ('view'), ('create'), ('update'), ('delete')
    ) AS required_action("ActionName")
    WHERE NOT EXISTS
    (
        SELECT 1
        FROM axionpro."ModuleOperationMapping" mapping
        INNER JOIN axionpro."Module" module
            ON module."Id" = mapping."ModuleId"
        INNER JOIN axionpro."Operation" operation
            ON operation."Id" = mapping."OperationId"
        WHERE module."ModuleCode" = seed."ModuleCode"
          AND mapping."IsActive" = TRUE
          AND operation."IsActive" = TRUE
          AND
          (
              (required_action."ActionName" = 'view' AND LOWER(BTRIM(operation."OperationName")) IN ('view', 'read'))
              OR (required_action."ActionName" = 'create' AND LOWER(BTRIM(operation."OperationName")) IN ('create', 'add'))
              OR (required_action."ActionName" = 'update' AND LOWER(BTRIM(operation."OperationName")) IN ('update', 'edit'))
              OR (required_action."ActionName" = 'delete' AND LOWER(BTRIM(operation."OperationName")) = 'delete')
          )
    );

    IF missing_standard_action_mapping_count <> 0 THEN
        RAISE EXCEPTION
            'Consolidated mapping validation failed: % required module-action mapping(s) are missing.',
            missing_standard_action_mapping_count;
    END IF;

    SELECT COUNT(*)
    INTO incomplete_mapping_metadata_count
    FROM axionpro."ModuleOperationMapping" mapping
    INNER JOIN axionpro."Module" module
        ON module."Id" = mapping."ModuleId"
    INNER JOIN module_seed seed
        ON seed."ModuleCode" = module."ModuleCode"
    WHERE NULLIF(BTRIM(mapping."PageURL"), '') IS NULL
       OR NULLIF(BTRIM(mapping."IconURL"), '') IS NULL
       OR mapping."IsCommonItem" IS NULL
       OR mapping."IsOperational" IS NULL
       OR mapping."Priority" IS NULL
       OR NULLIF(BTRIM(mapping."Remark"), '') IS NULL
       OR mapping."IsActive" IS NULL
       OR mapping."AddedById" IS NULL
       OR mapping."AddedDateTime" IS NULL
       OR mapping."UpdatedById" IS NULL
       OR mapping."UpdatedDateTime" IS NULL;

    IF incomplete_mapping_metadata_count <> 0 THEN
        RAISE EXCEPTION
            'Consolidated mapping validation failed: % module-operation mapping row(s) have incomplete UI or audit metadata.',
            incomplete_mapping_metadata_count;
    END IF;

    SELECT COUNT(*)
    INTO incomplete_operation_metadata_count
    FROM axionpro."Operation" operation
    WHERE LOWER(BTRIM(operation."OperationName")) IN
          ('view', 'read', 'create', 'add', 'update', 'edit', 'delete')
      AND
      (
          NULLIF(BTRIM(operation."Remark"), '') IS NULL
          OR operation."OperationType" IS NULL
          OR NULLIF(BTRIM(operation."IconImage"), '') IS NULL
          OR operation."AddedById" IS NULL
          OR operation."AddedDateTime" IS NULL
          OR operation."UpdatedById" IS NULL
          OR operation."UpdatedDateTime" IS NULL
      );

    IF incomplete_operation_metadata_count <> 0 THEN
        RAISE EXCEPTION
            'Consolidated operation validation failed: % standard operation row(s) have incomplete metadata.',
            incomplete_operation_metadata_count;
    END IF;

    SELECT COUNT(*)
    INTO password_module_count
    FROM axionpro."Module"
    WHERE "ModuleCode" = 'EMP_PASSWORD_MANAGEMENT'
      AND "IsLeafNode" = TRUE
      AND "ModuleScope" = 1;

    SELECT COUNT(*)
    INTO reset_password_operation_count
    FROM axionpro."Operation"
    WHERE LOWER(BTRIM("OperationName")) = LOWER('Reset Password')
      AND "IsActive" = TRUE;

    SELECT COUNT(*)
    INTO reset_password_mapping_count
    FROM axionpro."ModuleOperationMapping" mapping
    INNER JOIN axionpro."Module" module
        ON module."Id" = mapping."ModuleId"
    INNER JOIN axionpro."Operation" operation
        ON operation."Id" = mapping."OperationId"
    WHERE module."ModuleCode" = 'EMP_PASSWORD_MANAGEMENT'
      AND LOWER(BTRIM(operation."OperationName")) = LOWER('Reset Password')
      AND mapping."IsActive" = TRUE;

    IF password_module_count <> 1 THEN
        RAISE EXCEPTION
            'EMP_PASSWORD_MANAGEMENT module validation failed. Expected 1, found %.',
            password_module_count;
    END IF;

    IF reset_password_operation_count <> 1 THEN
        RAISE EXCEPTION
            'Reset Password operation validation failed. Expected 1, found %.',
            reset_password_operation_count;
    END IF;

    IF reset_password_mapping_count <> 1 THEN
        RAISE EXCEPTION
            'EMP_PASSWORD_MANAGEMENT mapping validation failed. Expected 1, found %.',
            reset_password_mapping_count;
    END IF;
END;
$$;


-- ============================================================================
-- SECTION 8E
-- PLATFORM HOST ADMIN PERMISSION BASELINE
-- ============================================================================
-- Rebuild the Host authorization baseline before inserting persisted grants.
-- Only two authenticated principal types are supported by MyMenu: Tenant and
-- Host. Host authorization itself is still role/permission based; no runtime
-- Host-Super-Admin receives the complete persisted grant set; runtime checks
-- still evaluate HostRoleModuleAndPermission for every Host request.
-- ============================================================================

DELETE FROM axionpro."RefreshToken"
WHERE "HostUserId" IS NOT NULL;

DELETE FROM axionpro."HostRoleModuleAndPermission";
DELETE FROM axionpro."HostUser";
DELETE FROM axionpro."HostRole";

DO
$$
DECLARE
    sequence_name TEXT;
BEGIN
    FOREACH sequence_name IN ARRAY ARRAY[
        pg_get_serial_sequence('axionpro."HostRole"', 'Id'),
        pg_get_serial_sequence('axionpro."HostUser"', 'Id'),
        pg_get_serial_sequence('axionpro."HostRoleModuleAndPermission"', 'Id')
    ]
    LOOP
        IF sequence_name IS NOT NULL THEN
            PERFORM setval(sequence_name::regclass, 1, FALSE);
        END IF;
    END LOOP;
END;
$$;

INSERT INTO axionpro."HostRole"
(
    "Id", "Name", "Description", "IsActive", "AddedById", "AddedDateTime",
    "UpdatedById", "UpdatedDateTime", "DeletedById", "DeletedDateTime", "IsSoftDeleted"
)
VALUES
(
    1,
    'Host-Super-Admin',
    'Full Host-scope administration through persisted module-operation permissions.',
    TRUE,
    1,
    CURRENT_TIMESTAMP,
    1,
    CURRENT_TIMESTAMP,
    NULL,
    NULL,
    FALSE
);

-- PasswordHash is ASP.NET Core Identity PasswordHasher V3 for 12344321.
INSERT INTO axionpro."HostUser"
(
    "Id", "HostRoleId", "Name", "LoginId", "PasswordHash", "Email", "MobileNumber",
    "IsActive", "IsSoftDeleted", "AddedById", "AddedDateTime", "UpdatedById",
    "UpdatedDateTime", "DeletedById", "DeletedDateTime"
)
VALUES
(
    1,
    1,
    'Deepesh Gupta',
    'mca.deepesh@gmail.com',
    'AQAAAAIAAYagAAAAEEDpT6tXHxx4OhhP394Aqp4vlsVunbyd3qQGOnszn4oghxYFlkERmuDjy0ATNqawgw==',
    'mca.deepesh@gmail.com',
    '9111161399',
    TRUE,
    FALSE,
    1,
    CURRENT_TIMESTAMP,
    1,
    CURRENT_TIMESTAMP,
    NULL,
    NULL
);

DO
$$
DECLARE
    expected_mapping_count INTEGER;
    effective_permission_count INTEGER;
BEGIN
    INSERT INTO axionpro."HostRoleModuleAndPermission"
    (
        "HostRoleId",
        "ModuleId",
        "OperationId",
        "IsActive",
        "IsSoftDeleted",
        "AddedById",
        "AddedDateTime",
        "UpdatedById",
        "UpdatedDateTime",
        "DeletedById",
        "DeletedDateTime"
    )
    SELECT
        1,
        mapping."ModuleId",
        mapping."OperationId",
        TRUE,
        FALSE,
        1,
        CURRENT_TIMESTAMP,
        1,
        CURRENT_TIMESTAMP,
        NULL,
        NULL
    FROM axionpro."ModuleOperationMapping" mapping
    INNER JOIN axionpro."Module" module
        ON module."Id" = mapping."ModuleId"
    INNER JOIN axionpro."Operation" operation
        ON operation."Id" = mapping."OperationId"
    WHERE mapping."IsActive" = TRUE
      AND mapping."IsOperational" = TRUE
      AND module."ModuleScope" = 2
      AND module."IsActive" = TRUE
      AND operation."IsActive" = TRUE
      AND NOT EXISTS
      (
          SELECT 1
          FROM axionpro."HostRoleModuleAndPermission" existing
          WHERE existing."HostRoleId" = 1
            AND existing."ModuleId" = mapping."ModuleId"
            AND existing."OperationId" = mapping."OperationId"
      );

    SELECT COUNT(DISTINCT (mapping."ModuleId", mapping."OperationId"))
    INTO expected_mapping_count
    FROM axionpro."ModuleOperationMapping" mapping
    INNER JOIN axionpro."Module" module
        ON module."Id" = mapping."ModuleId"
    INNER JOIN axionpro."Operation" operation
        ON operation."Id" = mapping."OperationId"
    WHERE mapping."IsActive" = TRUE
      AND mapping."IsOperational" = TRUE
      AND module."ModuleScope" = 2
      AND module."IsActive" = TRUE
      AND operation."IsActive" = TRUE;

    SELECT COUNT(DISTINCT (permission."ModuleId", permission."OperationId"))
    INTO effective_permission_count
    FROM axionpro."HostRoleModuleAndPermission" permission
    INNER JOIN axionpro."ModuleOperationMapping" mapping
        ON mapping."ModuleId" = permission."ModuleId"
       AND mapping."OperationId" = permission."OperationId"
    INNER JOIN axionpro."Module" module
        ON module."Id" = mapping."ModuleId"
    INNER JOIN axionpro."Operation" operation
        ON operation."Id" = mapping."OperationId"
    WHERE permission."HostRoleId" = 1
      AND permission."IsActive" = TRUE
      AND permission."IsSoftDeleted" = FALSE
      AND mapping."IsActive" = TRUE
      AND mapping."IsOperational" = TRUE
      AND module."ModuleScope" = 2
      AND module."IsActive" = TRUE
      AND operation."IsActive" = TRUE;

    IF effective_permission_count <> expected_mapping_count THEN
        RAISE EXCEPTION
            'Host-Super-Admin permission validation failed: expected % active Host mapping(s), found % active Host-Super-Admin permission(s).',
            expected_mapping_count,
            effective_permission_count;
    END IF;
END;
$$;


-- ============================================================================
-- SECTION 9
-- PRODUCTION VALIDATION
-- ============================================================================
--
-- Agar required module ya operation mapping create nahi hui
-- to transaction COMMIT nahi hogi.
-- ============================================================================

DO
$$
DECLARE

    host_module_count INTEGER;

    tenant_module_count INTEGER;

    host_mapping_count INTEGER;

    tenant_mapping_count INTEGER;

BEGIN

    SELECT COUNT(*)

    INTO host_module_count

    FROM axionpro."Module"

    WHERE "ModuleCode"
          = 'HOST_DEFAULT_EMAIL_CONFIG';


    SELECT COUNT(*)

    INTO tenant_module_count

    FROM axionpro."Module"

    WHERE "ModuleCode"
          = 'TENANT_EMAIL_CONFIG';


    IF host_module_count <> 1 THEN

        RAISE EXCEPTION
        'Expected exactly one HOST_DEFAULT_EMAIL_CONFIG module. Found: %',
        host_module_count;

    END IF;


    IF tenant_module_count <> 1 THEN

        RAISE EXCEPTION
        'Expected exactly one TENANT_EMAIL_CONFIG module. Found: %',
        tenant_module_count;

    END IF;


    SELECT COUNT(*)

    INTO host_mapping_count

    FROM axionpro."ModuleOperationMapping"
        mapping

    INNER JOIN axionpro."Module"
        module

        ON module."Id"
           = mapping."ModuleId"

    WHERE module."ModuleCode"
          = 'HOST_DEFAULT_EMAIL_CONFIG'

      AND mapping."IsActive"
          = TRUE;


    SELECT COUNT(*)

    INTO tenant_mapping_count

    FROM axionpro."ModuleOperationMapping"
        mapping

    INNER JOIN axionpro."Module"
        module

        ON module."Id"
           = mapping."ModuleId"

    WHERE module."ModuleCode"
          = 'TENANT_EMAIL_CONFIG'

      AND mapping."IsActive"
          = TRUE;


    IF host_mapping_count = 0 THEN

        RAISE EXCEPTION
        'No CRUD Operation mapping found for HOST_DEFAULT_EMAIL_CONFIG. Check Operation master data.';

    END IF;


    IF tenant_mapping_count = 0 THEN

        RAISE EXCEPTION
        'No CRUD Operation mapping found for TENANT_EMAIL_CONFIG. Check Operation master data.';

    END IF;

END;
$$;


-- ============================================================================
-- SECTION 9B
-- IMMUTABLE PAGE-NAME BACKFILL AND DATABASE ENFORCEMENT
-- ============================================================================
-- Existing modules receive a deterministic key once. The special Device
-- Management component key is intentionally kept exactly as registered by UI.
-- A legacy NULL may be populated once; after that an update cannot alter
-- PageName, including only its casing.
-- ============================================================================

-- On a re-run, this replaces the older strict trigger implementation before
-- the backfill below executes. It permits only the one-time NULL -> key
-- migration required for older module rows such as card inventory.
CREATE OR REPLACE FUNCTION axionpro."PreventModulePageNameChange"()
RETURNS TRIGGER
LANGUAGE plpgsql
AS
$$
BEGIN
    IF OLD."PageName" IS NOT NULL
       AND NEW."PageName" IS DISTINCT FROM OLD."PageName" THEN
        RAISE EXCEPTION
            USING ERRCODE = '23514',
                  MESSAGE = 'Module PageName is immutable and cannot be changed after initial assignment.';
    END IF;

    RETURN NEW;
END;
$$;

UPDATE axionpro."Module" module
SET "PageName" = CASE module."ModuleCode"
    WHEN 'HOST_MANAGEMENT' THEN 'host-management'
    WHEN 'HOST_TENANT_RFID_MANAGEMENT' THEN 'tenant-rfid-management'
    WHEN 'HOST_USERS' THEN 'host-users'
    WHEN 'HOST_ROLES' THEN 'host-roles'
    WHEN 'HOST_ROLE_PERMISSIONS' THEN 'host-role-permissions'
    WHEN 'HOST_MODULES' THEN 'host-modules'
    WHEN 'HOST_SUBMODULES' THEN 'host-submodules'
    WHEN 'HOST_OPERATIONS' THEN 'host-operations'
    WHEN 'HOST_MODULE_OPERATIONS' THEN 'host-module-operations'
    WHEN 'HOST_SUBSCRIPTIONS' THEN 'host-subscriptions'
    WHEN 'HOST_DEVICE_MGMT' THEN 'device-manangment'
    WHEN 'HOST_DEFAULT_EMAIL_CONFIG' THEN 'platform-email-defaults'
    WHEN 'TENANT_EMAIL_CONFIG' THEN 'email-delivery-settings'
    WHEN 'HOST_TENANT_EMAIL_CONFIG' THEN 'tenant-email-administration'
    WHEN 'HOST_EMAIL_TEMPLATE' THEN 'email-templates'
    WHEN 'HOST_DEVICE_SETUP' THEN 'device-catalogue'
    WHEN 'TENANT_DEVICE_SETUP' THEN 'installed-devices'
    WHEN 'HOST_INITIAL_DEVICE_CONFIGURATION' THEN 'device-provisioning'
    WHEN 'TENANT_DEVICE_CONFIGURATION' THEN 'device-connectivity'
    WHEN 'HOST_TENANT_CARD_INVENTORY' THEN 'tenant-card-inventory'
    WHEN 'TENANT_LOCATIONS' THEN 'tenant-locations'
    WHEN 'TENANT_ATTENDANCE_POLICIES' THEN 'attendance-policies'
    WHEN 'EMP_DEVICES' THEN 'employee-device-enrollment'
    WHEN 'EMP_WORK_LOCATIONS' THEN 'employee-work-locations'
    WHEN 'EMP_WORK_ARRANGEMENT' THEN 'employee-work-arrangements'
    WHEN 'EMP_WORK_PATTERN' THEN 'employee-work-patterns'
    WHEN 'EMP_OVERRIDES' THEN 'employee-work-mode-overrides'
    WHEN 'EMP_PASSWORD_MANAGEMENT' THEN 'employee-password-management'
    ELSE BTRIM(REGEXP_REPLACE(LOWER(BTRIM(module."ModuleCode")), '[^a-z0-9]+', '-', 'g'), '-')
END
WHERE module."PageName" IS NULL
  AND NULLIF(BTRIM(module."ModuleCode"), '') IS NOT NULL;

DO
$$
DECLARE
    missing_page_name_count INTEGER;
BEGIN
    SELECT COUNT(*)
    INTO missing_page_name_count
    FROM module_seed seed
    LEFT JOIN axionpro."Module" module
        ON module."ModuleCode" = seed."ModuleCode"
    WHERE module."Id" IS NULL
       OR NULLIF(BTRIM(module."PageName"), '') IS NULL;

    IF missing_page_name_count <> 0 THEN
        RAISE EXCEPTION
            'Module PageName validation failed: % seeded module row(s) do not have a stable page key.',
            missing_page_name_count;
    END IF;
END;
$$;

DO
$$
BEGIN
    IF EXISTS
    (
        SELECT 1
        FROM axionpro."Module"
        WHERE "PageName" IS NOT NULL
          AND
          (
              "PageName" !~ '^[a-z0-9]+(-[a-z0-9]+)*$'
              OR CHAR_LENGTH("PageName") > 100
          )
    )
    THEN
        RAISE EXCEPTION 'Every Module PageName must be a lowercase 1-100 character component key.';
    END IF;

    IF EXISTS
    (
        SELECT LOWER("PageName")
        FROM axionpro."Module"
        WHERE "PageName" IS NOT NULL
        GROUP BY LOWER("PageName")
        HAVING COUNT(*) > 1
    )
    THEN
        RAISE EXCEPTION 'Module PageName values must be unique without regard to case.';
    END IF;
END;
$$;

ALTER TABLE axionpro."Module"
DROP CONSTRAINT IF EXISTS "CK_Module_PageName_Format";

ALTER TABLE axionpro."Module"
ADD CONSTRAINT "CK_Module_PageName_Format"
CHECK
(
    "PageName" IS NULL
    OR "PageName" ~ '^[a-z0-9]+(-[a-z0-9]+)*$'
);

CREATE UNIQUE INDEX IF NOT EXISTS "UX_Module_PageName_CaseInsensitive"
ON axionpro."Module" (LOWER("PageName"))
WHERE "PageName" IS NOT NULL;

CREATE OR REPLACE FUNCTION axionpro."PreventModulePageNameChange"()
RETURNS TRIGGER
LANGUAGE plpgsql
AS
$$
BEGIN
    IF OLD."PageName" IS NOT NULL
       AND NEW."PageName" IS DISTINCT FROM OLD."PageName" THEN
        RAISE EXCEPTION
            USING ERRCODE = '23514',
                  MESSAGE = 'Module PageName is immutable and cannot be changed after initial assignment.';
    END IF;

    RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS "TR_Module_PageNameImmutable"
ON axionpro."Module";

CREATE TRIGGER "TR_Module_PageNameImmutable"
BEFORE UPDATE OF "PageName"
ON axionpro."Module"
FOR EACH ROW
EXECUTE FUNCTION axionpro."PreventModulePageNameChange"();


-- ============================================================================
-- SECTION 10
-- SAFE AUTO-INCREMENT / IDENTITY SYNCHRONIZATION
-- ============================================================================
--
-- IMPORTANT:
--
-- Empty table:
--     next ID = 1
--
-- Existing table:
--     next ID = MAX(Id) + 1
--
-- Host authorization tables are intentionally rebuilt above, so their
-- sequences are restarted from the canonical seed rows; other tables retain
-- the normal MAX(Id) + 1 behavior.
-- ============================================================================

DO
$$
DECLARE

    sequence_name TEXT;

    maximum_id BIGINT;

BEGIN


    -- ========================================================================
    -- DefaultEmailConfig
    -- ========================================================================

    sequence_name :=
        pg_get_serial_sequence
        (
            'axionpro."DefaultEmailConfig"',
            'Id'
        );


    IF sequence_name IS NOT NULL THEN

        SELECT COALESCE(MAX("Id"), 0)

        INTO maximum_id

        FROM axionpro."DefaultEmailConfig";


        IF maximum_id = 0 THEN

            PERFORM setval
            (
                sequence_name::regclass,
                1,
                FALSE
            );

        ELSE

            PERFORM setval
            (
                sequence_name::regclass,
                maximum_id,
                TRUE
            );

        END IF;

    END IF;



    -- ========================================================================
    -- Module
    -- ========================================================================

    sequence_name :=
        pg_get_serial_sequence
        (
            'axionpro."Module"',
            'Id'
        );


    IF sequence_name IS NOT NULL THEN

        SELECT COALESCE(MAX("Id"), 0)

        INTO maximum_id

        FROM axionpro."Module";


        IF maximum_id = 0 THEN

            PERFORM setval
            (
                sequence_name::regclass,
                1,
                FALSE
            );

        ELSE

            PERFORM setval
            (
                sequence_name::regclass,
                maximum_id,
                TRUE
            );

        END IF;

    END IF;



    -- ========================================================================
    -- ModuleOperationMapping
    -- ========================================================================

    sequence_name :=
        pg_get_serial_sequence
        (
            'axionpro."ModuleOperationMapping"',
            'Id'
        );


    IF sequence_name IS NOT NULL THEN

        SELECT COALESCE(MAX("Id"), 0)

        INTO maximum_id

        FROM axionpro."ModuleOperationMapping";


        IF maximum_id = 0 THEN

            PERFORM setval
            (
                sequence_name::regclass,
                1,
                FALSE
            );

        ELSE

            PERFORM setval
            (
                sequence_name::regclass,
                maximum_id,
                TRUE
            );

        END IF;

    END IF;


    -- ========================================================================
    -- HostRole
    -- ========================================================================

    sequence_name := pg_get_serial_sequence('axionpro."HostRole"', 'Id');

    IF sequence_name IS NOT NULL THEN
        SELECT COALESCE(MAX("Id"), 0)
        INTO maximum_id
        FROM axionpro."HostRole";

        PERFORM setval(
            sequence_name::regclass,
            CASE WHEN maximum_id = 0 THEN 1 ELSE maximum_id END,
            maximum_id <> 0);
    END IF;


    -- ========================================================================
    -- HostUser
    -- ========================================================================

    sequence_name := pg_get_serial_sequence('axionpro."HostUser"', 'Id');

    IF sequence_name IS NOT NULL THEN
        SELECT COALESCE(MAX("Id"), 0)
        INTO maximum_id
        FROM axionpro."HostUser";

        PERFORM setval(
            sequence_name::regclass,
            CASE WHEN maximum_id = 0 THEN 1 ELSE maximum_id END,
            maximum_id <> 0);
    END IF;


    -- ========================================================================
    -- HostRoleModuleAndPermission
    -- ========================================================================

    sequence_name := pg_get_serial_sequence('axionpro."HostRoleModuleAndPermission"', 'Id');

    IF sequence_name IS NOT NULL THEN
        SELECT COALESCE(MAX("Id"), 0)
        INTO maximum_id
        FROM axionpro."HostRoleModuleAndPermission";

        PERFORM setval(
            sequence_name::regclass,
            CASE WHEN maximum_id = 0 THEN 1 ELSE maximum_id END,
            maximum_id <> 0);
    END IF;

END;
$$;


-- ============================================================================
-- EVERYTHING SUCCESSFUL
-- ============================================================================

COMMIT;


-- ============================================================================
-- VERIFICATION 1
-- DEFAULT EMAIL CONFIGURATION
-- ============================================================================
--
-- Password / Secret intentionally SELECT nahi kiya gaya.
-- ============================================================================

SELECT

    "Id",

    "ConfigName",

    "SmtpHost",

    "SmtpPort",

    "SmtpUsername",

    "FromEmail",

    "FromName",

    "IsActive",

    "IsDefault",

    "CreatedDateTime",

    "UpdatedDateTime"

FROM axionpro."DefaultEmailConfig"

ORDER BY "Id";


-- ============================================================================
-- VERIFICATION 2
-- CONSOLIDATED MODULES WITH ALL CURRENT MODULE PROPERTIES
-- ============================================================================

SELECT

    "Id",

    "TenantId",

    "ModuleCode",

    "ModuleName",

    "PageName",

    "DisplayName",

    "URLPath",

    "ParentModuleId",

    "IsLeafNode",

    "IsModuleDisplayInUI",

    "IsCommonMenu",

    "IsActive",

    "ImageIconWeb",

    "ImageIconMobile",

    "ItemPriority",

    "Remark",

    "AddedById",

    "AddedDateTime",

    "UpdatedById",

    "UpdatedDateTime",

    "ModuleScope"

FROM axionpro."Module"

WHERE "ModuleCode"
      IN
      (
          'HOST_MANAGEMENT',
          'HOST_TENANT_RFID_MANAGEMENT',
          'HOST_USERS',
          'HOST_ROLES',
          'HOST_ROLE_PERMISSIONS',
          'HOST_MODULES',
          'HOST_SUBMODULES',
          'HOST_OPERATIONS',
          'HOST_MODULE_OPERATIONS',
          'HOST_SUBSCRIPTIONS',
          'HOST_DEFAULT_EMAIL_CONFIG',
          'HOST_TENANT_EMAIL_CONFIG',
          'TENANT_EMAIL_CONFIG',
          'HOST_EMAIL_TEMPLATE',
          'HOST_DEVICE_MGMT',
          'HOST_DEVICE_SETUP',
          'TENANT_DEVICE_SETUP',
          'HOST_INITIAL_DEVICE_CONFIGURATION',
          'TENANT_DEVICE_CONFIGURATION',
          'HOST_TENANT_CARD_INVENTORY',
          'TENANT_LOCATIONS',
          'TENANT_ATTENDANCE_POLICIES',
          'EMP_DEVICES',
          'EMP_WORK_LOCATIONS',
          'EMP_WORK_ARRANGEMENT',
          'EMP_WORK_PATTERN',
          'EMP_OVERRIDES',
          'EMP_PASSWORD_MANAGEMENT',
          'EMP_LIST', 'TENANT_DEPARTMENTS', 'TENANT_DESIGNATIONS',
          'TENANT_ROLES_PERMISSIONS', 'TENANT_EMPLOYEE_TYPES', 'TENANT_EMPLOYEE_CODE'
      )

ORDER BY
    "ModuleScope",
    "Id";


-- ============================================================================
-- VERIFICATION 3
-- MODULE OPERATION MAPPINGS
-- ============================================================================

SELECT

    module."Id"
        AS "ModuleId",

    module."ModuleCode",

    module."ModuleName",

    module."ModuleScope",

    operation."Id"
        AS "OperationId",

    operation."OperationName",

    mapping."Priority",

    mapping."IsCommonItem",

    mapping."IsOperational",

    mapping."Remark",

    mapping."IsActive"

FROM axionpro."ModuleOperationMapping"
    mapping

INNER JOIN axionpro."Module"
    module

    ON module."Id"
       = mapping."ModuleId"

INNER JOIN axionpro."Operation"
    operation

    ON operation."Id"
       = mapping."OperationId"

WHERE module."ModuleCode"
      IN
      (
          'HOST_USERS',
          'HOST_ROLES',
          'HOST_ROLE_PERMISSIONS',
          'HOST_MODULES',
          'HOST_SUBMODULES',
          'HOST_OPERATIONS',
          'HOST_MODULE_OPERATIONS',
          'HOST_SUBSCRIPTIONS',
          'HOST_DEFAULT_EMAIL_CONFIG',
          'HOST_TENANT_EMAIL_CONFIG',
          'TENANT_EMAIL_CONFIG',
          'HOST_EMAIL_TEMPLATE',
          'HOST_DEVICE_SETUP',
          'TENANT_DEVICE_SETUP',
          'HOST_INITIAL_DEVICE_CONFIGURATION',
          'TENANT_DEVICE_CONFIGURATION',
          'HOST_TENANT_CARD_INVENTORY',
          'TENANT_LOCATIONS',
          'TENANT_ATTENDANCE_POLICIES',
          'EMP_DEVICES',
          'EMP_WORK_LOCATIONS',
          'EMP_WORK_ARRANGEMENT',
          'EMP_WORK_PATTERN',
          'EMP_OVERRIDES',
          'EMP_PASSWORD_MANAGEMENT'
      )

ORDER BY

    module."ModuleScope",

    module."ModuleCode",

    mapping."Priority",

    operation."OperationName";


-- ============================================================================
-- VERIFICATION 4
-- TENANT PLATFORM FEATURE PLAN MAPPINGS
-- ============================================================================

SELECT

    plan_mapping.*,

    module."ModuleCode",

    module."DisplayName"

FROM axionpro."PlanModuleMapping"
    plan_mapping

INNER JOIN axionpro."Module"
    module

    ON module."Id"
       = plan_mapping."ModuleId"

WHERE module."ModuleCode"
      IN
      (
          'TENANT_EMAIL_CONFIG',
          'TENANT_LOCATIONS',
          'TENANT_ATTENDANCE_POLICIES',
          'TENANT_DEVICE_SETUP',
          'TENANT_DEVICE_CONFIGURATION',
          'EMP_DEVICES',
          'EMP_WORK_LOCATIONS',
          'EMP_WORK_ARRANGEMENT',
          'EMP_WORK_PATTERN',
          'EMP_OVERRIDES',
          'EMP_PASSWORD_MANAGEMENT'
      )

ORDER BY
    plan_mapping."SubscriptionPlanId",
    module."ModuleCode";
