-- ============================================================================
-- AxionPro Production - Email Configuration Consolidated Setup
-- Author      : Deepesh Gupta
-- Company     : Quecksilber Technologies
-- Role        : CEO
--
-- Purpose:
--   1. DefaultEmailConfig table create / upgrade.
--   2. Existing active TenantEmailConfig se default SMTP seed.
--   3. Host module      : Default Email Configuration.
--   4. Tenant module    : Tenant Email Configuration.
--   5. Existing CRUD Operations ko dono modules se map karna.
--   6. Existing incomplete module records ko normalize/update karna.
--   7. Identity / auto-increment sequence safely synchronize karna.
--
-- IMPORTANT:
--   * SMTP password/secret hard-code nahi kiya gaya hai.
--   * Existing production IDs ko reset/delete nahi kiya jayega.
--   * Script re-run safe/idempotent rakhi gayi hai.
-- ============================================================================


BEGIN;


-- ============================================================================
-- SECTION 1 : DEFAULT EMAIL CONFIGURATION TABLE
-- ============================================================================

CREATE TABLE IF NOT EXISTS axionpro."DefaultEmailConfig"
(
    "Id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    "ConfigName" CHARACTER VARYING(100) NOT NULL,

    "SmtpHost" CHARACTER VARYING(200) NOT NULL,

    "SmtpPort" INTEGER NOT NULL,

    "SmtpUsername" CHARACTER VARYING(200) NOT NULL,

    "SmtpPasswordEncrypted" CHARACTER VARYING(500) NOT NULL,

    "FromEmail" CHARACTER VARYING(200) NOT NULL,

    "FromName" CHARACTER VARYING(100) NOT NULL,

    "IsActive" BOOLEAN NOT NULL DEFAULT TRUE,

    "IsDefault" BOOLEAN NOT NULL DEFAULT FALSE,

    "SecrateKey" CHARACTER VARYING(500) NOT NULL,

    "CreatedDateTime"
        TIMESTAMP WITHOUT TIME ZONE
        NOT NULL
        DEFAULT CURRENT_TIMESTAMP,

    "UpdatedDateTime"
        TIMESTAMP WITHOUT TIME ZONE NULL
);


-- ============================================================================
-- SECTION 2 : SAFE TABLE UPGRADE
-- ============================================================================

ALTER TABLE axionpro."DefaultEmailConfig"
ADD COLUMN IF NOT EXISTS
    "IsDefault" BOOLEAN NOT NULL DEFAULT FALSE;


-- ============================================================================
-- SMTP PORT VALIDATION
-- ============================================================================

DO
$$
BEGIN

    IF NOT EXISTS
    (
        SELECT 1
        FROM pg_constraint
        WHERE conname = 'CK_DefaultEmailConfig_SmtpPort'
          AND conrelid = 'axionpro."DefaultEmailConfig"'::regclass
    )
    THEN

        ALTER TABLE axionpro."DefaultEmailConfig"
        ADD CONSTRAINT "CK_DefaultEmailConfig_SmtpPort"
        CHECK ("SmtpPort" BETWEEN 1 AND 65535);

    END IF;

END;
$$;


-- ============================================================================
-- CONFIG NAME UNIQUE CONSTRAINT
-- ============================================================================

DO
$$
BEGIN

    IF NOT EXISTS
    (
        SELECT 1
        FROM pg_constraint
        WHERE conname = 'UX_DefaultEmailConfig_ConfigName'
          AND conrelid = 'axionpro."DefaultEmailConfig"'::regclass
    )
    THEN

        ALTER TABLE axionpro."DefaultEmailConfig"
        ADD CONSTRAINT "UX_DefaultEmailConfig_ConfigName"
        UNIQUE ("ConfigName");

    END IF;

END;
$$;


-- ============================================================================
-- ONLY ONE DEFAULT SMTP CONFIGURATION
-- ============================================================================

DROP INDEX IF EXISTS
axionpro."UX_DefaultEmailConfig_OneActive";


CREATE UNIQUE INDEX IF NOT EXISTS
"UX_DefaultEmailConfig_OneDefault"
ON axionpro."DefaultEmailConfig"
(
    "IsDefault"
)
WHERE "IsDefault" = TRUE;


-- ============================================================================
-- SECTION 3 : SEED DEFAULT EMAIL CONFIGURATION
-- ============================================================================
--
-- Latest complete active TenantEmailConfig configuration ko source banaya jayega.
--
-- Isliye production SQL me:
-- Password
-- Secret
-- SMTP Username
--
-- manually paste nahi karna padega.
-- ============================================================================

DO
$$
BEGIN

    INSERT INTO axionpro."DefaultEmailConfig"
    (
        "ConfigName",
        "SmtpHost",
        "SmtpPort",
        "SmtpUsername",
        "SmtpPasswordEncrypted",
        "FromEmail",
        "FromName",
        "IsActive",
        "IsDefault",
        "SecrateKey"
    )

    SELECT

        'DEFAULT_REGISTRATION_SMTP',

        BTRIM(configuration."SmtpHost"),

        configuration."SmtpPort",

        BTRIM(configuration."SmtpUsername"),

        COALESCE
        (
            NULLIF
            (
                BTRIM(configuration."SmtpPasswordEncrypted"),
                ''
            ),

            NULLIF
            (
                BTRIM(configuration."SecrateKey"),
                ''
            )
        ),

        BTRIM(configuration."FromEmail"),

        BTRIM(configuration."FromName"),

        TRUE,

        NOT EXISTS
        (
            SELECT 1

            FROM axionpro."DefaultEmailConfig"
                existingDefault

            WHERE existingDefault."IsDefault" = TRUE
        ),

        COALESCE
        (
            NULLIF
            (
                BTRIM(configuration."SecrateKey"),
                ''
            ),

            NULLIF
            (
                BTRIM(configuration."SmtpPasswordEncrypted"),
                ''
            )
        )

    FROM axionpro."TenantEmailConfig"
        configuration

    WHERE configuration."IsActive" = TRUE

      AND NULLIF
          (
              BTRIM(configuration."SmtpHost"),
              ''
          ) IS NOT NULL

      AND configuration."SmtpPort"
          BETWEEN 1 AND 65535

      AND NULLIF
          (
              BTRIM(configuration."SmtpUsername"),
              ''
          ) IS NOT NULL

      AND COALESCE
          (
              NULLIF
              (
                  BTRIM(configuration."SmtpPasswordEncrypted"),
                  ''
              ),

              NULLIF
              (
                  BTRIM(configuration."SecrateKey"),
                  ''
              )
          ) IS NOT NULL

      AND NULLIF
          (
              BTRIM(configuration."FromEmail"),
              ''
          ) IS NOT NULL

      AND NULLIF
          (
              BTRIM(configuration."FromName"),
              ''
          ) IS NOT NULL

    ORDER BY configuration."Id" DESC

    LIMIT 1


    ON CONFLICT ("ConfigName")

    DO UPDATE SET

        "SmtpHost"
            = EXCLUDED."SmtpHost",

        "SmtpPort"
            = EXCLUDED."SmtpPort",

        "SmtpUsername"
            = EXCLUDED."SmtpUsername",

        "SmtpPasswordEncrypted"
            = EXCLUDED."SmtpPasswordEncrypted",

        "FromEmail"
            = EXCLUDED."FromEmail",

        "FromName"
            = EXCLUDED."FromName",

        "IsActive"
            = TRUE,

        "SecrateKey"
            = EXCLUDED."SecrateKey",

        "UpdatedDateTime"
            = CURRENT_TIMESTAMP;


    IF NOT FOUND THEN

        RAISE EXCEPTION
        'No complete active TenantEmailConfig found. DefaultEmailConfig could not be seeded.';

    END IF;

END;
$$;


-- ============================================================================
-- DEFAULT CONFIG MARK
-- ============================================================================
--
-- Agar pehle se koi IsDefault = true nahi hai,
-- to DEFAULT_REGISTRATION_SMTP ko default bana diya jayega.
-- ============================================================================

UPDATE axionpro."DefaultEmailConfig"
SET
    "IsDefault" = TRUE,

    "UpdatedDateTime" = CURRENT_TIMESTAMP

WHERE "ConfigName" = 'DEFAULT_REGISTRATION_SMTP'

  AND "IsActive" = TRUE

  AND "IsDefault" = FALSE

  AND NOT EXISTS
  (
      SELECT 1

      FROM axionpro."DefaultEmailConfig"

      WHERE "IsDefault" = TRUE
  );


-- ============================================================================
-- SECTION 4
-- HOST MODULE : DEFAULT EMAIL CONFIGURATION
-- ============================================================================
--
-- ModuleScope = 2
-- Host Admin module
--
-- Purpose:
-- New Tenant registration ke waqt selected/default SMTP configuration
-- TenantEmailConfig me copy hogi.
-- ============================================================================


-- ---------------------------------------------------------------------------
-- Existing module hai to usko complete/normalize karo.
-- ---------------------------------------------------------------------------

UPDATE axionpro."Module"

SET

    "TenantId" = NULL,

    "ModuleName"
        = 'Default Email Configuration',

    "DisplayName"
        = 'Default Email Configuration',

    "URLPath"
        = '/app/default-email-config',

    "ParentModuleId"
        = NULL,

    "IsLeafNode"
        = TRUE,

    "IsModuleDisplayInUI"
        = TRUE,

    "IsCommonMenu"
        = FALSE,

    "IsActive"
        = TRUE,

    "ImageIconWeb"
        = 'bi bi-envelope-gear',

    "ImageIconMobile"
        = 'mail-settings',

    "ItemPriority"
        = 10,

    "Remark"
        = 'Host-managed SMTP configuration used as the default email configuration when a new tenant is registered.',

    "UpdatedById"
        = 1,

    "UpdatedDateTime"
        = CURRENT_TIMESTAMP,

    "ModuleScope"
        = 2

WHERE "ModuleCode"
    = 'HOST_DEFAULT_EMAIL_CONFIG';


-- ---------------------------------------------------------------------------
-- Existing module nahi hai to create karo.
-- Id explicitly nahi diya gaya hai.
-- PostgreSQL identity automatically next Id generate karega.
-- ---------------------------------------------------------------------------

INSERT INTO axionpro."Module"
(
    "TenantId",

    "ModuleCode",

    "ModuleName",

    "DisplayName",

    "URLPath",

    "ParentModuleId",

    "IsLeafNode",

    "IsModuleDisplayInUI",

    "IsCommonMenu",

    "IsActive",

    "ImageIconWeb",

    "ImageIconMobile",

    "ItemPriority",

    "Remark",

    "AddedById",

    "AddedDateTime",

    "UpdatedById",

    "UpdatedDateTime",

    "ModuleScope"
)

SELECT

    NULL,

    'HOST_DEFAULT_EMAIL_CONFIG',

    'Default Email Configuration',

    'Default Email Configuration',

    '/app/default-email-config',

    NULL,

    TRUE,

    TRUE,

    FALSE,

    TRUE,

    'bi bi-envelope-gear',

    'mail-settings',

    10,

    'Host-managed SMTP configuration used as the default email configuration when a new tenant is registered.',

    1,

    CURRENT_TIMESTAMP,

    NULL,

    NULL,

    2

WHERE NOT EXISTS
(
    SELECT 1

    FROM axionpro."Module"

    WHERE "ModuleCode"
        = 'HOST_DEFAULT_EMAIL_CONFIG'
);


-- ============================================================================
-- SECTION 5
-- TENANT MODULE : TENANT EMAIL CONFIGURATION
-- ============================================================================
--
-- ModuleScope = 1
--
-- APIs:
--
-- POST
-- /api/TenantEmailConfig/create
--
-- GET
-- /api/TenantEmailConfig/get-all
--
-- GET
-- /api/TenantEmailConfig/get-by-id/{id}
--
-- POST
-- /api/TenantEmailConfig/update
--
-- DELETE
-- /api/TenantEmailConfig/delete/{id}
--
-- ============================================================================


-- ---------------------------------------------------------------------------
-- Existing module normalize/update.
-- ---------------------------------------------------------------------------

UPDATE axionpro."Module"

SET

    "TenantId"
        = NULL,

    "ModuleName"
        = 'Tenant Email Configuration',

    "DisplayName"
        = 'Email Configuration',

    "URLPath"
        = '/app/tenant-email-config',

    "ParentModuleId"
        = NULL,

    "IsLeafNode"
        = TRUE,

    "IsModuleDisplayInUI"
        = TRUE,

    "IsCommonMenu"
        = FALSE,

    "IsActive"
        = TRUE,

    "ImageIconWeb"
        = 'bi bi-envelope-at',

    "ImageIconMobile"
        = 'mail',

    "ItemPriority"
        = 10,

    "Remark"
        = 'Tenant-specific SMTP configuration used for transactional, notification and system email delivery.',

    "UpdatedById"
        = 1,

    "UpdatedDateTime"
        = CURRENT_TIMESTAMP,

    "ModuleScope"
        = 1

WHERE "ModuleCode"
    = 'TENANT_EMAIL_CONFIG';


-- ---------------------------------------------------------------------------
-- Create when missing.
-- ---------------------------------------------------------------------------

INSERT INTO axionpro."Module"
(
    "TenantId",

    "ModuleCode",

    "ModuleName",

    "DisplayName",

    "URLPath",

    "ParentModuleId",

    "IsLeafNode",

    "IsModuleDisplayInUI",

    "IsCommonMenu",

    "IsActive",

    "ImageIconWeb",

    "ImageIconMobile",

    "ItemPriority",

    "Remark",

    "AddedById",

    "AddedDateTime",

    "UpdatedById",

    "UpdatedDateTime",

    "ModuleScope"
)

SELECT

    NULL,

    'TENANT_EMAIL_CONFIG',

    'Tenant Email Configuration',

    'Email Configuration',

    '/app/tenant-email-config',

    NULL,

    TRUE,

    TRUE,

    FALSE,

    TRUE,

    'bi bi-envelope-at',

    'mail',

    10,

    'Tenant-specific SMTP configuration used for transactional, notification and system email delivery.',

    1,

    CURRENT_TIMESTAMP,

    NULL,

    NULL,

    1

WHERE NOT EXISTS
(
    SELECT 1

    FROM axionpro."Module"

    WHERE "ModuleCode"
        = 'TENANT_EMAIL_CONFIG'
);


-- ============================================================================
-- SECTION 6
-- HOST DEFAULT EMAIL CONFIG MODULE OPERATION MAPPING
-- ============================================================================
--
-- Existing Operation master reuse hoga.
--
-- Supported operation names:
--
-- View / Read
-- Create / Add
-- Update / Edit
-- Delete
--
-- ============================================================================

INSERT INTO axionpro."ModuleOperationMapping"
(
    "ModuleId",

    "OperationId",

    "IsCommonItem",

    "IsOperational",

    "Priority",

    "Remark",

    "IsActive",

    "AddedById",

    "AddedDateTime"
)

SELECT

    module."Id",

    operation."Id",

    FALSE,

    TRUE,

    CASE

        WHEN LOWER(BTRIM(operation."OperationName"))
             IN ('view', 'read')
            THEN 1

        WHEN LOWER(BTRIM(operation."OperationName"))
             IN ('create', 'add')
            THEN 2

        WHEN LOWER(BTRIM(operation."OperationName"))
             IN ('update', 'edit')
            THEN 3

        WHEN LOWER(BTRIM(operation."OperationName"))
             = 'delete'
            THEN 4

        ELSE 10

    END,

    CASE

        WHEN LOWER(BTRIM(operation."OperationName"))
             IN ('view', 'read')

            THEN
            'View Host default email configuration.'

        WHEN LOWER(BTRIM(operation."OperationName"))
             IN ('create', 'add')

            THEN
            'Create Host default email configuration.'

        WHEN LOWER(BTRIM(operation."OperationName"))
             IN ('update', 'edit')

            THEN
            'Update Host default email configuration.'

        WHEN LOWER(BTRIM(operation."OperationName"))
             = 'delete'

            THEN
            'Delete Host default email configuration.'

        ELSE
            'Host default email configuration operation.'

    END,

    TRUE,

    1,

    CURRENT_TIMESTAMP

FROM axionpro."Module" module

INNER JOIN axionpro."Operation" operation

    ON LOWER(BTRIM(operation."OperationName"))

       IN
       (
           'view',
           'read',
           'create',
           'add',
           'update',
           'edit',
           'delete'
       )

WHERE module."ModuleCode"
      = 'HOST_DEFAULT_EMAIL_CONFIG'

  AND operation."IsActive"
      = TRUE

  AND NOT EXISTS
  (
      SELECT 1

      FROM axionpro."ModuleOperationMapping"
          existingMapping

      WHERE existingMapping."ModuleId"
            = module."Id"

        AND existingMapping."OperationId"
            = operation."Id"
  );


-- ============================================================================
-- SECTION 7
-- TENANT EMAIL CONFIG MODULE OPERATION MAPPING
-- ============================================================================

INSERT INTO axionpro."ModuleOperationMapping"
(
    "ModuleId",

    "OperationId",

    "IsCommonItem",

    "IsOperational",

    "Priority",

    "Remark",

    "IsActive",

    "AddedById",

    "AddedDateTime"
)

SELECT

    module."Id",

    operation."Id",

    FALSE,

    TRUE,

    CASE

        WHEN LOWER(BTRIM(operation."OperationName"))
             IN ('view', 'read')
            THEN 1

        WHEN LOWER(BTRIM(operation."OperationName"))
             IN ('create', 'add')
            THEN 2

        WHEN LOWER(BTRIM(operation."OperationName"))
             IN ('update', 'edit')
            THEN 3

        WHEN LOWER(BTRIM(operation."OperationName"))
             = 'delete'
            THEN 4

        ELSE 10

    END,

    CASE

        WHEN LOWER(BTRIM(operation."OperationName"))
             IN ('view', 'read')

            THEN
            'View Tenant email configuration.'

        WHEN LOWER(BTRIM(operation."OperationName"))
             IN ('create', 'add')

            THEN
            'Create Tenant email configuration.'

        WHEN LOWER(BTRIM(operation."OperationName"))
             IN ('update', 'edit')

            THEN
            'Update Tenant email configuration.'

        WHEN LOWER(BTRIM(operation."OperationName"))
             = 'delete'

            THEN
            'Delete Tenant email configuration.'

        ELSE
            'Tenant email configuration operation.'

    END,

    TRUE,

    1,

    CURRENT_TIMESTAMP

FROM axionpro."Module" module

INNER JOIN axionpro."Operation" operation

    ON LOWER(BTRIM(operation."OperationName"))

       IN
       (
           'view',
           'read',
           'create',
           'add',
           'update',
           'edit',
           'delete'
       )

WHERE module."ModuleCode"
      = 'TENANT_EMAIL_CONFIG'

  AND operation."IsActive"
      = TRUE

  AND NOT EXISTS
  (
      SELECT 1

      FROM axionpro."ModuleOperationMapping"
          existingMapping

      WHERE existingMapping."ModuleId"
            = module."Id"

        AND existingMapping."OperationId"
            = operation."Id"
  );


-- ============================================================================
-- SECTION 8
-- NORMALIZE EXISTING MODULE OPERATION MAPPINGS
-- ============================================================================

UPDATE axionpro."ModuleOperationMapping"
    mapping

SET

    "IsCommonItem"
        = FALSE,

    "IsOperational"
        = TRUE,

    "Priority"
        =
        CASE

            WHEN LOWER(BTRIM(operation."OperationName"))
                 IN ('view', 'read')
                THEN 1

            WHEN LOWER(BTRIM(operation."OperationName"))
                 IN ('create', 'add')
                THEN 2

            WHEN LOWER(BTRIM(operation."OperationName"))
                 IN ('update', 'edit')
                THEN 3

            WHEN LOWER(BTRIM(operation."OperationName"))
                 = 'delete'
                THEN 4

            ELSE mapping."Priority"

        END,

    "Remark"
        =
        CASE

            WHEN module."ModuleCode"
                 = 'HOST_DEFAULT_EMAIL_CONFIG'

                 AND LOWER(BTRIM(operation."OperationName"))
                     IN ('view', 'read')

                THEN
                'View Host default email configuration.'


            WHEN module."ModuleCode"
                 = 'HOST_DEFAULT_EMAIL_CONFIG'

                 AND LOWER(BTRIM(operation."OperationName"))
                     IN ('create', 'add')

                THEN
                'Create Host default email configuration.'


            WHEN module."ModuleCode"
                 = 'HOST_DEFAULT_EMAIL_CONFIG'

                 AND LOWER(BTRIM(operation."OperationName"))
                     IN ('update', 'edit')

                THEN
                'Update Host default email configuration.'


            WHEN module."ModuleCode"
                 = 'HOST_DEFAULT_EMAIL_CONFIG'

                 AND LOWER(BTRIM(operation."OperationName"))
                     = 'delete'

                THEN
                'Delete Host default email configuration.'


            WHEN module."ModuleCode"
                 = 'TENANT_EMAIL_CONFIG'

                 AND LOWER(BTRIM(operation."OperationName"))
                     IN ('view', 'read')

                THEN
                'View Tenant email configuration.'


            WHEN module."ModuleCode"
                 = 'TENANT_EMAIL_CONFIG'

                 AND LOWER(BTRIM(operation."OperationName"))
                     IN ('create', 'add')

                THEN
                'Create Tenant email configuration.'


            WHEN module."ModuleCode"
                 = 'TENANT_EMAIL_CONFIG'

                 AND LOWER(BTRIM(operation."OperationName"))
                     IN ('update', 'edit')

                THEN
                'Update Tenant email configuration.'


            WHEN module."ModuleCode"
                 = 'TENANT_EMAIL_CONFIG'

                 AND LOWER(BTRIM(operation."OperationName"))
                     = 'delete'

                THEN
                'Delete Tenant email configuration.'


            ELSE mapping."Remark"

        END,

    "IsActive"
        = TRUE

FROM axionpro."Module"
    module,

     axionpro."Operation"
    operation

WHERE mapping."ModuleId"
      = module."Id"

  AND mapping."OperationId"
      = operation."Id"

  AND module."ModuleCode"
      IN
      (
          'HOST_DEFAULT_EMAIL_CONFIG',
          'TENANT_EMAIL_CONFIG'
      );


-- ============================================================================
-- SECTION 9
-- PRODUCTION VALIDATION
-- ============================================================================
--
-- Agar required module ya operation mapping create nahi hui
-- to transaction COMMIT nahi hogi.
-- ============================================================================

DO
$$
DECLARE

    host_module_count INTEGER;

    tenant_module_count INTEGER;

    host_mapping_count INTEGER;

    tenant_mapping_count INTEGER;

BEGIN

    SELECT COUNT(*)

    INTO host_module_count

    FROM axionpro."Module"

    WHERE "ModuleCode"
          = 'HOST_DEFAULT_EMAIL_CONFIG';


    SELECT COUNT(*)

    INTO tenant_module_count

    FROM axionpro."Module"

    WHERE "ModuleCode"
          = 'TENANT_EMAIL_CONFIG';


    IF host_module_count <> 1 THEN

        RAISE EXCEPTION
        'Expected exactly one HOST_DEFAULT_EMAIL_CONFIG module. Found: %',
        host_module_count;

    END IF;


    IF tenant_module_count <> 1 THEN

        RAISE EXCEPTION
        'Expected exactly one TENANT_EMAIL_CONFIG module. Found: %',
        tenant_module_count;

    END IF;


    SELECT COUNT(*)

    INTO host_mapping_count

    FROM axionpro."ModuleOperationMapping"
        mapping

    INNER JOIN axionpro."Module"
        module

        ON module."Id"
           = mapping."ModuleId"

    WHERE module."ModuleCode"
          = 'HOST_DEFAULT_EMAIL_CONFIG'

      AND mapping."IsActive"
          = TRUE;


    SELECT COUNT(*)

    INTO tenant_mapping_count

    FROM axionpro."ModuleOperationMapping"
        mapping

    INNER JOIN axionpro."Module"
        module

        ON module."Id"
           = mapping."ModuleId"

    WHERE module."ModuleCode"
          = 'TENANT_EMAIL_CONFIG'

      AND mapping."IsActive"
          = TRUE;


    IF host_mapping_count = 0 THEN

        RAISE EXCEPTION
        'No CRUD Operation mapping found for HOST_DEFAULT_EMAIL_CONFIG. Check Operation master data.';

    END IF;


    IF tenant_mapping_count = 0 THEN

        RAISE EXCEPTION
        'No CRUD Operation mapping found for TENANT_EMAIL_CONFIG. Check Operation master data.';

    END IF;

END;
$$;


-- ============================================================================
-- SECTION 10
-- SAFE AUTO-INCREMENT / IDENTITY SYNCHRONIZATION
-- ============================================================================
--
-- IMPORTANT:
--
-- Empty table:
--     next ID = 1
--
-- Existing table:
--     next ID = MAX(Id) + 1
--
-- Existing production IDs kabhi backward reset nahi honge.
-- ============================================================================

DO
$$
DECLARE

    sequence_name TEXT;

    maximum_id BIGINT;

BEGIN


    -- ========================================================================
    -- DefaultEmailConfig
    -- ========================================================================

    sequence_name :=
        pg_get_serial_sequence
        (
            'axionpro."DefaultEmailConfig"',
            'Id'
        );


    IF sequence_name IS NOT NULL THEN

        SELECT COALESCE(MAX("Id"), 0)

        INTO maximum_id

        FROM axionpro."DefaultEmailConfig";


        IF maximum_id = 0 THEN

            PERFORM setval
            (
                sequence_name::regclass,
                1,
                FALSE
            );

        ELSE

            PERFORM setval
            (
                sequence_name::regclass,
                maximum_id,
                TRUE
            );

        END IF;

    END IF;



    -- ========================================================================
    -- Module
    -- ========================================================================

    sequence_name :=
        pg_get_serial_sequence
        (
            'axionpro."Module"',
            'Id'
        );


    IF sequence_name IS NOT NULL THEN

        SELECT COALESCE(MAX("Id"), 0)

        INTO maximum_id

        FROM axionpro."Module";


        IF maximum_id = 0 THEN

            PERFORM setval
            (
                sequence_name::regclass,
                1,
                FALSE
            );

        ELSE

            PERFORM setval
            (
                sequence_name::regclass,
                maximum_id,
                TRUE
            );

        END IF;

    END IF;



    -- ========================================================================
    -- ModuleOperationMapping
    -- ========================================================================

    sequence_name :=
        pg_get_serial_sequence
        (
            'axionpro."ModuleOperationMapping"',
            'Id'
        );


    IF sequence_name IS NOT NULL THEN

        SELECT COALESCE(MAX("Id"), 0)

        INTO maximum_id

        FROM axionpro."ModuleOperationMapping";


        IF maximum_id = 0 THEN

            PERFORM setval
            (
                sequence_name::regclass,
                1,
                FALSE
            );

        ELSE

            PERFORM setval
            (
                sequence_name::regclass,
                maximum_id,
                TRUE
            );

        END IF;

    END IF;

END;
$$;


-- ============================================================================
-- EVERYTHING SUCCESSFUL
-- ============================================================================

COMMIT;


-- ============================================================================
-- VERIFICATION 1
-- DEFAULT EMAIL CONFIGURATION
-- ============================================================================
--
-- Password / Secret intentionally SELECT nahi kiya gaya.
-- ============================================================================

SELECT

    "Id",

    "ConfigName",

    "SmtpHost",

    "SmtpPort",

    "SmtpUsername",

    "FromEmail",

    "FromName",

    "IsActive",

    "IsDefault",

    "CreatedDateTime",

    "UpdatedDateTime"

FROM axionpro."DefaultEmailConfig"

ORDER BY "Id";


-- ============================================================================
-- VERIFICATION 2
-- BOTH MODULES WITH ALL CURRENT MODULE PROPERTIES
-- ============================================================================

SELECT

    "Id",

    "TenantId",

    "ModuleCode",

    "ModuleName",

    "DisplayName",

    "URLPath",

    "ParentModuleId",

    "IsLeafNode",

    "IsModuleDisplayInUI",

    "IsCommonMenu",

    "IsActive",

    "ImageIconWeb",

    "ImageIconMobile",

    "ItemPriority",

    "Remark",

    "AddedById",

    "AddedDateTime",

    "UpdatedById",

    "UpdatedDateTime",

    "ModuleScope"

FROM axionpro."Module"

WHERE "ModuleCode"
      IN
      (
          'HOST_DEFAULT_EMAIL_CONFIG',
          'TENANT_EMAIL_CONFIG'
      )

ORDER BY
    "ModuleScope",
    "Id";


-- ============================================================================
-- VERIFICATION 3
-- MODULE OPERATION MAPPINGS
-- ============================================================================

SELECT

    module."Id"
        AS "ModuleId",

    module."ModuleCode",

    module."ModuleName",

    module."ModuleScope",

    operation."Id"
        AS "OperationId",

    operation."OperationName",

    mapping."Priority",

    mapping."IsCommonItem",

    mapping."IsOperational",

    mapping."Remark",

    mapping."IsActive"

FROM axionpro."ModuleOperationMapping"
    mapping

INNER JOIN axionpro."Module"
    module

    ON module."Id"
       = mapping."ModuleId"

INNER JOIN axionpro."Operation"
    operation

    ON operation."Id"
       = mapping."OperationId"

WHERE module."ModuleCode"
      IN
      (
          'HOST_DEFAULT_EMAIL_CONFIG',
          'TENANT_EMAIL_CONFIG'
      )

ORDER BY

    module."ModuleScope",

    module."ModuleCode",

    mapping."Priority",

    operation."OperationName";