/*
  Generic, tenant-isolated policy framework.
  PostgreSQL / pgAdmin compatible and safe to rerun.
  This phase creates persistence only; controllers/endpoints are deliberately deferred.
*/

BEGIN;
SET LOCAL lock_timeout = '20s';
SET LOCAL statement_timeout = '300s';

CREATE TABLE IF NOT EXISTS axionpro."PolicyCategory"
(
    "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "CategoryCode" varchar(50) NOT NULL,
    "CategoryName" varchar(100) NOT NULL,
    "Description" varchar(500),
    "IsActive" boolean NOT NULL DEFAULT true,
    "AddedById" bigint,
    "AddedDateTime" timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "UpdatedById" bigint,
    "UpdatedDateTime" timestamptz,
    CONSTRAINT "UQ_PolicyCategory_Code" UNIQUE ("CategoryCode")
);

CREATE TABLE IF NOT EXISTS axionpro."PolicyStatus"
(
    "Id" smallint PRIMARY KEY,
    "StatusCode" varchar(30) NOT NULL,
    "StatusName" varchar(50) NOT NULL,
    "IsTerminal" boolean NOT NULL DEFAULT false,
    "IsActive" boolean NOT NULL DEFAULT true,
    CONSTRAINT "UQ_PolicyStatus_Code" UNIQUE ("StatusCode")
);

CREATE TABLE IF NOT EXISTS axionpro."PolicyRuleType"
(
    "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "RuleTypeCode" varchar(50) NOT NULL,
    "RuleTypeName" varchar(100) NOT NULL,
    "Description" varchar(500),
    "JsonSchemaVersion" integer NOT NULL DEFAULT 1,
    "IsActive" boolean NOT NULL DEFAULT true,
    CONSTRAINT "UQ_PolicyRuleType_Code" UNIQUE ("RuleTypeCode")
);

CREATE TABLE IF NOT EXISTS axionpro."PolicyDocumentType"
(
    "Id" smallint PRIMARY KEY,
    "DocumentTypeCode" varchar(30) NOT NULL,
    "DocumentTypeName" varchar(100) NOT NULL,
    "IsActive" boolean NOT NULL DEFAULT true,
    CONSTRAINT "UQ_PolicyDocumentType_Code" UNIQUE ("DocumentTypeCode")
);

CREATE TABLE IF NOT EXISTS axionpro."PolicyType"
(
    "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "TenantId" bigint,
    "PolicyName" varchar(150) NOT NULL,
    "Description" varchar(500),
    "IsActive" boolean DEFAULT true,
    "IsSoftDelete" boolean DEFAULT false,
    "AddedById" bigint,
    "AddedDateTime" timestamptz DEFAULT CURRENT_TIMESTAMP,
    "UpdateById" bigint,
    "UpdateDateTime" timestamptz,
    "SoftDeleteById" bigint,
    "SoftDeleteDateTime" timestamptz,
    "IsStructured" boolean NOT NULL DEFAULT true,
    "PolicyTypeEnumVal" integer NOT NULL DEFAULT 0,
    "HasPolicyDocUploaded" boolean NOT NULL DEFAULT false,
    "PolicyCategoryId" integer,
    "PolicyTypeCode" varchar(50),
    "DefaultCurrencyCode" varchar(3)
);

ALTER TABLE axionpro."PolicyType"
    ADD COLUMN IF NOT EXISTS "PolicyCategoryId" integer,
    ADD COLUMN IF NOT EXISTS "PolicyTypeCode" varchar(50),
    ADD COLUMN IF NOT EXISTS "DefaultCurrencyCode" varchar(3);

CREATE TABLE IF NOT EXISTS axionpro."Policy"
(
    "Id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "TenantId" bigint NOT NULL,
    "PolicyTypeId" integer NOT NULL,
    "PolicyCode" varchar(50) NOT NULL,
    "PolicyName" varchar(200) NOT NULL,
    "Summary" varchar(1000),
    "OwnerDepartmentId" integer,
    "DefaultCurrencyCode" varchar(3),
    "IsActive" boolean NOT NULL DEFAULT true,
    "IsSoftDeleted" boolean NOT NULL DEFAULT false,
    "AddedById" bigint NOT NULL,
    "AddedDateTime" timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "UpdatedById" bigint,
    "UpdatedDateTime" timestamptz,
    "SoftDeletedById" bigint,
    "SoftDeletedDateTime" timestamptz,
    CONSTRAINT "UQ_Policy_Tenant_Code" UNIQUE ("TenantId", "PolicyCode")
);

CREATE TABLE IF NOT EXISTS axionpro."PolicyVersion"
(
    "Id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "TenantId" bigint NOT NULL,
    "PolicyId" bigint NOT NULL,
    "VersionNumber" integer NOT NULL,
    "PolicyStatusId" smallint NOT NULL,
    "EffectiveFrom" date NOT NULL,
    "EffectiveTo" date,
    "ChangeSummary" varchar(1000),
    "RuleSchemaVersion" integer NOT NULL DEFAULT 1,
    "ApprovedById" bigint,
    "ApprovedDateTime" timestamptz,
    "PublishedById" bigint,
    "PublishedDateTime" timestamptz,
    "IsCurrent" boolean NOT NULL DEFAULT false,
    "IsActive" boolean NOT NULL DEFAULT true,
    "AddedById" bigint NOT NULL,
    "AddedDateTime" timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "UpdatedById" bigint,
    "UpdatedDateTime" timestamptz,
    CONSTRAINT "UQ_PolicyVersion_Policy_Version" UNIQUE ("PolicyId", "VersionNumber"),
    CONSTRAINT "CK_PolicyVersion_EffectiveDates" CHECK ("EffectiveTo" IS NULL OR "EffectiveTo" >= "EffectiveFrom")
);

CREATE TABLE IF NOT EXISTS axionpro."PolicyRule"
(
    "Id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "TenantId" bigint NOT NULL,
    "PolicyVersionId" bigint NOT NULL,
    "PolicyRuleTypeId" integer NOT NULL,
    "RuleName" varchar(150) NOT NULL,
    "RuleOrder" integer NOT NULL DEFAULT 1,
    "RuleConfiguration" jsonb NOT NULL,
    "IsActive" boolean NOT NULL DEFAULT true,
    "AddedById" bigint NOT NULL,
    "AddedDateTime" timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "UpdatedById" bigint,
    "UpdatedDateTime" timestamptz,
    CONSTRAINT "CK_PolicyRule_ConfigurationObject" CHECK (jsonb_typeof("RuleConfiguration") = 'object'),
    CONSTRAINT "UQ_PolicyRule_Version_Order" UNIQUE ("PolicyVersionId", "RuleOrder")
);

CREATE TABLE IF NOT EXISTS axionpro."PolicyApplicability"
(
    "Id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "TenantId" bigint NOT NULL,
    "PolicyVersionId" bigint NOT NULL,
    "ApplicabilityMode" smallint NOT NULL DEFAULT 1,
    "CountryId" integer,
    "StateId" integer,
    "DistrictId" integer,
    "LocalityId" integer,
    "TenantLocationId" bigint,
    "EmployeeTypeId" integer,
    "DepartmentId" integer,
    "DesignationId" integer,
    "EmployeeId" bigint,
    "GenderId" integer,
    "WorkArrangementType" smallint,
    "EmploymentStatus" smallint,
    "MinimumServiceDays" integer,
    "Priority" integer NOT NULL DEFAULT 100,
    "EffectiveFrom" date NOT NULL,
    "EffectiveTo" date,
    "IsActive" boolean NOT NULL DEFAULT true,
    "AddedById" bigint NOT NULL,
    "AddedDateTime" timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "UpdatedById" bigint,
    "UpdatedDateTime" timestamptz,
    CONSTRAINT "CK_PolicyApplicability_Mode" CHECK ("ApplicabilityMode" IN (1, 2)),
    CONSTRAINT "CK_PolicyApplicability_Dates" CHECK ("EffectiveTo" IS NULL OR "EffectiveTo" >= "EffectiveFrom"),
    CONSTRAINT "CK_PolicyApplicability_Service" CHECK ("MinimumServiceDays" IS NULL OR "MinimumServiceDays" >= 0)
);

CREATE TABLE IF NOT EXISTS axionpro."PolicyAssignment"
(
    "Id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "TenantId" bigint NOT NULL,
    "PolicyVersionId" bigint NOT NULL,
    "EmployeeId" bigint NOT NULL,
    "AssignmentSource" smallint NOT NULL DEFAULT 1,
    "SourceApplicabilityId" bigint,
    "EffectiveFrom" date NOT NULL,
    "EffectiveTo" date,
    "IsMandatory" boolean NOT NULL DEFAULT true,
    "IsActive" boolean NOT NULL DEFAULT true,
    "AssignedById" bigint NOT NULL,
    "AssignedDateTime" timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "RemovedById" bigint,
    "RemovedDateTime" timestamptz,
    CONSTRAINT "CK_PolicyAssignment_Dates" CHECK ("EffectiveTo" IS NULL OR "EffectiveTo" >= "EffectiveFrom"),
    CONSTRAINT "UQ_PolicyAssignment_Version_Employee_From" UNIQUE ("PolicyVersionId", "EmployeeId", "EffectiveFrom")
);

CREATE TABLE IF NOT EXISTS axionpro."PolicyException"
(
    "Id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "TenantId" bigint NOT NULL,
    "PolicyVersionId" bigint NOT NULL,
    "EmployeeId" bigint NOT NULL,
    "ExceptionType" smallint NOT NULL,
    "OverrideConfiguration" jsonb NOT NULL DEFAULT '{}'::jsonb,
    "Reason" varchar(1000) NOT NULL,
    "EffectiveFrom" date NOT NULL,
    "EffectiveTo" date NOT NULL,
    "ApprovalStatusId" smallint NOT NULL DEFAULT 2,
    "ApprovedById" bigint,
    "ApprovedDateTime" timestamptz,
    "IsActive" boolean NOT NULL DEFAULT true,
    "AddedById" bigint NOT NULL,
    "AddedDateTime" timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT "CK_PolicyException_Dates" CHECK ("EffectiveTo" >= "EffectiveFrom"),
    CONSTRAINT "CK_PolicyException_ConfigurationObject" CHECK (jsonb_typeof("OverrideConfiguration") = 'object')
);

CREATE TABLE IF NOT EXISTS axionpro."PolicyDocument"
(
    "Id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "TenantId" bigint NOT NULL,
    "PolicyVersionId" bigint NOT NULL,
    "PolicyDocumentTypeId" smallint NOT NULL,
    "DocumentTitle" varchar(200) NOT NULL,
    "OriginalFileName" varchar(255) NOT NULL,
    "StorageProvider" varchar(30) NOT NULL,
    "ObjectKey" varchar(1000) NOT NULL,
    "ContentType" varchar(100) NOT NULL,
    "FileSizeBytes" bigint NOT NULL,
    "ChecksumSha256" varchar(64) NOT NULL,
    "LanguageCode" varchar(10),
    "IsEmployeeVisible" boolean NOT NULL DEFAULT true,
    "IsActive" boolean NOT NULL DEFAULT true,
    "IsSoftDeleted" boolean NOT NULL DEFAULT false,
    "AddedById" bigint NOT NULL,
    "AddedDateTime" timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "SoftDeletedById" bigint,
    "SoftDeletedDateTime" timestamptz,
    CONSTRAINT "CK_PolicyDocument_Size" CHECK ("FileSizeBytes" >= 0),
    CONSTRAINT "UQ_PolicyDocument_Version_Object" UNIQUE ("PolicyVersionId", "ObjectKey")
);

CREATE TABLE IF NOT EXISTS axionpro."PolicyApprovalStage"
(
    "Id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "TenantId" bigint NOT NULL,
    "PolicyCategoryId" integer,
    "StageName" varchar(100) NOT NULL,
    "StageOrder" integer NOT NULL,
    "ApproverRoleId" integer,
    "MinimumApprovals" integer NOT NULL DEFAULT 1,
    "IsMandatory" boolean NOT NULL DEFAULT true,
    "IsActive" boolean NOT NULL DEFAULT true,
    "AddedById" bigint NOT NULL,
    "AddedDateTime" timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT "CK_PolicyApprovalStage_Count" CHECK ("MinimumApprovals" > 0),
    CONSTRAINT "UQ_PolicyApprovalStage_Tenant_Category_Order" UNIQUE ("TenantId", "PolicyCategoryId", "StageOrder")
);

CREATE TABLE IF NOT EXISTS axionpro."PolicyApprovalHistory"
(
    "Id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "TenantId" bigint NOT NULL,
    "PolicyVersionId" bigint NOT NULL,
    "PolicyApprovalStageId" bigint NOT NULL,
    "ActionType" smallint NOT NULL,
    "ActionById" bigint NOT NULL,
    "ActionDateTime" timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "Comments" varchar(1000),
    "SequenceNumber" integer NOT NULL,
    CONSTRAINT "UQ_PolicyApprovalHistory_Version_Sequence" UNIQUE ("PolicyVersionId", "SequenceNumber")
);

CREATE TABLE IF NOT EXISTS axionpro."PolicyAcknowledgement"
(
    "Id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "TenantId" bigint NOT NULL,
    "PolicyVersionId" bigint NOT NULL,
    "EmployeeId" bigint NOT NULL,
    "AcknowledgementStatus" smallint NOT NULL DEFAULT 1,
    "AssignedDateTime" timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "ViewedDateTime" timestamptz,
    "AcknowledgedDateTime" timestamptz,
    "SourceIpHash" varchar(64),
    "EvidenceJson" jsonb,
    CONSTRAINT "UQ_PolicyAcknowledgement_Version_Employee" UNIQUE ("PolicyVersionId", "EmployeeId"),
    CONSTRAINT "CK_PolicyAcknowledgement_Evidence" CHECK ("EvidenceJson" IS NULL OR jsonb_typeof("EvidenceJson") = 'object')
);

CREATE TABLE IF NOT EXISTS axionpro."PolicyChangeAudit"
(
    "Id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "TenantId" bigint NOT NULL,
    "PolicyId" bigint NOT NULL,
    "PolicyVersionId" bigint,
    "EntityName" varchar(100) NOT NULL,
    "EntityId" bigint,
    "ActionName" varchar(50) NOT NULL,
    "BeforeData" jsonb,
    "AfterData" jsonb,
    "ChangedById" bigint NOT NULL,
    "ChangedDateTime" timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "CorrelationId" uuid,
    CONSTRAINT "CK_PolicyChangeAudit_Before" CHECK ("BeforeData" IS NULL OR jsonb_typeof("BeforeData") = 'object'),
    CONSTRAINT "CK_PolicyChangeAudit_After" CHECK ("AfterData" IS NULL OR jsonb_typeof("AfterData") = 'object')
);

INSERT INTO axionpro."PolicyStatus" ("Id", "StatusCode", "StatusName", "IsTerminal") VALUES
    (1, 'DRAFT', 'Draft', false), (2, 'UNDER_REVIEW', 'Under Review', false),
    (3, 'APPROVED', 'Approved', false), (4, 'PUBLISHED', 'Published', false),
    (5, 'SUSPENDED', 'Suspended', false), (6, 'ARCHIVED', 'Archived', true),
    (7, 'REJECTED', 'Rejected', true)
ON CONFLICT ("Id") DO UPDATE SET "StatusCode"=EXCLUDED."StatusCode", "StatusName"=EXCLUDED."StatusName", "IsTerminal"=EXCLUDED."IsTerminal", "IsActive"=true;

ALTER TABLE axionpro."PolicyException" ALTER COLUMN "ApprovalStatusId" SET DEFAULT 2;

INSERT INTO axionpro."PolicyDocumentType" ("Id", "DocumentTypeCode", "DocumentTypeName") VALUES
    (1, 'POLICY_DOCUMENT', 'Policy Document'), (2, 'ANNEXURE', 'Annexure'),
    (3, 'LEGAL_CIRCULAR', 'Legal Circular'), (4, 'EMPLOYEE_GUIDE', 'Employee Guide'),
    (5, 'TRANSLATION', 'Translated Policy')
ON CONFLICT ("Id") DO UPDATE SET "DocumentTypeCode"=EXCLUDED."DocumentTypeCode", "DocumentTypeName"=EXCLUDED."DocumentTypeName", "IsActive"=true;

INSERT INTO axionpro."PolicyCategory" ("CategoryCode", "CategoryName", "Description") VALUES
    ('LEAVE', 'Leave', 'Leave eligibility, accrual, carry-forward and sandwich rules.'),
    ('ATTENDANCE', 'Attendance', 'Attendance channel, late, overtime and regularization rules.'),
    ('WORK_ARRANGEMENT', 'Work Arrangement', 'Office, remote, hybrid and field-work rules.'),
    ('TRAVEL', 'Travel', 'Travel eligibility, limits and reimbursement rules.'),
    ('ACCOMMODATION', 'Accommodation', 'Accommodation eligibility and allowance rules.'),
    ('INSURANCE', 'Insurance', 'Insurance eligibility, dependent and coverage rules.'),
    ('EXPENSE', 'Expense and Reimbursement', 'Expense categories, limits and evidence rules.'),
    ('HOLIDAY', 'Holiday and Calendar', 'Location-specific holiday and optional holiday rules.'),
    ('SHIFT', 'Shift and Weekly Off', 'Shift, weekly-off and roster rules.'),
    ('EMPLOYMENT', 'Employment Lifecycle', 'Probation, confirmation and notice-period rules.'),
    ('BENEFIT', 'Employee Benefit', 'Tenant-defined benefits and allowance rules.'),
    ('CUSTOM', 'Custom', 'Tenant-defined policy category.')
ON CONFLICT ("CategoryCode") DO UPDATE SET "CategoryName"=EXCLUDED."CategoryName", "Description"=EXCLUDED."Description", "IsActive"=true;

INSERT INTO axionpro."PolicyRuleType" ("RuleTypeCode", "RuleTypeName", "Description") VALUES
    ('ELIGIBILITY', 'Eligibility', 'Determines who qualifies for the policy.'),
    ('ENTITLEMENT', 'Entitlement', 'Defines entitlement quantity and unit.'),
    ('ACCRUAL', 'Accrual', 'Defines accrual frequency and calculation.'),
    ('CARRY_FORWARD', 'Carry Forward', 'Defines year-end carry-forward behavior.'),
    ('SANDWICH', 'Sandwich', 'Defines holiday and weekly-off sandwich behavior.'),
    ('LIMIT', 'Limit', 'Defines monetary, count or duration limits.'),
    ('ATTENDANCE_CHANNEL', 'Attendance Channel', 'Defines allowed web, mobile, biometric or manual channels.'),
    ('LATE_PENALTY', 'Late Penalty', 'Defines late grace and penalty thresholds.'),
    ('OVERTIME', 'Overtime', 'Defines overtime eligibility and calculation.'),
    ('APPROVAL', 'Approval', 'Defines request approval requirements.'),
    ('REIMBURSEMENT', 'Reimbursement', 'Defines reimbursement evidence and amount rules.'),
    ('CALENDAR', 'Calendar', 'Defines holiday/calendar application behavior.'),
    ('CUSTOM', 'Custom Rule', 'Tenant-defined structured JSON rule.')
ON CONFLICT ("RuleTypeCode") DO UPDATE SET "RuleTypeName"=EXCLUDED."RuleTypeName", "Description"=EXCLUDED."Description", "IsActive"=true;

DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname='FK_PolicyType_Tenant') THEN ALTER TABLE axionpro."PolicyType" ADD CONSTRAINT "FK_PolicyType_Tenant" FOREIGN KEY ("TenantId") REFERENCES axionpro."Tenant"("Id") ON DELETE RESTRICT; END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname='FK_PolicyType_Category') THEN ALTER TABLE axionpro."PolicyType" ADD CONSTRAINT "FK_PolicyType_Category" FOREIGN KEY ("PolicyCategoryId") REFERENCES axionpro."PolicyCategory"("Id") ON DELETE RESTRICT; END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname='FK_Policy_Tenant') THEN ALTER TABLE axionpro."Policy" ADD CONSTRAINT "FK_Policy_Tenant" FOREIGN KEY ("TenantId") REFERENCES axionpro."Tenant"("Id") ON DELETE RESTRICT; END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname='FK_Policy_Type') THEN ALTER TABLE axionpro."Policy" ADD CONSTRAINT "FK_Policy_Type" FOREIGN KEY ("PolicyTypeId") REFERENCES axionpro."PolicyType"("Id") ON DELETE RESTRICT; END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname='FK_Policy_OwnerDepartment') THEN ALTER TABLE axionpro."Policy" ADD CONSTRAINT "FK_Policy_OwnerDepartment" FOREIGN KEY ("OwnerDepartmentId") REFERENCES axionpro."Department"("Id") ON DELETE RESTRICT; END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname='FK_PolicyVersion_Policy') THEN ALTER TABLE axionpro."PolicyVersion" ADD CONSTRAINT "FK_PolicyVersion_Policy" FOREIGN KEY ("PolicyId") REFERENCES axionpro."Policy"("Id") ON DELETE CASCADE; END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname='FK_PolicyVersion_Status') THEN ALTER TABLE axionpro."PolicyVersion" ADD CONSTRAINT "FK_PolicyVersion_Status" FOREIGN KEY ("PolicyStatusId") REFERENCES axionpro."PolicyStatus"("Id") ON DELETE RESTRICT; END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname='FK_PolicyRule_Version') THEN ALTER TABLE axionpro."PolicyRule" ADD CONSTRAINT "FK_PolicyRule_Version" FOREIGN KEY ("PolicyVersionId") REFERENCES axionpro."PolicyVersion"("Id") ON DELETE CASCADE; END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname='FK_PolicyRule_Type') THEN ALTER TABLE axionpro."PolicyRule" ADD CONSTRAINT "FK_PolicyRule_Type" FOREIGN KEY ("PolicyRuleTypeId") REFERENCES axionpro."PolicyRuleType"("Id") ON DELETE RESTRICT; END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname='FK_PolicyApplicability_Version') THEN ALTER TABLE axionpro."PolicyApplicability" ADD CONSTRAINT "FK_PolicyApplicability_Version" FOREIGN KEY ("PolicyVersionId") REFERENCES axionpro."PolicyVersion"("Id") ON DELETE CASCADE; END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname='FK_PolicyApplicability_Country') THEN ALTER TABLE axionpro."PolicyApplicability" ADD CONSTRAINT "FK_PolicyApplicability_Country" FOREIGN KEY ("CountryId") REFERENCES axionpro."Country"("Id") ON DELETE RESTRICT; END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname='FK_PolicyApplicability_State') THEN ALTER TABLE axionpro."PolicyApplicability" ADD CONSTRAINT "FK_PolicyApplicability_State" FOREIGN KEY ("StateId") REFERENCES axionpro."State"("Id") ON DELETE RESTRICT; END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname='FK_PolicyApplicability_District') THEN ALTER TABLE axionpro."PolicyApplicability" ADD CONSTRAINT "FK_PolicyApplicability_District" FOREIGN KEY ("DistrictId") REFERENCES axionpro."District"("Id") ON DELETE RESTRICT; END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname='FK_PolicyApplicability_Locality') THEN ALTER TABLE axionpro."PolicyApplicability" ADD CONSTRAINT "FK_PolicyApplicability_Locality" FOREIGN KEY ("LocalityId") REFERENCES axionpro."Locality"("Id") ON DELETE RESTRICT; END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname='FK_PolicyApplicability_TenantLocation') THEN ALTER TABLE axionpro."PolicyApplicability" ADD CONSTRAINT "FK_PolicyApplicability_TenantLocation" FOREIGN KEY ("TenantLocationId") REFERENCES axionpro."TenantLocation"("Id") ON DELETE RESTRICT; END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname='FK_PolicyApplicability_EmployeeType') THEN ALTER TABLE axionpro."PolicyApplicability" ADD CONSTRAINT "FK_PolicyApplicability_EmployeeType" FOREIGN KEY ("EmployeeTypeId") REFERENCES axionpro."EmployeeType"("Id") ON DELETE RESTRICT; END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname='FK_PolicyApplicability_Department') THEN ALTER TABLE axionpro."PolicyApplicability" ADD CONSTRAINT "FK_PolicyApplicability_Department" FOREIGN KEY ("DepartmentId") REFERENCES axionpro."Department"("Id") ON DELETE RESTRICT; END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname='FK_PolicyApplicability_Designation') THEN ALTER TABLE axionpro."PolicyApplicability" ADD CONSTRAINT "FK_PolicyApplicability_Designation" FOREIGN KEY ("DesignationId") REFERENCES axionpro."Designation"("Id") ON DELETE RESTRICT; END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname='FK_PolicyApplicability_Employee') THEN ALTER TABLE axionpro."PolicyApplicability" ADD CONSTRAINT "FK_PolicyApplicability_Employee" FOREIGN KEY ("EmployeeId") REFERENCES axionpro."Employee"("Id") ON DELETE RESTRICT; END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname='FK_PolicyApplicability_Gender') THEN ALTER TABLE axionpro."PolicyApplicability" ADD CONSTRAINT "FK_PolicyApplicability_Gender" FOREIGN KEY ("GenderId") REFERENCES axionpro."Gender"("Id") ON DELETE RESTRICT; END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname='FK_PolicyAssignment_Version') THEN ALTER TABLE axionpro."PolicyAssignment" ADD CONSTRAINT "FK_PolicyAssignment_Version" FOREIGN KEY ("PolicyVersionId") REFERENCES axionpro."PolicyVersion"("Id") ON DELETE RESTRICT; END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname='FK_PolicyAssignment_Employee') THEN ALTER TABLE axionpro."PolicyAssignment" ADD CONSTRAINT "FK_PolicyAssignment_Employee" FOREIGN KEY ("EmployeeId") REFERENCES axionpro."Employee"("Id") ON DELETE RESTRICT; END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname='FK_PolicyAssignment_Applicability') THEN ALTER TABLE axionpro."PolicyAssignment" ADD CONSTRAINT "FK_PolicyAssignment_Applicability" FOREIGN KEY ("SourceApplicabilityId") REFERENCES axionpro."PolicyApplicability"("Id") ON DELETE SET NULL; END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname='FK_PolicyException_Version') THEN ALTER TABLE axionpro."PolicyException" ADD CONSTRAINT "FK_PolicyException_Version" FOREIGN KEY ("PolicyVersionId") REFERENCES axionpro."PolicyVersion"("Id") ON DELETE RESTRICT; END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname='FK_PolicyException_Employee') THEN ALTER TABLE axionpro."PolicyException" ADD CONSTRAINT "FK_PolicyException_Employee" FOREIGN KEY ("EmployeeId") REFERENCES axionpro."Employee"("Id") ON DELETE RESTRICT; END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname='FK_PolicyException_Status') THEN ALTER TABLE axionpro."PolicyException" ADD CONSTRAINT "FK_PolicyException_Status" FOREIGN KEY ("ApprovalStatusId") REFERENCES axionpro."PolicyStatus"("Id") ON DELETE RESTRICT; END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname='FK_PolicyDocument_Version') THEN ALTER TABLE axionpro."PolicyDocument" ADD CONSTRAINT "FK_PolicyDocument_Version" FOREIGN KEY ("PolicyVersionId") REFERENCES axionpro."PolicyVersion"("Id") ON DELETE CASCADE; END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname='FK_PolicyDocument_Type') THEN ALTER TABLE axionpro."PolicyDocument" ADD CONSTRAINT "FK_PolicyDocument_Type" FOREIGN KEY ("PolicyDocumentTypeId") REFERENCES axionpro."PolicyDocumentType"("Id") ON DELETE RESTRICT; END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname='FK_PolicyApprovalStage_Category') THEN ALTER TABLE axionpro."PolicyApprovalStage" ADD CONSTRAINT "FK_PolicyApprovalStage_Category" FOREIGN KEY ("PolicyCategoryId") REFERENCES axionpro."PolicyCategory"("Id") ON DELETE RESTRICT; END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname='FK_PolicyApprovalStage_Role') THEN ALTER TABLE axionpro."PolicyApprovalStage" ADD CONSTRAINT "FK_PolicyApprovalStage_Role" FOREIGN KEY ("ApproverRoleId") REFERENCES axionpro."Role"("Id") ON DELETE RESTRICT; END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname='FK_PolicyApprovalHistory_Version') THEN ALTER TABLE axionpro."PolicyApprovalHistory" ADD CONSTRAINT "FK_PolicyApprovalHistory_Version" FOREIGN KEY ("PolicyVersionId") REFERENCES axionpro."PolicyVersion"("Id") ON DELETE RESTRICT; END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname='FK_PolicyApprovalHistory_Stage') THEN ALTER TABLE axionpro."PolicyApprovalHistory" ADD CONSTRAINT "FK_PolicyApprovalHistory_Stage" FOREIGN KEY ("PolicyApprovalStageId") REFERENCES axionpro."PolicyApprovalStage"("Id") ON DELETE RESTRICT; END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname='FK_PolicyAcknowledgement_Version') THEN ALTER TABLE axionpro."PolicyAcknowledgement" ADD CONSTRAINT "FK_PolicyAcknowledgement_Version" FOREIGN KEY ("PolicyVersionId") REFERENCES axionpro."PolicyVersion"("Id") ON DELETE RESTRICT; END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname='FK_PolicyAcknowledgement_Employee') THEN ALTER TABLE axionpro."PolicyAcknowledgement" ADD CONSTRAINT "FK_PolicyAcknowledgement_Employee" FOREIGN KEY ("EmployeeId") REFERENCES axionpro."Employee"("Id") ON DELETE RESTRICT; END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname='FK_PolicyChangeAudit_Policy') THEN ALTER TABLE axionpro."PolicyChangeAudit" ADD CONSTRAINT "FK_PolicyChangeAudit_Policy" FOREIGN KEY ("PolicyId") REFERENCES axionpro."Policy"("Id") ON DELETE RESTRICT; END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname='FK_PolicyChangeAudit_Version') THEN ALTER TABLE axionpro."PolicyChangeAudit" ADD CONSTRAINT "FK_PolicyChangeAudit_Version" FOREIGN KEY ("PolicyVersionId") REFERENCES axionpro."PolicyVersion"("Id") ON DELETE RESTRICT; END IF;
END $$;

DO $$
DECLARE
    table_name text;
    constraint_name text;
BEGIN
    FOREACH table_name IN ARRAY ARRAY[
        'PolicyVersion','PolicyRule','PolicyApplicability','PolicyAssignment','PolicyException',
        'PolicyDocument','PolicyApprovalStage','PolicyApprovalHistory','PolicyAcknowledgement','PolicyChangeAudit'
    ]
    LOOP
        constraint_name := 'FK_' || table_name || '_Tenant';
        IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname=constraint_name) THEN
            EXECUTE format('ALTER TABLE axionpro.%I ADD CONSTRAINT %I FOREIGN KEY ("TenantId") REFERENCES axionpro."Tenant"("Id") ON DELETE RESTRICT', table_name, constraint_name);
        END IF;
    END LOOP;
END $$;

CREATE UNIQUE INDEX IF NOT EXISTS "UX_PolicyType_Tenant_Code" ON axionpro."PolicyType" ("TenantId", "PolicyTypeCode") WHERE "PolicyTypeCode" IS NOT NULL AND COALESCE("IsSoftDelete", false)=false;
CREATE UNIQUE INDEX IF NOT EXISTS "UX_PolicyVersion_Current" ON axionpro."PolicyVersion" ("PolicyId") WHERE "IsCurrent"=true AND "IsActive"=true;
CREATE INDEX IF NOT EXISTS "IX_PolicyApplicability_Resolution" ON axionpro."PolicyApplicability" ("TenantId", "PolicyVersionId", "Priority", "EffectiveFrom", "EffectiveTo") WHERE "IsActive"=true;
CREATE INDEX IF NOT EXISTS "IX_PolicyAssignment_Employee" ON axionpro."PolicyAssignment" ("TenantId", "EmployeeId", "EffectiveFrom", "EffectiveTo") WHERE "IsActive"=true;
CREATE INDEX IF NOT EXISTS "IX_PolicyException_Employee" ON axionpro."PolicyException" ("TenantId", "EmployeeId", "EffectiveFrom", "EffectiveTo") WHERE "IsActive"=true;
CREATE INDEX IF NOT EXISTS "IX_PolicyAcknowledgement_Employee" ON axionpro."PolicyAcknowledgement" ("TenantId", "EmployeeId", "AcknowledgementStatus");
CREATE INDEX IF NOT EXISTS "IX_PolicyChangeAudit_Policy" ON axionpro."PolicyChangeAudit" ("TenantId", "PolicyId", "ChangedDateTime" DESC);

COMMIT;

SELECT table_name
FROM information_schema.tables
WHERE table_schema='axionpro' AND table_name IN
('PolicyCategory','PolicyStatus','PolicyRuleType','PolicyDocumentType','PolicyType','Policy','PolicyVersion','PolicyRule','PolicyApplicability','PolicyAssignment','PolicyException','PolicyDocument','PolicyApprovalStage','PolicyApprovalHistory','PolicyAcknowledgement','PolicyChangeAudit')
ORDER BY table_name;
