-- Run this once in pgAdmin 4 against the AxionPro database.
-- It copies credentials from the latest complete active TenantEmailConfig row, so SMTP secrets never need to be pasted into this script.
-- This table supplies the central SMTP configuration copied into each newly registered Tenant's TenantEmailConfig row.

BEGIN;

CREATE TABLE IF NOT EXISTS axionpro."DefaultEmailConfig"
(
    "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "ConfigName" character varying(100) NOT NULL,
    "SmtpHost" character varying(200) NOT NULL,
    "SmtpPort" integer NOT NULL CHECK ("SmtpPort" BETWEEN 1 AND 65535),
    "SmtpUsername" character varying(200) NOT NULL,
    "SmtpPasswordEncrypted" character varying(500) NOT NULL,
    "FromEmail" character varying(200) NOT NULL,
    "FromName" character varying(100) NOT NULL,
    "IsActive" boolean NOT NULL DEFAULT true,
    "IsDefault" boolean NOT NULL DEFAULT false,
    "SecrateKey" character varying(500) NOT NULL,
    "CreatedDateTime" timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "UpdatedDateTime" timestamp without time zone NULL,
    CONSTRAINT "UX_DefaultEmailConfig_ConfigName" UNIQUE ("ConfigName")
);

-- IsDefault was added after the first rollout. This is safe both for a new
-- table and for a database where the earlier version of this script ran.
ALTER TABLE axionpro."DefaultEmailConfig"
    ADD COLUMN IF NOT EXISTS "IsDefault" boolean NOT NULL DEFAULT false;

-- More than one SMTP configuration can be active. Only one active choice is
-- marked as the registration default.
DROP INDEX IF EXISTS axionpro."UX_DefaultEmailConfig_OneActive";

CREATE UNIQUE INDEX IF NOT EXISTS "UX_DefaultEmailConfig_OneDefault"
    ON axionpro."DefaultEmailConfig" ("IsDefault")
    WHERE "IsDefault" = true;

-- Upgrade the original seeded row to default only when another configuration
-- has not already been deliberately selected as the registration default.
UPDATE axionpro."DefaultEmailConfig" configuration
SET "IsDefault" = true,
    "UpdatedDateTime" = CURRENT_TIMESTAMP
WHERE configuration."ConfigName" = 'DEFAULT_REGISTRATION_SMTP'
  AND configuration."IsActive" = true
  AND configuration."IsDefault" = false
  AND NOT EXISTS
  (
      SELECT 1
      FROM axionpro."DefaultEmailConfig" existingDefault
      WHERE existingDefault."IsDefault" = true
  );

DO
$$
DECLARE
BEGIN
    INSERT INTO axionpro."DefaultEmailConfig"
    (
        "ConfigName", "SmtpHost", "SmtpPort", "SmtpUsername",
        "SmtpPasswordEncrypted", "FromEmail", "FromName", "IsActive", "IsDefault", "SecrateKey"
    )
    SELECT
        'DEFAULT_REGISTRATION_SMTP',
        btrim(configuration."SmtpHost"),
        configuration."SmtpPort",
        btrim(configuration."SmtpUsername"),
        COALESCE(
            NULLIF(btrim(configuration."SmtpPasswordEncrypted"), ''),
            NULLIF(btrim(configuration."SecrateKey"), '')),
        btrim(configuration."FromEmail"),
        btrim(configuration."FromName"),
        true,
        NOT EXISTS
        (
            SELECT 1
            FROM axionpro."DefaultEmailConfig" existingDefault
            WHERE existingDefault."IsDefault" = true
        ),
        COALESCE(
            NULLIF(btrim(configuration."SecrateKey"), ''),
            NULLIF(btrim(configuration."SmtpPasswordEncrypted"), ''))
    FROM axionpro."TenantEmailConfig" configuration
    WHERE configuration."IsActive" = true
      AND NULLIF(btrim(configuration."SmtpHost"), '') IS NOT NULL
      AND configuration."SmtpPort" BETWEEN 1 AND 65535
      AND NULLIF(btrim(configuration."SmtpUsername"), '') IS NOT NULL
      AND COALESCE(
            NULLIF(btrim(configuration."SmtpPasswordEncrypted"), ''),
            NULLIF(btrim(configuration."SecrateKey"), '')) IS NOT NULL
      AND NULLIF(btrim(configuration."FromEmail"), '') IS NOT NULL
      AND NULLIF(btrim(configuration."FromName"), '') IS NOT NULL
    ORDER BY configuration."Id" DESC
    LIMIT 1
    ON CONFLICT ("ConfigName")
    DO UPDATE SET
        "SmtpHost" = EXCLUDED."SmtpHost",
        "SmtpPort" = EXCLUDED."SmtpPort",
        "SmtpUsername" = EXCLUDED."SmtpUsername",
        "SmtpPasswordEncrypted" = EXCLUDED."SmtpPasswordEncrypted",
        "FromEmail" = EXCLUDED."FromEmail",
        "FromName" = EXCLUDED."FromName",
        "IsActive" = EXCLUDED."IsActive",
        "SecrateKey" = EXCLUDED."SecrateKey",
        "UpdatedDateTime" = CURRENT_TIMESTAMP;

    IF NOT FOUND THEN
        RAISE EXCEPTION 'No complete active TenantEmailConfig was found to seed DefaultEmailConfig.';
    END IF;
END;
$$;

-- Seed the Host module used by the API authorization behavior. Existing Host
-- roles do not receive this permission automatically; assign the required
-- mapped operation(s) through Host Role Permissions after running this script.
INSERT INTO axionpro."Module"
(
    "TenantId", "ModuleCode", "ModuleName", "DisplayName", "URLPath",
    "ParentModuleId", "IsLeafNode", "IsModuleDisplayInUI", "IsCommonMenu",
    "ModuleScope", "IsActive", "ItemPriority", "Remark", "AddedDateTime"
)
SELECT
    NULL,
    'HOST_DEFAULT_EMAIL_CONFIG',
    'Default Email Configuration',
    'Default Email Configuration',
    '/app/default-email-config',
    NULL,
    true,
    false,
    false,
    2,
    true,
    0,
    'Host-managed SMTP defaults for new Tenant registration.',
    CURRENT_TIMESTAMP
WHERE NOT EXISTS
(
    SELECT 1
    FROM axionpro."Module"
    WHERE "ModuleCode" = 'HOST_DEFAULT_EMAIL_CONFIG'
);

-- Reuse the existing active CRUD operation master rows. If a deployment uses
-- different operation names, map the appropriate operation through the
-- existing Module Operation Mapping administration screen.
INSERT INTO axionpro."ModuleOperationMapping"
(
    "ModuleId", "OperationId", "IsCommonItem", "IsOperational", "Priority",
    "Remark", "IsActive", "AddedById", "AddedDateTime"
)
SELECT
    module."Id",
    operation."Id",
    false,
    true,
    0,
    'Default Email Configuration permission mapping.',
    true,
    0,
    CURRENT_TIMESTAMP
FROM axionpro."Module" module
INNER JOIN axionpro."Operation" operation
    ON lower(btrim(operation."OperationName")) IN ('create', 'add', 'view', 'read', 'update', 'edit', 'delete')
WHERE module."ModuleCode" = 'HOST_DEFAULT_EMAIL_CONFIG'
  AND operation."IsActive" = true
  AND NOT EXISTS
  (
      SELECT 1
      FROM axionpro."ModuleOperationMapping" mapping
      WHERE mapping."ModuleId" = module."Id"
        AND mapping."OperationId" = operation."Id"
  );

COMMIT;
