/*
  Data-preserving City -> Locality migration.

  Result:
  - axionpro."City" becomes axionpro."Locality".
  - Existing rows are classified as City and linked to their matching District.
  - LocalityType is seeded with City, Town, and Village.
  - TenantLocation receives DistrictId; its existing CityId column is retained as
    the physical compatibility column used by LocalityId in the updated API.
  - A read-compatible City view keeps the currently deployed API operational
    during the deployment transition.
*/

BEGIN;
SET LOCAL lock_timeout = '15s';
SET LOCAL statement_timeout = '180s';

CREATE TABLE IF NOT EXISTS axionpro."LocalityType"
(
    "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "TypeName" character varying(30) NOT NULL,
    "IsActive" boolean NOT NULL DEFAULT TRUE,
    CONSTRAINT "UQ_LocalityType_TypeName" UNIQUE ("TypeName")
);

INSERT INTO axionpro."LocalityType" ("Id", "TypeName", "IsActive")
VALUES
    (1, 'City', TRUE),
    (2, 'Town', TRUE),
    (3, 'Village', TRUE)
ON CONFLICT ("Id") DO UPDATE
SET "TypeName" = EXCLUDED."TypeName",
    "IsActive" = TRUE;

DO $$
BEGIN
    IF to_regclass('axionpro."Locality"') IS NULL
       AND EXISTS
       (
           SELECT 1
           FROM pg_class class
           JOIN pg_namespace namespace ON namespace.oid = class.relnamespace
           WHERE namespace.nspname = 'axionpro'
             AND class.relname = 'City'
             AND class.relkind = 'r'
       ) THEN
        ALTER TABLE axionpro."City" RENAME TO "Locality";
    END IF;

    IF to_regclass('axionpro."Locality"') IS NULL THEN
        RAISE EXCEPTION 'Neither axionpro.City table nor axionpro.Locality table exists.';
    END IF;

    IF EXISTS
       (
           SELECT 1 FROM information_schema.columns
           WHERE table_schema = 'axionpro' AND table_name = 'Locality' AND column_name = 'CityName'
       ) THEN
        ALTER TABLE axionpro."Locality" RENAME COLUMN "CityName" TO "LocalityName";
    END IF;
END;
$$;

ALTER TABLE axionpro."Locality"
    ADD COLUMN IF NOT EXISTS "DistrictId" integer,
    ADD COLUMN IF NOT EXISTS "LocalityTypeId" integer;

UPDATE axionpro."Locality" locality
SET "DistrictId" = district."Id"
FROM axionpro."District" district
WHERE locality."DistrictId" IS NULL
  AND district."Id" = locality."Id"
  AND district."StateId" = locality."StateId";

DO $$
DECLARE
    unmapped_count bigint;
BEGIN
    SELECT count(*) INTO unmapped_count
    FROM axionpro."Locality"
    WHERE "DistrictId" IS NULL;

    IF unmapped_count > 0 THEN
        RAISE EXCEPTION '% Locality row(s) cannot be mapped to District by the synchronized Id/StateId catalog.', unmapped_count;
    END IF;
END;
$$;

UPDATE axionpro."Locality"
SET "LocalityTypeId" = 1
WHERE "LocalityTypeId" IS NULL;

ALTER TABLE axionpro."Locality"
    ALTER COLUMN "DistrictId" SET NOT NULL,
    ALTER COLUMN "LocalityTypeId" SET NOT NULL,
    ALTER COLUMN "LocalityTypeId" SET DEFAULT 1;

DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'FK_Locality_District') THEN
        ALTER TABLE axionpro."Locality"
            ADD CONSTRAINT "FK_Locality_District"
            FOREIGN KEY ("DistrictId") REFERENCES axionpro."District"("Id") ON DELETE RESTRICT;
    END IF;

    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'FK_Locality_LocalityType') THEN
        ALTER TABLE axionpro."Locality"
            ADD CONSTRAINT "FK_Locality_LocalityType"
            FOREIGN KEY ("LocalityTypeId") REFERENCES axionpro."LocalityType"("Id") ON DELETE RESTRICT;
    END IF;
END;
$$;

CREATE INDEX IF NOT EXISTS "IX_Locality_DistrictId" ON axionpro."Locality" ("DistrictId");
CREATE INDEX IF NOT EXISTS "IX_Locality_LocalityTypeId" ON axionpro."Locality" ("LocalityTypeId");

ALTER TABLE axionpro."TenantLocation"
    ADD COLUMN IF NOT EXISTS "DistrictId" integer;

UPDATE axionpro."TenantLocation" tenant_location
SET "DistrictId" = locality."DistrictId"
FROM axionpro."Locality" locality
WHERE tenant_location."DistrictId" IS NULL
  AND tenant_location."CityId" = locality."Id";

DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'FK_TenantLocation_District') THEN
        ALTER TABLE axionpro."TenantLocation"
            ADD CONSTRAINT "FK_TenantLocation_District"
            FOREIGN KEY ("DistrictId") REFERENCES axionpro."District"("Id") ON DELETE RESTRICT;
    END IF;
END;
$$;

CREATE INDEX IF NOT EXISTS "IX_TenantLocation_DistrictId"
    ON axionpro."TenantLocation" ("DistrictId");

DO $$
BEGIN
    IF to_regclass('axionpro."City"') IS NULL THEN
        EXECUTE '
            CREATE VIEW axionpro."City" AS
            SELECT "Id", "LocalityName" AS "CityName", "StateId", "IsActive"
            FROM axionpro."Locality"';
    END IF;
END;
$$;

COMMIT;

SELECT "Id", "TypeName", "IsActive"
FROM axionpro."LocalityType"
ORDER BY "Id";

SELECT
    count(*) AS "LocalityCount",
    count(*) FILTER (WHERE "DistrictId" IS NULL) AS "MissingDistrictCount",
    count(*) FILTER (WHERE "LocalityTypeId" IS NULL) AS "MissingLocalityTypeCount"
FROM axionpro."Locality";
