-- Replaces the obsolete biometric command tables with the durable MQTT/MQTTS infrastructure.
-- Run once against the AxionPro PostgreSQL database after deploying the matching application build.
-- Deliberately has no CASCADE: unexpected external dependencies abort the transaction.

BEGIN;

-- Do not silently continue after a partial or different prior migration.
DO $$
BEGIN
    IF to_regclass('axionpro."DeviceCommand"') IS NOT NULL
       OR to_regclass('axionpro."DeviceCommandResponse"') IS NOT NULL
       OR to_regclass('axionpro."DeviceMessageLog"') IS NOT NULL
       OR to_regclass('axionpro."DeviceCredential"') IS NOT NULL THEN
        RAISE EXCEPTION 'The replacement device infrastructure already exists. Inspect its schema before rerunning this migration.';
    END IF;
END $$;

-- MQTT is deliberately separate from the historical HTTP-oriented CommunicationType column.
ALTER TABLE axionpro."TenantDeviceConfiguration"
    ADD COLUMN IF NOT EXISTS "MqttTransport" smallint NULL;

ALTER TABLE axionpro."TenantDeviceConfiguration"
    DROP CONSTRAINT IF EXISTS "CK_TenantDeviceConfiguration_MqttTransport";

ALTER TABLE axionpro."TenantDeviceConfiguration"
    ADD CONSTRAINT "CK_TenantDeviceConfiguration_MqttTransport"
    CHECK ("MqttTransport" IS NULL OR "MqttTransport" IN (1, 2));

CREATE TABLE axionpro."DeviceCommand"
(
    "Id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "InternalTrackingId" uuid NOT NULL,
    "TenantId" bigint NOT NULL,
    "TenantDeviceId" bigint NOT NULL,
    "TenantLocationId" bigint NOT NULL,
    "DeviceSerialNumber" character varying(100) NOT NULL,
    "CommandName" character varying(100) NOT NULL,
    "RequestPayload" jsonb NOT NULL,
    "MatchCriteria" jsonb NOT NULL DEFAULT '{}'::jsonb,
    "Status" smallint NOT NULL DEFAULT 1,
    "ResponseMode" smallint NOT NULL DEFAULT 1,
    "AccessLevel" smallint NOT NULL DEFAULT 3,
    "AttemptCount" integer NOT NULL DEFAULT 0,
    "MaxAttempts" integer NOT NULL DEFAULT 3,
    "NextAttemptDateTime" timestamp with time zone NULL,
    "PublishedDateTime" timestamp with time zone NULL,
    "ResponseDeadlineDateTime" timestamp with time zone NULL,
    "CompletedDateTime" timestamp with time zone NULL,
    "FailureReason" character varying(2000) NULL,
    "RequestedById" bigint NULL,
    "AddedDateTime" timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "UpdatedDateTime" timestamp with time zone NULL,
    CONSTRAINT "UX_DeviceCommand_InternalTrackingId" UNIQUE ("InternalTrackingId"),
    CONSTRAINT "CK_DeviceCommand_Status" CHECK ("Status" IN (1, 2, 3, 4, 5, 6, 7)),
    CONSTRAINT "CK_DeviceCommand_ResponseMode" CHECK ("ResponseMode" IN (1, 2, 3)),
    CONSTRAINT "CK_DeviceCommand_AccessLevel" CHECK ("AccessLevel" IN (1, 2, 3)),
    CONSTRAINT "CK_DeviceCommand_Attempts" CHECK ("AttemptCount" >= 0 AND "MaxAttempts" BETWEEN 1 AND 10),
    CONSTRAINT "FK_DeviceCommand_Tenant"
        FOREIGN KEY ("TenantId") REFERENCES axionpro."Tenant" ("Id") ON DELETE RESTRICT,
    CONSTRAINT "FK_DeviceCommand_TenantDevice"
        FOREIGN KEY ("TenantDeviceId") REFERENCES axionpro."TenantDevice" ("Id") ON DELETE RESTRICT,
    CONSTRAINT "FK_DeviceCommand_TenantLocation"
        FOREIGN KEY ("TenantLocationId") REFERENCES axionpro."TenantLocation" ("Id") ON DELETE RESTRICT
);

CREATE INDEX "IX_DeviceCommand_Dispatch"
    ON axionpro."DeviceCommand" ("Status", "NextAttemptDateTime", "AddedDateTime");
CREATE INDEX "IX_DeviceCommand_DeviceSerial_Order"
    ON axionpro."DeviceCommand" ("DeviceSerialNumber", "AddedDateTime");
CREATE INDEX "IX_DeviceCommand_TenantId"
    ON axionpro."DeviceCommand" ("TenantId");
CREATE INDEX "IX_DeviceCommand_TenantLocationId"
    ON axionpro."DeviceCommand" ("TenantLocationId");
CREATE UNIQUE INDEX "UX_DeviceCommand_OneOutstandingSerial"
    ON axionpro."DeviceCommand" ("DeviceSerialNumber")
    WHERE "Status" IN (2, 3, 6);

CREATE TABLE axionpro."DeviceCommandResponse"
(
    "Id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "DeviceCommandId" bigint NULL,
    "TenantId" bigint NULL,
    "TenantDeviceId" bigint NULL,
    "DeviceSerialNumber" character varying(100) NOT NULL,
    "ResponseCommandName" character varying(100) NOT NULL,
    "Result" boolean NULL,
    "FailureReason" character varying(2000) NULL,
    "ResponsePayload" text NOT NULL,
    "ReceivedDateTime" timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT "FK_DeviceCommandResponse_DeviceCommand"
        FOREIGN KEY ("DeviceCommandId") REFERENCES axionpro."DeviceCommand" ("Id") ON DELETE RESTRICT,
    CONSTRAINT "FK_DeviceCommandResponse_Tenant"
        FOREIGN KEY ("TenantId") REFERENCES axionpro."Tenant" ("Id") ON DELETE RESTRICT,
    CONSTRAINT "FK_DeviceCommandResponse_TenantDevice"
        FOREIGN KEY ("TenantDeviceId") REFERENCES axionpro."TenantDevice" ("Id") ON DELETE RESTRICT
);

CREATE UNIQUE INDEX "UX_DeviceCommandResponse_DeviceCommand"
    ON axionpro."DeviceCommandResponse" ("DeviceCommandId")
    WHERE "DeviceCommandId" IS NOT NULL;
CREATE INDEX "IX_DeviceCommandResponse_TenantDevice_Received"
    ON axionpro."DeviceCommandResponse" ("TenantDeviceId", "ReceivedDateTime");

CREATE TABLE axionpro."DeviceMessageLog"
(
    "Id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "TenantId" bigint NULL,
    "TenantDeviceId" bigint NULL,
    "DeviceSerialNumber" character varying(100) NOT NULL,
    "Topic" character varying(300) NOT NULL,
    "Direction" smallint NOT NULL DEFAULT 1,
    "QualityOfService" integer NOT NULL DEFAULT 1,
    "IsDuplicateDelivery" boolean NOT NULL DEFAULT false,
    "PayloadHash" character varying(64) NOT NULL,
    "RawPayload" text NOT NULL,
    "OccurredDateTime" timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "AddedDateTime" timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT "CK_DeviceMessageLog_Direction" CHECK ("Direction" IN (1, 2)),
    CONSTRAINT "CK_DeviceMessageLog_Qos" CHECK ("QualityOfService" BETWEEN 0 AND 2),
    CONSTRAINT "FK_DeviceMessageLog_Tenant"
        FOREIGN KEY ("TenantId") REFERENCES axionpro."Tenant" ("Id") ON DELETE RESTRICT,
    CONSTRAINT "FK_DeviceMessageLog_TenantDevice"
        FOREIGN KEY ("TenantDeviceId") REFERENCES axionpro."TenantDevice" ("Id") ON DELETE RESTRICT
);

CREATE INDEX "IX_DeviceMessageLog_TenantDevice_Occurred"
    ON axionpro."DeviceMessageLog" ("TenantDeviceId", "OccurredDateTime");
CREATE INDEX "IX_DeviceMessageLog_Topic_PayloadHash"
    ON axionpro."DeviceMessageLog" ("Topic", "PayloadHash");

CREATE TABLE axionpro."DeviceCredential"
(
    "Id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "TenantDeviceId" bigint NOT NULL,
    "CredentialType" smallint NOT NULL,
    "UserName" character varying(300) NULL,
    "SecretEncrypted" text NULL,
    "CertificateReference" character varying(1000) NULL,
    "ExpiresDateTime" timestamp with time zone NULL,
    "IsActive" boolean NOT NULL DEFAULT true,
    "AddedById" bigint NOT NULL,
    "AddedDateTime" timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "UpdatedById" bigint NULL,
    "UpdatedDateTime" timestamp with time zone NULL,
    CONSTRAINT "CK_DeviceCredential_Type" CHECK ("CredentialType" IN (1, 2, 3)),
    CONSTRAINT "FK_DeviceCredential_TenantDevice"
        FOREIGN KEY ("TenantDeviceId") REFERENCES axionpro."TenantDevice" ("Id") ON DELETE RESTRICT
);

CREATE UNIQUE INDEX "UX_DeviceCredential_ActiveType"
    ON axionpro."DeviceCredential" ("TenantDeviceId", "CredentialType")
    WHERE "IsActive" = true;

-- Lock the obsolete tables before the safety checks and destructive replacement.
LOCK TABLE axionpro."DeviceCommandMaster", axionpro."DeviceCommandQueue", axionpro."DeviceLogRaw" IN ACCESS EXCLUSIVE MODE;

DO $$
DECLARE
    pending_command_count bigint;
    legacy_log_count bigint;
    unexpected_dependencies text;
BEGIN
    SELECT count(*) INTO pending_command_count FROM axionpro."DeviceCommandQueue";
    IF pending_command_count <> 0 THEN
        RAISE EXCEPTION 'Legacy DeviceCommandQueue has % row(s). Resolve them explicitly; this migration will not discard queued device commands.', pending_command_count;
    END IF;

    SELECT count(*) INTO legacy_log_count FROM axionpro."DeviceLogRaw";
    IF legacy_log_count <> 0 THEN
        RAISE EXCEPTION 'Legacy DeviceLogRaw has % row(s). Archive it explicitly before this migration; audit data is not silently discarded.', legacy_log_count;
    END IF;

    SELECT string_agg(format('%I.%I (%I)', ns.nspname, rel.relname, con.conname), ', ')
    INTO unexpected_dependencies
    FROM pg_constraint con
    JOIN pg_class rel ON rel.oid = con.conrelid
    JOIN pg_namespace ns ON ns.oid = rel.relnamespace
    WHERE con.contype = 'f'
      AND con.confrelid IN (
          'axionpro."DeviceCommandMaster"'::regclass,
          'axionpro."DeviceCommandQueue"'::regclass,
          'axionpro."DeviceLogRaw"'::regclass)
      AND con.conrelid NOT IN (
          'axionpro."DeviceCommandMaster"'::regclass,
          'axionpro."DeviceCommandQueue"'::regclass,
          'axionpro."DeviceLogRaw"'::regclass);

    IF unexpected_dependencies IS NOT NULL THEN
        RAISE EXCEPTION 'Unexpected foreign-key dependencies prevent legacy device table removal: %', unexpected_dependencies;
    END IF;

    SELECT string_agg(format('%I.%I', ns.nspname, rel.relname), ', ')
    INTO unexpected_dependencies
    FROM pg_depend dep
    JOIN pg_rewrite rule ON rule.oid = dep.objid
    JOIN pg_class rel ON rel.oid = rule.ev_class
    JOIN pg_namespace ns ON ns.oid = rel.relnamespace
    WHERE dep.refobjid IN (
          'axionpro."DeviceCommandMaster"'::regclass,
          'axionpro."DeviceCommandQueue"'::regclass,
          'axionpro."DeviceLogRaw"'::regclass)
      AND rel.relkind IN ('v', 'm');

    IF unexpected_dependencies IS NOT NULL THEN
        RAISE EXCEPTION 'Views/materialized views depend on legacy device tables: %', unexpected_dependencies;
    END IF;
END $$;

-- No CASCADE by design. PostgreSQL will fail rather than hide any missed dependency.
DROP TABLE axionpro."DeviceCommandQueue";
DROP TABLE axionpro."DeviceLogRaw";
DROP TABLE axionpro."DeviceCommandMaster";

COMMIT;
