-- Tenant Email Template module, tenant-owned template table, and initial data.
-- Idempotent: rerunning does not duplicate modules, mappings, entitlements, or templates.
BEGIN;

CREATE TABLE IF NOT EXISTS axionpro."TenantEmailTemplate"
(
    "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "TenantId" bigint NOT NULL,
    "TemplateName" character varying(150) NOT NULL,
    "TemplateCode" character varying(100),
    "Subject" character varying(250) NOT NULL,
    "Body" text NOT NULL,
    "FromEmail" character varying(150),
    "FromName" character varying(100),
    "CcEmail" text,
    "BccEmail" text,
    "Category" character varying(100),
    "LanguageCode" character varying(10),
    "IsActive" boolean NOT NULL DEFAULT TRUE,
    "AddedById" bigint NOT NULL,
    "AddedDateTime" timestamp with time zone NOT NULL DEFAULT now(),
    "UpdatedById" bigint,
    "UpdatedDateTime" timestamp with time zone,
    "AddedFromIP" character varying(50),
    "UpdatedFromIP" character varying(50),
    CONSTRAINT "FK_TenantEmailTemplate_Tenant" FOREIGN KEY ("TenantId")
        REFERENCES axionpro."Tenant" ("Id") ON DELETE CASCADE
);

CREATE UNIQUE INDEX IF NOT EXISTS "UX_TenantEmailTemplate_Tenant_TemplateCode"
    ON axionpro."TenantEmailTemplate" ("TenantId", "TemplateCode");

INSERT INTO axionpro."TenantEmailTemplate"
(
    "TenantId", "TemplateName", "TemplateCode", "Subject", "Body", "FromEmail", "FromName",
    "CcEmail", "BccEmail", "Category", "LanguageCode", "IsActive", "AddedById", "AddedDateTime",
    "UpdatedById", "UpdatedDateTime", "AddedFromIP", "UpdatedFromIP"
)
SELECT tenant."Id", template."TemplateName", template."TemplateCode", template."Subject", template."Body",
       template."FromEmail", template."FromName", template."CcEmail", template."BccEmail", template."Category",
       template."LanguageCode", template."IsActive", template."AddedById", template."AddedDateTime",
       template."UpdatedById", template."UpdatedDateTime", template."AddedFromIP", template."UpdatedFromIP"
FROM axionpro."Tenant" tenant
CROSS JOIN axionpro."EmailTemplate" template
WHERE NOT EXISTS
(
    SELECT 1 FROM axionpro."TenantEmailTemplate" existing
    WHERE existing."TenantId" = tenant."Id"
      AND existing."TemplateCode" IS NOT DISTINCT FROM template."TemplateCode"
);

INSERT INTO axionpro."Module"
(
    "TenantId", "ModuleCode", "ModuleName", "PageName", "DisplayName", "URLPath", "ParentModuleId",
    "IsLeafNode", "IsModuleDisplayInUI", "IsCommonMenu", "IsActive", "ImageIconWeb", "ImageIconMobile",
    "ItemPriority", "Remark", "AddedById", "AddedDateTime", "ModuleScope"
)
SELECT NULL, 'TENANT_EMAIL_TEMPLATE', 'Tenant Email Templates', 'tenant-email-templates', 'Email Templates',
       '/app/tenant-email-templates', parent."Id", TRUE, TRUE, FALSE, TRUE, 'bi bi-envelope-paper', 'mail',
       420, 'Tenant-owned email template management.', 1, CURRENT_TIMESTAMP, 1
FROM axionpro."Module" parent
WHERE parent."Id" = 46
  AND parent."ModuleCode" = 'TENANT_EMAIL_CONFIG'
  AND NOT EXISTS (SELECT 1 FROM axionpro."Module" existing WHERE existing."ModuleCode" = 'TENANT_EMAIL_TEMPLATE');

DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM axionpro."Module" WHERE "Id" = 46 AND "ModuleCode" = 'TENANT_EMAIL_CONFIG') THEN
        RAISE EXCEPTION 'Parent TENANT_EMAIL_CONFIG Module Id 46 was not found.';
    END IF;
END $$;

INSERT INTO axionpro."ModuleOperationMapping"
(
    "ModuleId", "OperationId", "PageURL", "IconURL", "IsCommonItem", "IsOperational", "Priority",
    "Remark", "IsActive", "AddedById", "AddedDateTime"
)
SELECT module."Id", operation."Id", '/app/tenant-email-templates',
       CASE operation."OperationName" WHEN 'Add' THEN 'plus-circle' WHEN 'Update' THEN 'pencil-square'
            WHEN 'Delete' THEN 'trash3' ELSE 'eye' END,
       FALSE, TRUE,
       CASE operation."OperationName" WHEN 'View' THEN 1 WHEN 'Add' THEN 2 WHEN 'Update' THEN 3 ELSE 4 END,
       operation."OperationName" || ' Tenant email templates.', TRUE, 1, CURRENT_TIMESTAMP
FROM axionpro."Module" module
JOIN axionpro."Operation" operation ON operation."Id" IN (1, 2, 3, 4) AND operation."IsActive" = TRUE
WHERE module."ModuleCode" = 'TENANT_EMAIL_TEMPLATE'
  AND NOT EXISTS
  (
      SELECT 1 FROM axionpro."ModuleOperationMapping" existing
      WHERE existing."ModuleId" = module."Id" AND existing."OperationId" = operation."Id"
  );

INSERT INTO axionpro."PlanModuleMapping"
    ("SubscriptionPlanId", "ModuleId", "IsActive", "Remark", "AddedById", "AddedDateTime")
SELECT parentMapping."SubscriptionPlanId", child."Id", TRUE, 'Tenant Email Templates inherited from Email Settings.',
       1, CURRENT_TIMESTAMP
FROM axionpro."PlanModuleMapping" parentMapping
JOIN axionpro."Module" child ON child."ModuleCode" = 'TENANT_EMAIL_TEMPLATE'
WHERE parentMapping."ModuleId" = 46 AND parentMapping."IsActive" = TRUE
  AND NOT EXISTS
  (
      SELECT 1 FROM axionpro."PlanModuleMapping" existing
      WHERE existing."SubscriptionPlanId" = parentMapping."SubscriptionPlanId" AND existing."ModuleId" = child."Id"
  );

INSERT INTO axionpro."TenantEnabledModule"
    ("TenantId", "ParentModuleId", "ModuleId", "IsLeafNode", "IsEnabled", "AddedById", "AddedDateTime")
SELECT enabled."TenantId", 46, child."Id", TRUE, TRUE, enabled."AddedById", CURRENT_TIMESTAMP
FROM axionpro."TenantEnabledModule" enabled
JOIN axionpro."Module" child ON child."ModuleCode" = 'TENANT_EMAIL_TEMPLATE'
WHERE enabled."ModuleId" = 46 AND enabled."IsEnabled" = TRUE
  AND NOT EXISTS
  (
      SELECT 1 FROM axionpro."TenantEnabledModule" existing
      WHERE existing."TenantId" = enabled."TenantId" AND existing."ModuleId" = child."Id"
  );

INSERT INTO axionpro."TenantEnabledOperation"
    ("TenantId", "ModuleId", "OperationId", "IsOperationUsed", "IsEnabled", "AddedById", "AddedDateTime")
SELECT enabled."TenantId", enabled."ModuleId", mapping."OperationId", TRUE, TRUE, enabled."AddedById", CURRENT_TIMESTAMP
FROM axionpro."TenantEnabledModule" enabled
JOIN axionpro."Module" module ON module."Id" = enabled."ModuleId" AND module."ModuleCode" = 'TENANT_EMAIL_TEMPLATE'
JOIN axionpro."ModuleOperationMapping" mapping ON mapping."ModuleId" = enabled."ModuleId" AND mapping."IsActive" = TRUE
WHERE NOT EXISTS
(
    SELECT 1 FROM axionpro."TenantEnabledOperation" existing
    WHERE existing."TenantId" = enabled."TenantId" AND existing."ModuleId" = enabled."ModuleId"
      AND existing."OperationId" = mapping."OperationId"
);

COMMIT;
