// ================================================================
// Purpose : Host-only procurement inventory for physical Tenant cards.
// ================================================================

using System.Security.Cryptography;
using System.Text;
using axionpro.application.Common.Helpers;
using axionpro.application.Constants;
using axionpro.application.DTOS.Host;
using axionpro.application.Exceptions;
using axionpro.application.Interfaces;
using axionpro.application.Interfaces.ICommonRequest;
using axionpro.application.Interfaces.IEncryptionService;
using axionpro.application.Wrappers;
using axionpro.domain.Entity;
using MediatR;
using Microsoft.Extensions.Logging;

namespace axionpro.application.Features.HostDeviceCmd.Handlers;

public sealed class CreateTenantCardMasterCommand(CreateTenantCardMasterRequestDTO dto) : IRequest<ApiResponse<TenantCardMasterResponseDTO>> { public CreateTenantCardMasterRequestDTO DTO { get; } = dto; }
public sealed class UpdateTenantCardMasterCommand(UpdateTenantCardMasterRequestDTO dto) : IRequest<ApiResponse<TenantCardMasterResponseDTO>> { public UpdateTenantCardMasterRequestDTO DTO { get; } = dto; }
public sealed class UpdateTenantCardMasterStatusCommand(UpdateTenantCardMasterStatusRequestDTO dto) : IRequest<ApiResponse<TenantCardMasterResponseDTO>> { public UpdateTenantCardMasterStatusRequestDTO DTO { get; } = dto; }
public sealed class DeleteTenantCardMasterCommand(string id, TenantDeviceAccessRequestDTO access) : IRequest<ApiResponse<bool>> { public string Id { get; } = id; public TenantDeviceAccessRequestDTO AccessRequest { get; } = access; }
public sealed class GetTenantCardMasterByIdQuery(string id, TenantDeviceAccessRequestDTO access) : IRequest<ApiResponse<TenantCardMasterResponseDTO>> { public string Id { get; } = id; public TenantDeviceAccessRequestDTO AccessRequest { get; } = access; }
public sealed class GetTenantCardMastersQuery(TenantCardMasterFilterRequestDTO filter) : IRequest<ApiResponse<List<TenantCardMasterResponseDTO>>> { public TenantCardMasterFilterRequestDTO Filter { get; } = filter; }

public abstract class TenantCardMasterHandlerBase(IUnitOfWork u, ICommonRequestService c, IIdEncoderService ids, IEncryptionService encryption, ILogger<axionpro.application.Features.TenantConfigurationCmd.Handlers.TenantConfigurationHandlerBase> l)
    : TenantDeviceAccessHandlerBase(u, c, ids, l)
{
    protected IEncryptionService Encryption { get; } = encryption;
    protected static string Hash(string number, string key) => Convert.ToHexString(HMACSHA256.HashData(Encoding.UTF8.GetBytes(key), Encoding.UTF8.GetBytes(number))).ToLowerInvariant();
    protected static void Validate(TenantCardMasterRequestDTO d, bool numberRequired)
    {
        if (numberRequired && (string.IsNullOrWhiteSpace(d.CardNumber) || d.CardNumber.Length > 19 || d.CardNumber.Any(x => !char.IsAsciiDigit(x)))) throw new ValidationErrorException("Card number must contain up to 19 digits.");
        if (d.UnitPurchasePriceExcludingTax < 0 || d.CgstAmount < 0 || d.SgstAmount < 0 || d.IgstAmount < 0 || d.ForeignTaxAmount < 0 || d.CustomsDutyAmount < 0 || d.FreightAmount < 0 || string.IsNullOrWhiteSpace(d.PurchaseCurrencyCode) || d.PurchaseCurrencyCode.Trim().Length != 3) throw new ValidationErrorException("Enter valid invoice purchase and tax amounts.");
    }
    protected TenantCardMasterResponseDTO Map(TenantCardMaster e, TenantDeviceAccessScope s)
    {
        var card = Encryption.Decrypt(e.CardNumberEncrypted, s.TenantEncryptionKey);
        return new TenantCardMasterResponseDTO { Id = EncryptIdentifier(e.Id, s.TenantEncryptionKey), TenantId = HostTenantIdentifierProtector.Encrypt(e.TenantId, s.TenantEncryptionKey, IdEncoder), MaskedCardNumber = card.Length <= 4 ? "****" : $"****{card[^4..]}", CardReference = e.CardReference, CardStatus = (TenantCardStatus)e.CardStatus, PurchaseCurrencyCode = e.PurchaseCurrencyCode, UnitPurchasePriceExcludingTax = e.UnitPurchasePriceExcludingTax, SupplierCountryId = e.SupplierCountryId, SupplierStateId = e.SupplierStateId, PlaceOfSupplyCountryId = e.PlaceOfSupplyCountryId, PlaceOfSupplyStateId = e.PlaceOfSupplyStateId, SupplierName = e.SupplierName, SupplierTaxRegistrationNumber = e.SupplierTaxRegistrationNumber, PurchaseInvoiceNumber = e.PurchaseInvoiceNumber, PurchaseInvoiceDate = e.PurchaseInvoiceDate, TaxTreatment = (TenantCardTaxTreatment)e.TaxTreatment, CgstRate = e.CgstRate, CgstAmount = e.CgstAmount, SgstRate = e.SgstRate, SgstAmount = e.SgstAmount, IgstRate = e.IgstRate, IgstAmount = e.IgstAmount, ForeignTaxLabel = e.ForeignTaxLabel, ForeignTaxRate = e.ForeignTaxRate, ForeignTaxAmount = e.ForeignTaxAmount, CustomsDutyAmount = e.CustomsDutyAmount, FreightAmount = e.FreightAmount, LandedCost = e.LandedCost, IsActive = e.IsActive, AddedDateTime = e.AddedDateTime, UpdatedDateTime = e.UpdatedDateTime };
    }
    protected IIdEncoderService IdEncoder { get; } = ids;
    protected static void Apply(TenantCardMaster e, TenantCardMasterRequestDTO d) { e.CardReference = d.CardReference?.Trim(); e.PurchaseCurrencyCode = d.PurchaseCurrencyCode.Trim().ToUpperInvariant(); e.UnitPurchasePriceExcludingTax = d.UnitPurchasePriceExcludingTax; e.SupplierCountryId = d.SupplierCountryId; e.SupplierStateId = d.SupplierStateId; e.PlaceOfSupplyCountryId = d.PlaceOfSupplyCountryId; e.PlaceOfSupplyStateId = d.PlaceOfSupplyStateId; e.SupplierName = d.SupplierName?.Trim(); e.SupplierTaxRegistrationNumber = d.SupplierTaxRegistrationNumber?.Trim(); e.PurchaseInvoiceNumber = d.PurchaseInvoiceNumber?.Trim(); e.PurchaseInvoiceDate = d.PurchaseInvoiceDate; e.TaxTreatment = (short)d.TaxTreatment; e.CgstRate = d.CgstRate; e.CgstAmount = d.CgstAmount; e.SgstRate = d.SgstRate; e.SgstAmount = d.SgstAmount; e.IgstRate = d.IgstRate; e.IgstAmount = d.IgstAmount; e.ForeignTaxLabel = d.ForeignTaxLabel?.Trim(); e.ForeignTaxRate = d.ForeignTaxRate; e.ForeignTaxAmount = d.ForeignTaxAmount; e.CustomsDutyAmount = d.CustomsDutyAmount; e.FreightAmount = d.FreightAmount; e.LandedCost = d.UnitPurchasePriceExcludingTax + d.CgstAmount + d.SgstAmount + d.IgstAmount + d.ForeignTaxAmount + d.CustomsDutyAmount + d.FreightAmount; e.IsActive = d.IsActive; }
}

public sealed class CreateTenantCardMasterCommandHandler(IUnitOfWork u, ICommonRequestService c, IIdEncoderService ids, IEncryptionService e, ILogger<axionpro.application.Features.TenantConfigurationCmd.Handlers.TenantConfigurationHandlerBase> l) : TenantCardMasterHandlerBase(u,c,ids,e,l), IRequestHandler<CreateTenantCardMasterCommand,ApiResponse<TenantCardMasterResponseDTO>>
{ public async Task<ApiResponse<TenantCardMasterResponseDTO>> Handle(CreateTenantCardMasterCommand r, CancellationToken ct) { var d=r.DTO??throw new ValidationErrorException("Card data is required."); var s=await ResolveHostDeviceAssignmentScopeAsync(d,ct); Validate(d,true); var n=d.CardNumber.Trim(); if(await UnitOfWork.TenantCardMasterRepository.CardHashExistsAsync(s.TenantId,Hash(n,s.TenantEncryptionKey),null,ct))throw new ConflictException("This card already exists in the selected Tenant inventory."); var x=new TenantCardMaster{TenantId=s.TenantId,CardNumberEncrypted=Encryption.Encrypt(n,s.TenantEncryptionKey),CardNumberLookupHash=Hash(n,s.TenantEncryptionKey),CardStatus=(short)TenantCardStatus.Available,AddedById=s.ActorId,AddedDateTime=DateTime.UtcNow};Apply(x,d);await UnitOfWork.TenantCardMasterRepository.AddAsync(x,ct);await UnitOfWork.SaveChangesAsync(ct);return ApiResponse<TenantCardMasterResponseDTO>.Success(Map(x,s),"Tenant card inventory item created successfully.");} }
public sealed class UpdateTenantCardMasterCommandHandler(IUnitOfWork u,ICommonRequestService c,IIdEncoderService ids,IEncryptionService e,ILogger<axionpro.application.Features.TenantConfigurationCmd.Handlers.TenantConfigurationHandlerBase> l) : TenantCardMasterHandlerBase(u,c,ids,e,l),IRequestHandler<UpdateTenantCardMasterCommand,ApiResponse<TenantCardMasterResponseDTO>>
{ public async Task<ApiResponse<TenantCardMasterResponseDTO>> Handle(UpdateTenantCardMasterCommand r,CancellationToken ct){var d=r.DTO??throw new ValidationErrorException("Card data is required.");var s=await ResolveHostDeviceAssignmentScopeAsync(d,ct);var x=await UnitOfWork.TenantCardMasterRepository.GetForUpdateAsync(s.TenantId,DecodeIdentifier(d.Id,s,"TenantCardId"),ct)??throw new NotFoundException("Tenant card was not found.");if(x.CardStatus==(short)TenantCardStatus.Assigned)throw new ValidationErrorException("An assigned card cannot be edited. Unbind it first.");Validate(d,!string.IsNullOrWhiteSpace(d.CardNumber));if(!string.IsNullOrWhiteSpace(d.CardNumber)){var n=d.CardNumber.Trim();if(await UnitOfWork.TenantCardMasterRepository.CardHashExistsAsync(s.TenantId,Hash(n,s.TenantEncryptionKey),x.Id,ct))throw new ConflictException("This card already exists in the selected Tenant inventory.");x.CardNumberEncrypted=Encryption.Encrypt(n,s.TenantEncryptionKey);x.CardNumberLookupHash=Hash(n,s.TenantEncryptionKey);}Apply(x,d);x.UpdatedById=s.ActorId;x.UpdatedDateTime=DateTime.UtcNow;await UnitOfWork.SaveChangesAsync(ct);return ApiResponse<TenantCardMasterResponseDTO>.Success(Map(x,s),"Tenant card inventory item updated successfully.");} }
public sealed class GetTenantCardMasterByIdQueryHandler(IUnitOfWork u,ICommonRequestService c,IIdEncoderService ids,IEncryptionService e,ILogger<axionpro.application.Features.TenantConfigurationCmd.Handlers.TenantConfigurationHandlerBase> l):TenantCardMasterHandlerBase(u,c,ids,e,l),IRequestHandler<GetTenantCardMasterByIdQuery,ApiResponse<TenantCardMasterResponseDTO>>
{public async Task<ApiResponse<TenantCardMasterResponseDTO>> Handle(GetTenantCardMasterByIdQuery r,CancellationToken ct){var s=await ResolveHostDeviceAssignmentScopeAsync(r.AccessRequest,ct);var x=await UnitOfWork.TenantCardMasterRepository.GetByIdAsync(s.TenantId,DecodeIdentifier(r.Id,s,"TenantCardId"),ct)??throw new NotFoundException("Tenant card was not found.");return ApiResponse<TenantCardMasterResponseDTO>.Success(Map(x,s));}}
public sealed class GetTenantCardMastersQueryHandler(IUnitOfWork u,ICommonRequestService c,IIdEncoderService ids,IEncryptionService e,ILogger<axionpro.application.Features.TenantConfigurationCmd.Handlers.TenantConfigurationHandlerBase> l):TenantCardMasterHandlerBase(u,c,ids,e,l),IRequestHandler<GetTenantCardMastersQuery,ApiResponse<List<TenantCardMasterResponseDTO>>>
{public async Task<ApiResponse<List<TenantCardMasterResponseDTO>>> Handle(GetTenantCardMastersQuery r,CancellationToken ct){var d=r.Filter??new();var s=await ResolveHostDeviceAssignmentScopeAsync(d,ct);var p=await UnitOfWork.TenantCardMasterRepository.GetPagedAsync(s.TenantId,d,ct);return ApiResponse<List<TenantCardMasterResponseDTO>>.SuccessPaginated(p.Data.Select(x=>Map(x,s)).ToList(),p.PageNumber,p.PageSize,p.TotalCount,(int)Math.Ceiling(p.TotalCount/(double)p.PageSize),"Tenant card inventory retrieved successfully.");}}
public sealed class UpdateTenantCardMasterStatusCommandHandler(IUnitOfWork u,ICommonRequestService c,IIdEncoderService ids,IEncryptionService e,ILogger<axionpro.application.Features.TenantConfigurationCmd.Handlers.TenantConfigurationHandlerBase> l):TenantCardMasterHandlerBase(u,c,ids,e,l),IRequestHandler<UpdateTenantCardMasterStatusCommand,ApiResponse<TenantCardMasterResponseDTO>>
{public async Task<ApiResponse<TenantCardMasterResponseDTO>> Handle(UpdateTenantCardMasterStatusCommand r,CancellationToken ct){var d=r.DTO??throw new ValidationErrorException("Card status is required.");var s=await ResolveHostDeviceAssignmentScopeAsync(d,ct);var x=await UnitOfWork.TenantCardMasterRepository.GetForUpdateAsync(s.TenantId,DecodeIdentifier(d.Id,s,"TenantCardId"),ct)??throw new NotFoundException("Tenant card was not found.");if(x.CardStatus==(short)TenantCardStatus.Assigned&&!d.IsActive)throw new ValidationErrorException("Unbind an assigned card before deactivation.");x.IsActive=d.IsActive;x.UpdatedById=s.ActorId;x.UpdatedDateTime=DateTime.UtcNow;await UnitOfWork.SaveChangesAsync(ct);return ApiResponse<TenantCardMasterResponseDTO>.Success(Map(x,s),"Tenant card status updated successfully.");}}
public sealed class DeleteTenantCardMasterCommandHandler(IUnitOfWork u,ICommonRequestService c,IIdEncoderService ids,IEncryptionService e,ILogger<axionpro.application.Features.TenantConfigurationCmd.Handlers.TenantConfigurationHandlerBase> l):TenantCardMasterHandlerBase(u,c,ids,e,l),IRequestHandler<DeleteTenantCardMasterCommand,ApiResponse<bool>>
{public async Task<ApiResponse<bool>> Handle(DeleteTenantCardMasterCommand r,CancellationToken ct){var s=await ResolveHostDeviceAssignmentScopeAsync(r.AccessRequest,ct);var x=await UnitOfWork.TenantCardMasterRepository.GetForUpdateAsync(s.TenantId,DecodeIdentifier(r.Id,s,"TenantCardId"),ct)??throw new NotFoundException("Tenant card was not found.");if(await UnitOfWork.TenantCardMasterRepository.HasActiveEnrollmentAssignmentAsync(s.TenantId,x.Id,ct))throw new ValidationErrorException("Unbind the card from active employee enrollments before deleting it.");x.IsActive=false;x.IsSoftDeleted=true;x.SoftDeletedById=s.ActorId;x.SoftDeletedDateTime=DateTime.UtcNow;await UnitOfWork.SaveChangesAsync(ct);return ApiResponse<bool>.Success(true,"Tenant card inventory item deleted successfully.");}}
