"""Generate an additive state supplement from GeoNames admin1CodesASCII.txt.

Existing IN/CN/DE/US postal hierarchies and the UAE catalogue remain authoritative.
Their state codes are not interchangeable with GeoNames ADM1 codes. No existing
row is overwritten, and no country or dummy state is created.
"""

import argparse
import hashlib
from pathlib import Path
from GenerateFourCountryPostalSeed import write_values


PRESERVED_COUNTRIES = {"IN", "CN", "DE", "US", "AE"}


def generate(source_path, output_path):
    content = Path(source_path).read_bytes()
    rows = []
    seen = set()
    for line in content.decode("utf-8").splitlines():
        code, name, ascii_name, geoname_id = line.split("\t")
        country_code, state_code = code.split(".", 1)
        assert len(country_code) == 2 and state_code and geoname_id.isdigit()
        assert code not in seen, "Duplicate source ADM1 code: " + code
        assert len(name) <= 100 and len(state_code) <= 30, "Source exceeds State schema"
        seen.add(code)
        rows.append((country_code, state_code, name, ascii_name, geoname_id))
    assert len(rows) > 3500
    with open(output_path, "w", encoding="utf-8", newline="\n") as output:
        output.write("""-- Global State supplement: generated by location-seed/GenerateGlobalStateSeed.py.
-- Source: https://download.geonames.org/export/dump/admin1CodesASCII.txt
-- Retrieved 2026-10-01. GeoNames CC BY 4.0 https://creativecommons.org/licenses/by/4.0/
-- ADM1 is first-order administrative division (state/province/region/territory).
-- Public reference data; source coverage is not a guarantee of official completeness.
-- Preserves existing IN/CN/DE/US postal hierarchies and the UAE catalogue/codes.
-- Additive only: no Country/State updates, no deletes, no District/Locality writes.
""")
        output.write("-- Source SHA256: " + hashlib.sha256(content).hexdigest() + "\n")
        output.write(f"-- Source contains {len(rows)} ADM1 rows across {len({row[0] for row in rows})} country codes.\n")
        output.write("""BEGIN;
SET LOCAL lock_timeout = '30s';
SET LOCAL statement_timeout = '5min';
SELECT pg_advisory_xact_lock(20261001, 249);
CREATE TEMP TABLE global_state_seed (
    country_code text, state_code text, name text, ascii_name text, geoname_id text,
    PRIMARY KEY (country_code, state_code)
) ON COMMIT DROP;
""")
        write_values(output, "global_state_seed", sorted(rows),
                     "(country_code, state_code, name, ascii_name, geoname_id)")
        output.write("""
-- Preserve identities and stored codes in the five established detailed catalogues.
-- Elsewhere a code OR exact native/ASCII name match preserves the existing row.
INSERT INTO axionpro."State" ("CountryId", "StateCode", "StateName", "IsActive")
SELECT c."Id", seed.state_code, seed.name, TRUE
FROM global_state_seed seed
JOIN axionpro."Country" c ON c."CountryCode" = seed.country_code
WHERE seed.country_code NOT IN ('IN', 'CN', 'DE', 'US', 'AE')
  AND c."IsActive" = TRUE
  AND NOT EXISTS (
      SELECT 1 FROM axionpro."State" s WHERE s."CountryId" = c."Id"
        AND (s."StateCode" = seed.state_code
             OR lower(s."StateName") IN (lower(seed.name), lower(seed.ascii_name)))
  );
DO $$
BEGIN
    IF EXISTS (
        SELECT 1 FROM global_state_seed seed
        JOIN axionpro."Country" c ON c."CountryCode" = seed.country_code AND c."IsActive" = TRUE
        WHERE seed.country_code NOT IN ('IN', 'CN', 'DE', 'US', 'AE')
          AND NOT EXISTS (
              SELECT 1 FROM axionpro."State" s WHERE s."CountryId" = c."Id" AND s."IsActive" = TRUE
                AND (s."StateCode" = seed.state_code
                     OR lower(s."StateName") IN (lower(seed.name), lower(seed.ascii_name)))
          )
    ) THEN
        RAISE EXCEPTION 'State coverage is incomplete or an existing matched state is inactive; rollback for review';
    END IF;
END $$;
-- Coverage, including source gaps: never silently invent a state for these countries.
SELECT c."CountryCode", c."CountryName", count(s."Id") AS active_states,
       CASE WHEN c."CountryCode" IN ('IN','CN','DE','US','AE') THEN 'existing detailed catalogue'
            WHEN EXISTS (SELECT 1 FROM global_state_seed seed WHERE seed.country_code=c."CountryCode")
            THEN 'GeoNames ADM1' ELSE 'no ADM1 in source' END AS coverage
FROM axionpro."Country" c
LEFT JOIN axionpro."State" s ON s."CountryId"=c."Id" AND s."IsActive"=TRUE
WHERE c."IsActive"=TRUE
GROUP BY c."Id", c."CountryCode", c."CountryName"
ORDER BY c."CountryCode";
COMMIT;
""")
    print(f"Generated {len(rows)} source states across {len({row[0] for row in rows})} source country codes")


if __name__ == "__main__":
    parser = argparse.ArgumentParser()
    parser.add_argument("source_path")
    parser.add_argument("output_path")
    args = parser.parse_args()
    generate(args.source_path, args.output_path)
