"""Generate the additive UAE catalogue from the public GeoNames AE.zip export.

GeoNames data: https://download.geonames.org/export/dump/AE.zip (CC BY 4.0).
ADM1 maps to State, ADM2 to District, ADM3 and current populated places to
Locality. Missing ADM2 uses the existing Unassigned District seed convention;
no coordinates are used to guess administrative membership or postal codes.
"""

import argparse
import hashlib
import zipfile
from collections import Counter
from GenerateFourCountryPostalSeed import write_values


# GeoNames FIPS -> ISO subdivision code and UAE government English display name.
# https://www.geonames.org/AE/administrative-division-united-arab-emirates.html
# https://u.ae/en/about-the-uae/the-seven-emirates
EMIRATES = {
    "01": ("AZ", "Abu Dhabi"),
    "02": ("AJ", "Ajman"),
    "03": ("DU", "Dubai"),
    "04": ("FU", "Fujairah"),
    "05": ("RK", "Ras Al Khaimah"),
    "06": ("SH", "Sharjah"),
    "07": ("UQ", "Umm Al Quwain"),
}
CURRENT_PLACES = {"PPL", "PPLA", "PPLA2", "PPLA3", "PPLA4", "PPLC", "PPLX"}


def generate(archive_path, output_path):
    with zipfile.ZipFile(archive_path) as archive:
        content = archive.read("AE.txt")
    rows = [line.split("\t") for line in content.decode("utf-8").splitlines()]
    rows = [row for row in rows if len(row) >= 19 and row[8] == "AE"]
    assert {row[10] for row in rows if row[7] == "ADM1"} == set(EMIRATES)
    districts = {
        (row[10], row[11]): row[2] or row[1]
        for row in rows if row[7] == "ADM2" and row[10] in EMIRATES and row[11]
    }
    localities = []
    excluded = Counter()
    for row in rows:
        if row[7] not in CURRENT_PLACES and row[7] != "ADM3":
            continue
        if row[10] not in EMIRATES:
            excluded["missing_emirate"] += 1
            continue
        district_code = row[11]
        if not district_code:
            district_code = "UNASSIGNED"
            districts[(row[10], district_code)] = EMIRATES[row[10]][1] + " - Unassigned District"
        elif (row[10], district_code) not in districts:
            raise ValueError("Unresolved source district: " + row[0])
        name = row[2] or row[1]
        assert len(name) <= 100, "Locality name exceeds schema: " + row[0]
        localities.append((EMIRATES[row[10]][0], district_code, "GN-" + row[0], name))
    assert len(localities) > 2000
    assert len(districts) >= 28
    assert {row[0] for row in localities} == {value[0] for value in EMIRATES.values()}
    with open(output_path, "w", encoding="utf-8", newline="\n") as output:
        output.write("""-- UAE geography; generated by location-seed/GenerateUaeLocationSeed.py.
-- Source: https://download.geonames.org/export/dump/AE.zip, retrieved 2026-10-01.
-- Attribution: GeoNames, CC BY 4.0 https://creativecommons.org/licenses/by/4.0/
-- Public community catalogue, not a guarantee of complete official coverage.
-- ADM1 -> State; ADM2 -> District; ADM3/current populated places -> Locality.
-- Unassigned District means the source does not provide ADM2 membership.
-- PostalCode stays NULL; existing IDs, rows and all other countries are preserved.
""")
        output.write("-- AE.txt SHA256: " + hashlib.sha256(content).hexdigest() + "\n")
        output.write(f"-- Source rows: 7 states, {len(districts)} districts, {len(localities)} localities.\n")
        output.write(f"-- Excluded current places with missing emirate: {excluded['missing_emirate']}.\n")
        output.write("""BEGIN;
SET LOCAL lock_timeout = '30s';
SET LOCAL statement_timeout = '5min';
-- Serialize concurrent runs without locking unrelated country readers.
SELECT pg_advisory_xact_lock(20261001, 784);
DO $$
BEGIN
    IF (SELECT count(*) FROM axionpro."Country" WHERE "CountryCode" = 'AE' AND "IsActive" = TRUE) <> 1 THEN
        RAISE EXCEPTION 'Exactly one active AE country is required';
    END IF;
    IF NOT EXISTS (SELECT 1 FROM axionpro."LocalityType" WHERE "Id" = 4 AND "TypeName" = 'Other / Unclassified') THEN
        RAISE EXCEPTION 'Existing Other / Unclassified locality type 4 is required';
    END IF;
END $$;
CREATE TEMP TABLE uae_states (code text PRIMARY KEY, name text) ON COMMIT DROP;
CREATE TEMP TABLE uae_districts (state_code text, code text, name text, PRIMARY KEY(state_code, code)) ON COMMIT DROP;
CREATE TEMP TABLE uae_localities (state_code text, district_code text, code text PRIMARY KEY, name text) ON COMMIT DROP;
""")
        write_values(output, "uae_states", sorted(EMIRATES.values()), "(code, name)")
        write_values(output, "uae_districts", sorted(
            (EMIRATES[state][0], code, name) for (state, code), name in districts.items()
        ), "(state_code, code, name)")
        write_values(output, "uae_localities", sorted(localities), "(state_code, district_code, code, name)")
        output.write("""
INSERT INTO axionpro."State" ("CountryId", "StateCode", "StateName", "IsActive")
SELECT c."Id", seed.code, seed.name, TRUE
FROM uae_states seed CROSS JOIN axionpro."Country" c
WHERE c."CountryCode" = 'AE' AND NOT EXISTS (
    SELECT 1 FROM axionpro."State" s WHERE s."CountryId" = c."Id"
      AND (s."StateCode" = seed.code OR lower(s."StateName") = lower(seed.name))
);
CREATE TEMP TABLE uae_state_map ON COMMIT DROP AS
SELECT DISTINCT ON (seed.code) seed.code, s."Id" AS id
FROM uae_states seed JOIN axionpro."Country" c ON c."CountryCode" = 'AE'
JOIN axionpro."State" s ON s."CountryId" = c."Id"
 AND (s."StateCode" = seed.code OR lower(s."StateName") = lower(seed.name))
ORDER BY seed.code, CASE WHEN s."StateCode" = seed.code THEN 0 ELSE 1 END, s."Id";

INSERT INTO axionpro."District" ("StateId", "DistrictCode", "DistrictName", "IsActive", "Remark")
SELECT s.id, seed.code, seed.name, TRUE, 'GeoNames AE; CC BY 4.0; 2026-10-01'
FROM uae_districts seed JOIN uae_state_map s ON s.code = seed.state_code
WHERE NOT EXISTS (
    SELECT 1 FROM axionpro."District" d WHERE d."StateId" = s.id
      AND (d."DistrictCode" = seed.code OR lower(d."DistrictName") = lower(seed.name))
);
CREATE TEMP TABLE uae_district_map ON COMMIT DROP AS
SELECT DISTINCT ON (seed.state_code, seed.code) seed.state_code, seed.code, s.id AS state_id, d."Id" AS id
FROM uae_districts seed JOIN uae_state_map s ON s.code = seed.state_code
JOIN axionpro."District" d ON d."StateId" = s.id
 AND (d."DistrictCode" = seed.code OR lower(d."DistrictName") = lower(seed.name))
ORDER BY seed.state_code, seed.code, CASE WHEN d."DistrictCode" = seed.code THEN 0 ELSE 1 END, d."Id";

INSERT INTO axionpro."Locality" ("LocalityName", "LocalityCode", "PostalCode", "StateId", "DistrictId", "LocalityTypeId", "IsActive")
SELECT seed.name, seed.code, NULL, d.state_id, d.id, 4, TRUE
FROM uae_localities seed JOIN uae_district_map d ON d.state_code = seed.state_code AND d.code = seed.district_code
WHERE NOT EXISTS (
    SELECT 1 FROM axionpro."Locality" l WHERE l."DistrictId" = d.id AND l."LocalityCode" = seed.code
);
DO $$
BEGIN
    IF (SELECT count(*) FROM uae_state_map) <> 7
       OR (SELECT count(*) FROM uae_district_map) <> (SELECT count(*) FROM uae_districts)
       OR EXISTS (
           SELECT 1 FROM uae_localities seed
           JOIN uae_district_map d ON d.state_code = seed.state_code AND d.code = seed.district_code
           LEFT JOIN axionpro."Locality" l ON l."DistrictId" = d.id AND l."LocalityCode" = seed.code
           WHERE l."Id" IS NULL OR l."StateId" <> d.state_id OR l."IsActive" IS NOT TRUE
       ) THEN
        RAISE EXCEPTION 'UAE catalogue acceptance failed; transaction rolled back';
    END IF;
END $$;
SELECT (SELECT count(*) FROM uae_state_map) AS states,
       (SELECT count(*) FROM uae_district_map) AS districts,
       (SELECT count(*) FROM uae_localities) AS source_localities;
COMMIT;
""")
    print(f"Generated UAE seed: 7 states, {len(districts)} districts, {len(localities)} localities; excluded {dict(excluded)}")


if __name__ == "__main__":
    parser = argparse.ArgumentParser()
    parser.add_argument("archive_path")
    parser.add_argument("output_path")
    args = parser.parse_args()
    generate(args.archive_path, args.output_path)
