--
-- PostgreSQL database dump
--

\restrict 4WBaNzo23boehovFewc5YJ3mblT5q4ISgzzqATdTzC6TyHQ8ZxaD4UdgVNIn0E2

-- Dumped from database version 18.6 (Debian 18.6-1.pgdg12+2)
-- Dumped by pg_dump version 18.3

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- Data for Name: OrganizationHolidayCalendar; Type: TABLE DATA; Schema: axionpro; Owner: workforcedb_user
--

INSERT INTO axionpro."OrganizationHolidayCalendar" ("Id", "TenantId", "HolidayName", "HolidayDate", "IsOptional", "Description", "IsActive", "IsSoftDeleted", "AddedById", "AddedDateTime", "UpdatedById", "UpdatedDateTime", "SoftDeletedById", "DeletedDateTime", "TenantLocationId") VALUES (17, 8, 'Ambedkar Jayanti and Vaisakhi', '2026-04-14', true, 'MP government gazetted holiday 2026', true, false, NULL, '2026-09-22 16:34:52.097878+00', 4, '2026-09-23 12:53:10.640798+00', NULL, NULL, 5);
INSERT INTO axionpro."OrganizationHolidayCalendar" ("Id", "TenantId", "HolidayName", "HolidayDate", "IsOptional", "Description", "IsActive", "IsSoftDeleted", "AddedById", "AddedDateTime", "UpdatedById", "UpdatedDateTime", "SoftDeletedById", "DeletedDateTime", "TenantLocationId") VALUES (8, 8, 'Sant Ravidas Jayanti', '2026-02-01', false, 'MP government gazetted holiday 2026; Sunday', true, false, NULL, '2026-09-22 16:34:52.097878+00', NULL, NULL, NULL, NULL, 5);
INSERT INTO axionpro."OrganizationHolidayCalendar" ("Id", "TenantId", "HolidayName", "HolidayDate", "IsOptional", "Description", "IsActive", "IsSoftDeleted", "AddedById", "AddedDateTime", "UpdatedById", "UpdatedDateTime", "SoftDeletedById", "DeletedDateTime", "TenantLocationId") VALUES (9, 8, 'Maha Shivaratri', '2026-02-15', false, 'MP government gazetted holiday 2026; Sunday', true, false, NULL, '2026-09-22 16:34:52.097878+00', NULL, NULL, NULL, NULL, 5);
INSERT INTO axionpro."OrganizationHolidayCalendar" ("Id", "TenantId", "HolidayName", "HolidayDate", "IsOptional", "Description", "IsActive", "IsSoftDeleted", "AddedById", "AddedDateTime", "UpdatedById", "UpdatedDateTime", "SoftDeletedById", "DeletedDateTime", "TenantLocationId") VALUES (10, 8, 'Holi', '2026-03-03', false, 'MP government gazetted holiday 2026', true, false, NULL, '2026-09-22 16:34:52.097878+00', NULL, NULL, NULL, NULL, 5);
INSERT INTO axionpro."OrganizationHolidayCalendar" ("Id", "TenantId", "HolidayName", "HolidayDate", "IsOptional", "Description", "IsActive", "IsSoftDeleted", "AddedById", "AddedDateTime", "UpdatedById", "UpdatedDateTime", "SoftDeletedById", "DeletedDateTime", "TenantLocationId") VALUES (11, 8, 'Gudi Padwa', '2026-03-19', false, 'MP government gazetted holiday 2026', true, false, NULL, '2026-09-22 16:34:52.097878+00', NULL, NULL, NULL, NULL, 5);
INSERT INTO axionpro."OrganizationHolidayCalendar" ("Id", "TenantId", "HolidayName", "HolidayDate", "IsOptional", "Description", "IsActive", "IsSoftDeleted", "AddedById", "AddedDateTime", "UpdatedById", "UpdatedDateTime", "SoftDeletedById", "DeletedDateTime", "TenantLocationId") VALUES (12, 8, 'Cheti Chand', '2026-03-20', false, 'MP government gazetted holiday 2026', true, false, NULL, '2026-09-22 16:34:52.097878+00', NULL, NULL, NULL, NULL, 5);
INSERT INTO axionpro."OrganizationHolidayCalendar" ("Id", "TenantId", "HolidayName", "HolidayDate", "IsOptional", "Description", "IsActive", "IsSoftDeleted", "AddedById", "AddedDateTime", "UpdatedById", "UpdatedDateTime", "SoftDeletedById", "DeletedDateTime", "TenantLocationId") VALUES (13, 8, 'Eid-ul-Fitr', '2026-03-21', false, 'MP government gazetted holiday 2026', true, false, NULL, '2026-09-22 16:34:52.097878+00', NULL, NULL, NULL, NULL, 5);
INSERT INTO axionpro."OrganizationHolidayCalendar" ("Id", "TenantId", "HolidayName", "HolidayDate", "IsOptional", "Description", "IsActive", "IsSoftDeleted", "AddedById", "AddedDateTime", "UpdatedById", "UpdatedDateTime", "SoftDeletedById", "DeletedDateTime", "TenantLocationId") VALUES (14, 8, 'Ram Navami', '2026-03-27', false, 'MP government gazetted holiday 2026', true, false, NULL, '2026-09-22 16:34:52.097878+00', NULL, NULL, NULL, NULL, 5);
INSERT INTO axionpro."OrganizationHolidayCalendar" ("Id", "TenantId", "HolidayName", "HolidayDate", "IsOptional", "Description", "IsActive", "IsSoftDeleted", "AddedById", "AddedDateTime", "UpdatedById", "UpdatedDateTime", "SoftDeletedById", "DeletedDateTime", "TenantLocationId") VALUES (15, 8, 'Mahavir Jayanti', '2026-03-31', false, 'MP government gazetted holiday 2026', true, false, NULL, '2026-09-22 16:34:52.097878+00', NULL, NULL, NULL, NULL, 5);
INSERT INTO axionpro."OrganizationHolidayCalendar" ("Id", "TenantId", "HolidayName", "HolidayDate", "IsOptional", "Description", "IsActive", "IsSoftDeleted", "AddedById", "AddedDateTime", "UpdatedById", "UpdatedDateTime", "SoftDeletedById", "DeletedDateTime", "TenantLocationId") VALUES (16, 8, 'Good Friday', '2026-04-03', false, 'MP government gazetted holiday 2026', true, false, NULL, '2026-09-22 16:34:52.097878+00', NULL, NULL, NULL, NULL, 5);
INSERT INTO axionpro."OrganizationHolidayCalendar" ("Id", "TenantId", "HolidayName", "HolidayDate", "IsOptional", "Description", "IsActive", "IsSoftDeleted", "AddedById", "AddedDateTime", "UpdatedById", "UpdatedDateTime", "SoftDeletedById", "DeletedDateTime", "TenantLocationId") VALUES (18, 8, 'Parashuram Jayanti', '2026-04-20', false, 'MP government gazetted holiday 2026', true, false, NULL, '2026-09-22 16:34:52.097878+00', NULL, NULL, NULL, NULL, 5);
INSERT INTO axionpro."OrganizationHolidayCalendar" ("Id", "TenantId", "HolidayName", "HolidayDate", "IsOptional", "Description", "IsActive", "IsSoftDeleted", "AddedById", "AddedDateTime", "UpdatedById", "UpdatedDateTime", "SoftDeletedById", "DeletedDateTime", "TenantLocationId") VALUES (19, 8, 'Buddha Purnima', '2026-05-01', false, 'MP government gazetted holiday 2026', true, false, NULL, '2026-09-22 16:34:52.097878+00', NULL, NULL, NULL, NULL, 5);
INSERT INTO axionpro."OrganizationHolidayCalendar" ("Id", "TenantId", "HolidayName", "HolidayDate", "IsOptional", "Description", "IsActive", "IsSoftDeleted", "AddedById", "AddedDateTime", "UpdatedById", "UpdatedDateTime", "SoftDeletedById", "DeletedDateTime", "TenantLocationId") VALUES (20, 8, 'Eid al-Adha', '2026-05-27', false, 'MP government gazetted holiday 2026', true, false, NULL, '2026-09-22 16:34:52.097878+00', NULL, NULL, NULL, NULL, 5);
INSERT INTO axionpro."OrganizationHolidayCalendar" ("Id", "TenantId", "HolidayName", "HolidayDate", "IsOptional", "Description", "IsActive", "IsSoftDeleted", "AddedById", "AddedDateTime", "UpdatedById", "UpdatedDateTime", "SoftDeletedById", "DeletedDateTime", "TenantLocationId") VALUES (21, 8, 'Maharana Pratap and Chhatrasal Jayanti', '2026-06-17', false, 'MP government gazetted holiday 2026', true, false, NULL, '2026-09-22 16:34:52.097878+00', NULL, NULL, NULL, NULL, 5);
INSERT INTO axionpro."OrganizationHolidayCalendar" ("Id", "TenantId", "HolidayName", "HolidayDate", "IsOptional", "Description", "IsActive", "IsSoftDeleted", "AddedById", "AddedDateTime", "UpdatedById", "UpdatedDateTime", "SoftDeletedById", "DeletedDateTime", "TenantLocationId") VALUES (22, 8, 'Muharram', '2026-06-26', false, 'MP government gazetted holiday 2026', true, false, NULL, '2026-09-22 16:34:52.097878+00', NULL, NULL, NULL, NULL, 5);
INSERT INTO axionpro."OrganizationHolidayCalendar" ("Id", "TenantId", "HolidayName", "HolidayDate", "IsOptional", "Description", "IsActive", "IsSoftDeleted", "AddedById", "AddedDateTime", "UpdatedById", "UpdatedDateTime", "SoftDeletedById", "DeletedDateTime", "TenantLocationId") VALUES (23, 8, 'Guru Purnima', '2026-07-29', true, 'MP government optional holiday 2026; verify organization approval', true, false, NULL, '2026-09-22 16:34:52.097878+00', NULL, NULL, NULL, NULL, 5);
INSERT INTO axionpro."OrganizationHolidayCalendar" ("Id", "TenantId", "HolidayName", "HolidayDate", "IsOptional", "Description", "IsActive", "IsSoftDeleted", "AddedById", "AddedDateTime", "UpdatedById", "UpdatedDateTime", "SoftDeletedById", "DeletedDateTime", "TenantLocationId") VALUES (24, 8, 'Independence Day', '2026-08-15', false, 'MP government gazetted holiday 2026; Saturday', true, false, NULL, '2026-09-22 16:34:52.097878+00', NULL, NULL, NULL, NULL, 5);
INSERT INTO axionpro."OrganizationHolidayCalendar" ("Id", "TenantId", "HolidayName", "HolidayDate", "IsOptional", "Description", "IsActive", "IsSoftDeleted", "AddedById", "AddedDateTime", "UpdatedById", "UpdatedDateTime", "SoftDeletedById", "DeletedDateTime", "TenantLocationId") VALUES (25, 8, 'Milad-un-Nabi', '2026-08-26', false, 'MP government gazetted holiday 2026', true, false, NULL, '2026-09-22 16:34:52.097878+00', NULL, NULL, NULL, NULL, 5);
INSERT INTO axionpro."OrganizationHolidayCalendar" ("Id", "TenantId", "HolidayName", "HolidayDate", "IsOptional", "Description", "IsActive", "IsSoftDeleted", "AddedById", "AddedDateTime", "UpdatedById", "UpdatedDateTime", "SoftDeletedById", "DeletedDateTime", "TenantLocationId") VALUES (26, 8, 'Raksha Bandhan', '2026-08-28', false, 'MP government gazetted holiday 2026', true, false, NULL, '2026-09-22 16:34:52.097878+00', NULL, NULL, NULL, NULL, 5);
INSERT INTO axionpro."OrganizationHolidayCalendar" ("Id", "TenantId", "HolidayName", "HolidayDate", "IsOptional", "Description", "IsActive", "IsSoftDeleted", "AddedById", "AddedDateTime", "UpdatedById", "UpdatedDateTime", "SoftDeletedById", "DeletedDateTime", "TenantLocationId") VALUES (27, 8, 'Janmashtami', '2026-09-04', false, 'MP government gazetted holiday 2026', true, false, NULL, '2026-09-22 16:34:52.097878+00', NULL, NULL, NULL, NULL, 5);
INSERT INTO axionpro."OrganizationHolidayCalendar" ("Id", "TenantId", "HolidayName", "HolidayDate", "IsOptional", "Description", "IsActive", "IsSoftDeleted", "AddedById", "AddedDateTime", "UpdatedById", "UpdatedDateTime", "SoftDeletedById", "DeletedDateTime", "TenantLocationId") VALUES (28, 8, 'Ganesh Chaturthi', '2026-09-14', false, 'MP government gazetted holiday 2026', true, false, NULL, '2026-09-22 16:34:52.097878+00', NULL, NULL, NULL, NULL, 5);
INSERT INTO axionpro."OrganizationHolidayCalendar" ("Id", "TenantId", "HolidayName", "HolidayDate", "IsOptional", "Description", "IsActive", "IsSoftDeleted", "AddedById", "AddedDateTime", "UpdatedById", "UpdatedDateTime", "SoftDeletedById", "DeletedDateTime", "TenantLocationId") VALUES (29, 8, 'Gandhi Jayanti', '2026-10-02', false, 'MP government gazetted holiday 2026', true, false, NULL, '2026-09-22 16:34:52.097878+00', NULL, NULL, NULL, NULL, 5);
INSERT INTO axionpro."OrganizationHolidayCalendar" ("Id", "TenantId", "HolidayName", "HolidayDate", "IsOptional", "Description", "IsActive", "IsSoftDeleted", "AddedById", "AddedDateTime", "UpdatedById", "UpdatedDateTime", "SoftDeletedById", "DeletedDateTime", "TenantLocationId") VALUES (30, 8, 'Dussehra', '2026-10-20', false, 'MP government gazetted holiday 2026', true, false, NULL, '2026-09-22 16:34:52.097878+00', NULL, NULL, NULL, NULL, 5);
INSERT INTO axionpro."OrganizationHolidayCalendar" ("Id", "TenantId", "HolidayName", "HolidayDate", "IsOptional", "Description", "IsActive", "IsSoftDeleted", "AddedById", "AddedDateTime", "UpdatedById", "UpdatedDateTime", "SoftDeletedById", "DeletedDateTime", "TenantLocationId") VALUES (31, 8, 'Maharishi Valmiki Jayanti', '2026-10-26', false, 'MP government gazetted holiday 2026', true, false, NULL, '2026-09-22 16:34:52.097878+00', NULL, NULL, NULL, NULL, 5);
INSERT INTO axionpro."OrganizationHolidayCalendar" ("Id", "TenantId", "HolidayName", "HolidayDate", "IsOptional", "Description", "IsActive", "IsSoftDeleted", "AddedById", "AddedDateTime", "UpdatedById", "UpdatedDateTime", "SoftDeletedById", "DeletedDateTime", "TenantLocationId") VALUES (32, 8, 'Diwali', '2026-11-08', false, 'MP government gazetted holiday 2026; Sunday', true, false, NULL, '2026-09-22 16:34:52.097878+00', NULL, NULL, NULL, NULL, 5);
INSERT INTO axionpro."OrganizationHolidayCalendar" ("Id", "TenantId", "HolidayName", "HolidayDate", "IsOptional", "Description", "IsActive", "IsSoftDeleted", "AddedById", "AddedDateTime", "UpdatedById", "UpdatedDateTime", "SoftDeletedById", "DeletedDateTime", "TenantLocationId") VALUES (33, 8, 'Govardhan Puja', '2026-11-09', false, 'MP government gazetted holiday 2026', true, false, NULL, '2026-09-22 16:34:52.097878+00', NULL, NULL, NULL, NULL, 5);
INSERT INTO axionpro."OrganizationHolidayCalendar" ("Id", "TenantId", "HolidayName", "HolidayDate", "IsOptional", "Description", "IsActive", "IsSoftDeleted", "AddedById", "AddedDateTime", "UpdatedById", "UpdatedDateTime", "SoftDeletedById", "DeletedDateTime", "TenantLocationId") VALUES (34, 8, 'Tribal Pride Day', '2026-11-15', false, 'MP government gazetted holiday 2026; Sunday', true, false, NULL, '2026-09-22 16:34:52.097878+00', NULL, NULL, NULL, NULL, 5);
INSERT INTO axionpro."OrganizationHolidayCalendar" ("Id", "TenantId", "HolidayName", "HolidayDate", "IsOptional", "Description", "IsActive", "IsSoftDeleted", "AddedById", "AddedDateTime", "UpdatedById", "UpdatedDateTime", "SoftDeletedById", "DeletedDateTime", "TenantLocationId") VALUES (35, 8, 'Guru Nanak Jayanti', '2026-11-24', false, 'MP government gazetted holiday 2026', true, false, NULL, '2026-09-22 16:34:52.097878+00', NULL, NULL, NULL, NULL, 5);
INSERT INTO axionpro."OrganizationHolidayCalendar" ("Id", "TenantId", "HolidayName", "HolidayDate", "IsOptional", "Description", "IsActive", "IsSoftDeleted", "AddedById", "AddedDateTime", "UpdatedById", "UpdatedDateTime", "SoftDeletedById", "DeletedDateTime", "TenantLocationId") VALUES (36, 8, 'Christmas Day', '2026-12-25', false, 'MP government gazetted holiday 2026', true, false, NULL, '2026-09-22 16:34:52.097878+00', NULL, NULL, NULL, NULL, 5);
INSERT INTO axionpro."OrganizationHolidayCalendar" ("Id", "TenantId", "HolidayName", "HolidayDate", "IsOptional", "Description", "IsActive", "IsSoftDeleted", "AddedById", "AddedDateTime", "UpdatedById", "UpdatedDateTime", "SoftDeletedById", "DeletedDateTime", "TenantLocationId") VALUES (7, 8, 'Republic Day', '2026-01-26', false, 'MP government gazetted holiday 2026 ddddd', true, false, NULL, '2026-09-22 16:34:52.097878+00', 4, '2026-09-22 18:41:56.243578+00', NULL, NULL, 5);
INSERT INTO axionpro."OrganizationHolidayCalendar" ("Id", "TenantId", "HolidayName", "HolidayDate", "IsOptional", "Description", "IsActive", "IsSoftDeleted", "AddedById", "AddedDateTime", "UpdatedById", "UpdatedDateTime", "SoftDeletedById", "DeletedDateTime", "TenantLocationId") VALUES (6, 8, 'New Years Day', '2026-01-01', true, 'MP government optional holiday 2026; verify organization approval', true, false, NULL, '2026-09-22 16:34:52.097878+00', 4, '2026-09-23 12:50:36.88378+00', NULL, NULL, 5);


--
-- Name: OrganizationHolidayCalendar_Id_seq; Type: SEQUENCE SET; Schema: axionpro; Owner: workforcedb_user
--

SELECT pg_catalog.setval('axionpro."OrganizationHolidayCalendar_Id_seq"', 48, true);


--
-- PostgreSQL database dump complete
--

\unrestrict 4WBaNzo23boehovFewc5YJ3mblT5q4ISgzzqATdTzC6TyHQ8ZxaD4UdgVNIn0E2

