#!/usr/bin/env python3
"""
Simple MSSQL -> PostgreSQL schema converter (best-effort).
Place this script at the repository root and run:
    python tools/mssql_to_postgres.py
It will read `AxionProMSSQLSchema.txt` and write `AxionProPostgresSchema.txt`.
This is not a perfect converter but handles common patterns used in the project:
 - removes database prefix `db_...` and converts schema `AxionPro` -> `axionpro`
 - converts IDENTITY to `GENERATED BY DEFAULT AS IDENTITY`
 - converts `bit` -> `boolean`
 - converts `nvarchar(MAX)`/`varchar(MAX)` -> `text`
 - converts `nvarchar(n)`/`varchar(n)`/`char(n)` -> keeps as `varchar(n)`/`char(n)` (Postgres supports)
 - converts `datetime`/`datetime2` -> `timestamptz`
 - converts `getdate()`/`sysdatetime()`/`getutcdate()` -> `now()` (or timezone for utc)
 - removes COLLATE clauses and SQL Server-specific options
 - converts `CONSTRAINT ... PRIMARY KEY (Id)` kept as-is
 - converts `CREATE NONCLUSTERED INDEX` -> `CREATE INDEX` and removes index options
 - replaces `newid()` default with `gen_random_uuid()` (requires pgcrypto extension)
 - removes `WITH NOCHECK` and other SQL Server alter constraints syntax

Review the produced `AxionProPostgresSchema.txt` and adjust types/constraints manually where needed.
"""

import re
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
INPUT = ROOT / 'AxionProMSSQLSchema.txt'
OUTPUT = ROOT / 'AxionProPostgresSchema.txt'

if not INPUT.exists():
    print(f"Input file not found: {INPUT}")
    raise SystemExit(1)

text = INPUT.read_text(encoding='utf-8')

# 1. Normalize line endings
text = text.replace('\r\n', '\n')

# 2. Remove database prefix like db_ab6be2_quecksilbertechnol.
text = re.sub(r"\bdb_[a-z0-9_]+\.", "", text, flags=re.IGNORECASE)

# 3. Convert schema creation
text = re.sub(r"CREATE SCHEMA\s+AxionPro;", "CREATE SCHEMA IF NOT EXISTS axionpro;\nSET search_path = axionpro, public;", flags=re.IGNORECASE)

# 4. Replace fully-qualified names like AxionPro.Table -> axionpro.table
text = re.sub(r"\bAxionPro\.(\w+)\b", lambda m: f"axionpro.{m.group(1).lower()}", text)

# 5. Replace IDENTITY(a,b) -> GENERATED BY DEFAULT AS IDENTITY
text = re.sub(r"\bIDENTITY\s*\(\s*\d+\s*,\s*\d+\s*\)", "GENERATED BY DEFAULT AS IDENTITY", text, flags=re.IGNORECASE)

# 6. Replace types
# nvarchar(max) -> text
text = re.sub(r"\bnvarchar\s*\(\s*MAX\s*\)", "text", text, flags=re.IGNORECASE)
text = re.sub(r"\bvarchar\s*\(\s*MAX\s*\)", "text", text, flags=re.IGNORECASE)

# nvarchar(n) and varchar(n) -> keep but ensure lower-case and remove COLLATE
text = re.sub(r"\bnvarchar\s*\(", "varchar(", text, flags=re.IGNORECASE)

# remove COLLATE clauses
text = re.sub(r"\s+COLLATE\s+[^\s,\)]+", "", text, flags=re.IGNORECASE)

# bit -> boolean
text = re.sub(r"\bbit\b", "boolean", text, flags=re.IGNORECASE)

# datetime2 / datetime -> timestamptz
text = re.sub(r"\bdatetime2\b", "timestamptz", text, flags=re.IGNORECASE)
text = re.sub(r"\bdatetime\b", "timestamptz", text, flags=re.IGNORECASE)

# date stays

# float -> double precision (Postgres float -> double precision)
text = re.sub(r"\bfloat\b", "double precision", text, flags=re.IGNORECASE)

# varbinary(MAX) -> bytea
text = re.sub(r"\bvarbinary\s*\(\s*MAX\s*\)", "bytea", text, flags=re.IGNORECASE)

# nchar/char -> char/varchar (keep)
text = re.sub(r"\bnchar\b", "char", text, flags=re.IGNORECASE)

# decimal(p,s) keep as numeric(p,s)
text = re.sub(r"\bdecimal\b", "numeric", text, flags=re.IGNORECASE)

# money -> numeric(19,4)
text = re.sub(r"\bmoney\b", "numeric(19,4)", text, flags=re.IGNORECASE)

# newid() -> gen_random_uuid()
text = re.sub(r"newid\s*\(\s*\)", "gen_random_uuid()", text, flags=re.IGNORECASE)

# defaults: getdate(), sysdatetime(), getutcdate() -> now()
text = re.sub(r"\bgetdate\s*\(\s*\)", "now()", text, flags=re.IGNORECASE)
text = re.sub(r"\bsysdatetime\s*\(\s*\)", "now()", text, flags=re.IGNORECASE)
text = re.sub(r"\bgetutcdate\s*\(\s*\)", "timezone('utc', now())", text, flags=re.IGNORECASE)

# dateadd(day,(5),getdate()) -> (now() + interval '5 day')
text = re.sub(r"dateadd\s*\(\s*day\s*,\s*\(?(\d+)\)?\s*,\s*getdate\s*\(\s*\)\s*\)", lambda m: f"(now() + interval '{m.group(1)} day')", text, flags=re.IGNORECASE)

# Remove WITH NOCHECK and CHECK/ALTER ... (best-effort)
text = re.sub(r"ALTER TABLE [^;]+WITH NOCHECK ADD CONSTRAINT [^;]+;", "", text, flags=re.IGNORECASE)

# Remove SQL Server index options and convert to simple CREATE INDEX
text = re.sub(r"CREATE NONCLUSTERED INDEX\s+(\w+)\s+ON\s+([\w\.\[\]]+)\s*\(([^\)]+)\)\s*WITH[^;]+;", lambda m: f"CREATE INDEX {m.group(1)} ON {m.group(2)} ({m.group(3)});", text, flags=re.IGNORECASE)

# Remove ON [PRIMARY] and other filegroup options
text = re.sub(r"\)\s*ON\s*\[PRIMARY\s*\]\s*;", ");", text, flags=re.IGNORECASE)
text = re.sub(r"\)\s*ON\s*\[PRIMARY\s*\]", ")", text, flags=re.IGNORECASE)

# Convert bracketed identifiers [Name] -> Name
text = re.sub(r"\[([^\]]+)\]", lambda m: m.group(1), text)

# Convert schema.table to schema.table (lowercase schema)
text = re.sub(r"\bAxionPro\.(\w+)\b", lambda m: f"axionpro.{m.group(1).lower()}", text, flags=re.IGNORECASE)

# Replace double-quoted defaults like DEFAULT 'Pending' -> keep

# Fix PRIMARY KEY constraint lines referencing Id - keep

# Some MSSQL CHECK constraints syntax may use [] - convert by removing brackets
text = re.sub(r"\[([^\]]+)\]", lambda m: m.group(1), text)

# Replace ON DELETE CASCADE ON UPDATE CASCADE -> ON DELETE CASCADE (Postgres doesn't support ON UPDATE CASCADE in same way in some contexts, keep ON UPDATE if present)
text = re.sub(r"ON UPDATE CASCADE", "ON UPDATE CASCADE", text, flags=re.IGNORECASE)

# Replace DEFAULT 0/1 for boolean: ensure true/false
text = re.sub(r"DEFAULT\s+0(\s|\))", "DEFAULT false\1", text, flags=re.IGNORECASE)
text = re.sub(r"DEFAULT\s+1(\s|\))", "DEFAULT true\1", text, flags=re.IGNORECASE)

# Remove multiple spaces
# text = re.sub(r"[ \t]+", " ", text)

# Prepend header: extensions and search_path
header = "-- Converted Postgres schema (best-effort)\n-- Review carefully before applying to DB\nCREATE EXTENSION IF NOT EXISTS \"pgcrypto\"; -- for gen_random_uuid()\nCREATE SCHEMA IF NOT EXISTS axionpro;\nSET search_path = axionpro, public;\n\n"

OUT = header + text

OUTPUT.write_text(OUT, encoding='utf-8')
print(f"Wrote converted schema to: {OUTPUT}")
print("NOTE: Review the output and adjust types, constraints, and indexes manually.")
